//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Localized.loadError
 Localized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case popupChooseDealershipTitle
	case viewStartRequestPickup
	case viewDrivetoArriveatCustomer
	case viewRecordLoanerMileage
	case errorInvalidPassword
	case viewExchangeKeysPickupSwipeTitle
	case number6
	case change
	case viewDrivetoCustomer
	case viewChecklistLoanerAgreementLabel
	case viewStartRequestRetrieveCustomerVehicle
	case viewRetrieveFormsSwipeTitle
	case viewRetrieveFormsInfoNext
	case number2
	case viewPhoneAdd
	case viewDrawerNavigationPreferenceGoogle
	case viewInspectCustomer
	case delivery
	case permissionsCameraDeniedMessage
	case notificationForegroundServiceTextInspectNotes
	case viewScheduleEmptyToday
	case viewReceiveVehicleLoanerSwipeButtonTitle
	case errorDuplicateLoanerVehicleBookingAssignment
	case viewStartRequestRetrieveForms
	case helpIForgotMyPassword
	case volvoYearModel
	case viewHelpOptionDetailEmailDealer
	case help
	case no
	case errorLocationServiceUnavailable
	case error
	case viewGetToText
	case errorEnterLoanerMileage
	case yourAccount
	case viewProfileChangeContact
	case viewScheduleListHeaderNameCompletedToday
	case viewArrivedatCustomer
	case min
	case contact
	case passwordRequirements
	case viewReceiveVehicleCustomerSwipeButtonTitle
	case viewExchangeKeysDeliverySwipeTitle
	case loanerColon
	case popupAlreadyStartedDrivingPositive
	case popupTooFarFromCustomerTitle
	case notificationForegroundServiceTextDriverInspectCustomer
	case confirmPhoneNumber
	case notificationForegroundServiceTextDriveLoanerToDealership
	case popupHardRefreshTitle
	case viewScheduleStateRefreshButton
	case number7
	case viewScheduleListHeaderNameCurrent
	case requestCanceled
	case edit
	case viewScheduleListItemTypePickup
	case yes
	case popupPhoneVerificationResendCodeMessage
	case viewIntroFooterSignin
	case errorOffline
	case viewExchangeKeysInfoReminder
	case signout
	case errorIllegalRequestTaskChange
	case pickupColon
	case popupGetToCustomerTitle
	case settings
	case viewStartRequestRetrieveLoaner
	case notificationForegroundServiceTextDriverInspectLoaner
	case viewReceiveVehicleLoanerNext
	case viewInspectDocumentsOverlayInfo
	case new
	case viewDrawerProfileOptionsChangePassword
	case viewHelpOptionDetailCallDealer
	case viewDrivetoSwipeButtonTitle
	case errorAmbiguousVehicleUpsert
	case viewReceiveVehicleLoaner
	case errorUnknown
	case notificationForegroundServiceTextDriverInspectDocuments
	case notificationForegroundServiceTextDriverVehicleToCustomer
	case notificationForegroundServiceTextDriverGetToCustomer
	case mins
	case number9
	case popupPhoneVerificationResendCodeTitle
	case phoneNumberCannotBeEmpty
	case number8
	case requestCompleted
	case viewPhoneAddLabel
	case notificationForegroundServiceTextRetrieveVehicle
	case color
	case viewSigninPhoto
	case emailAddress
	case popupMileageMaxConfirmation
	case viewInspectLoaner
	case permissionsLocationDeniedMessage
	case year
	case viewArrivedatDeliverySwipeButtonTitle
	case viewInspectDocumentsMinPhotosWarning
	case permissionsCameraDeniedTitle
	case later
	case errorForcedUpgradeTitle
	case viewSigninEmailInvalid
	case inspectVehicle
	case viewSigninForgotPassword
	case recentMileageColon
	case popupTooFarFromCustomerMessage
	case notificationForegroundServiceTextDriverLoanerToCustomer
	case viewNavigateText
	case update
	case viewDrawerProfileOptionsAttributions
	case viewNavigateAddressCopiedToClipboard
	case viewTosContent
	case iAmSure
	case viewExchangeKeysSwipeButtonTitle
	case popupMileageMinConfirmation
	case remove
	case resendCode
	case viewRetrieveVehicleCustomer
	case popupAlreadyStartedDrivingTitle
	case popupSelectTimeSlotUnavailableCallDealership
	case errorLocationServiceNotOfferedInYourArea
	case viewTosContentTermsOfServiceUrl
	case errorIllegalRequestStateChange
	case viewTosContentPrivacyPolicyTitle
	case popupGetToDealershipCopyToClipboard
	case viewTosContentPrivacyPolicyUrl
	case viewIntro
	case popupGetToCustomerCopyToClipboard
	case back
	case viewSchedule
	case confirmNewPassword
	case vehicleMake
	case notificationForegroundServiceTextDriverMeetWithCustomer
	case errorSoftUpgradeTitle
	case notAvailable
	case viewReceiveVehicleInfoReminder
	case currentPassword
	case loading
	case errorVerifyPhoneNumber
	case number10
	case close
	case errorLocationOutOfPickupArea
	case viewInspectLoanerMinPhotosWarning
	case viewTosContentTermsOfServiceTitle
	case viewScheduleStateRefreshInfo
	case popupTooFarFromCustomerPositive
	case viewReceiveVehicle
	case errorPhoneNumberTaken
	case viewSigninActionSignin
	case readMore
	case viewInspectCustomerMinPhotoWarning
	case viewTosContentTermsOfService
	case viewDrawerContactDealershipText
	case popupAddNewLocationLabel
	case viewInspectCustomerOverlayInfo
	case errorSoftUpgradeMessage
	case viewInspectNotesSwipeButtonTitle
	case notificationForegroundServiceTextRetrieveForms
	case viewInspectLoanerMinPhotoWarning
	case viewRetrieveVehicle
	case viewInspectLoanerOverlayInfo
	case notificationBatteryWarningTitle
	case toastSettingsLocationDisabled
	case popupForgotPasswordMessage
	case number1
	case inspectVehicles
	case errorInvalidLastName
	case dealership
	case exchangeKeys
	case popupGetToDealershipTitle
	case popupDeviceChangeMessage
	case notificationForegroundServiceTextGetToDealership
	case errorInvalidEmail
	case viewRetrieveVehicleCustomerSwipeTitle
	case errorAmbiguousCustomerUpsert
	case notificationForegroundServiceTitle
	case password
	case viewScheduleServiceTypeOtherUnknown
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case notesColon
	case viewRecordLoanerMileagePickupSwipeButtonTitle
	case notificationActionOpen
	case confirmationCode
	case viewGettoDealershipSwipeButtonTitle
	case errorInvalidPasswordConfirm
	case viewTosContentPrivacyPolicy
	case returnToDealership
	case viewDrawerNavigationPreferenceWaze
	case viewRecordLoanerMileageDropoffSwipeButtonTitle
	case number5
	case errorFaceDetectionMessage
	case helpICantUpdateMyPhone
	case viewEmailSubject
	case viewArrivedatDeliveryInspectVehicles
	case requestReset
	case done
	case notificationForegroundServiceTextDriveCustomerToDealership
	case viewDrawerProfileOptionsChangeContact
	case viewPhoneVerificationLabel
	case phoneNumber
	case viewScheduleServiceStatusSelfAdvisorPickup
	case serviceColon
	case viewHelpOptionDetailEmailVolvo
	case viewSigninPasswordShort
	case viewScheduleState
	case viewContactText
	case viewRetrieveVehicleCustomerInfoNext
	case number4
	case addressColon
	case viewArrivedat
	case viewHelpOptionDetailCallVolvo
	case appName
	case repairOrderColon
	case viewScheduleListItemTypeDeliver
	case popupAlreadyStartedDrivingMessage
	case errorInvalidUserDisabled
	case errorOnline
	case retry
	case notNow
	case popupDeviceChangeTitle
	case errorRemoveVehicleError
	case dismiss
	case viewGettoCustomer
	case errorRequestNotCancelable
	case errorInvalidFirstName
	case popupSoftUpgradeNegative
	case viewScheduleListHeaderNameUpcomingToday
	case modelColon
	case popupTooFarFromDealershipMessage
	case licensePlateColon
	case viewSignin
	case notificationBatteryWarningTextBig
	case popupSignoutConfirmationMessage
	case notificationForegroundServiceTextReceiveLoaner
	case popupUpdatingLocation
	case viewSigninPopupProgressSignin
	case errorInvalidPhoneVerificationCode
	case viewRetrieveVehicleLoaner
	case viewStartRequestDropoff
	case viewContactCall
	case next
	case viewReceiveVehicleCustomer
	case permissionsLocationDeniedTitle
	case viewStartRequestSwipeButtonTitle
	case viewDrawerContactDealershipCall
	case viewDriveto
	case viewSwipeButtonInnerText
	case viewEmailBody
	case goBack
	case createPassword
	case popupTooFarFromDealershipTitle
	case notificationForegroundServiceTextRecordLoanerMileage
	case pickup
	case errorForcedUpgradeMessage
	case errorUserDisabled
	case viewIntroFooterSignup
	case unknown
	case errorInvalidApplicationVersion
	case viewGettoCustomerSwipeButtonTitle
	case viewScheduleServiceStatusSelfDealershipNavigate
	case viewHelpCategoryLastLeg
	case openSettings
	case exchangeKey
	case requestTaskChangedFromBackend
	case errorOops
	case notificationBatteryWarningText
	case phoneNumberAlreadyTaken
	case viewScheduleCurrent
	case viewNavigateWazeText
	case viewHelpCategoryHowLuxeByVolvoWorks
	case updateNow
	case keyCodeColon
	case errorInvalidPasswordUnauthorizedCharacters
	case notificationForegroundServiceTextDriverExchangeKeys
	case cancel
	case viewInspectNotes
	case viewInspectCustomerMinPhotosWarning
	case errorInvalidCredentials
	case viewDrawerProfileOptionsSignout
	case errorLocationOutOfDropoffArea
	case number3
	case viewLogoTitle
	case viewProfileChangePasswordTemp
	case skip
	case errorInvalidVerificationCode
	case viewArrivedatPickupSwipeButtonTitle
	case viewInspectNotesDescriptionHint
	case viewRetrieveForms
	case viewInspectDocuments
	case viewEmailIntentChooserTitle
	case add
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case number11
	case customerColon
	case viewReturntoSwipeButtonTitle
	case support
	case model
	case ok
	case notificationForegroundServiceTextRetrieveLoaner
	case viewDrawerNavigationPreferenceTitle
	case viewSoftwareLicences
	case errorInvalidPhoneNumber
	case viewGettoCustomerArriveatCustomer
	case errorAccountAlreadyExists
	case popupHardRefreshMessage
	case viewRetrieveVehicleLoanerSwipeTitle
	case viewScheduleEmpty
	case popupTooFarFromDealershipPositive
	case viewRecordLoanerMileageDropoffInfoNext
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case viewInspectDocumentsMinPhotoWarning
	case deliveryColon
	case popupForgotPasswordTitle
	case newPassword

    var key : String {
        switch self {
            case .popupChooseDealershipTitle:
					return "popupChooseDealershipTitle"
			case .viewStartRequestPickup:
					return "viewStartRequestPickup"
			case .viewDrivetoArriveatCustomer:
					return "viewDrivetoArriveatCustomer"
			case .viewRecordLoanerMileage:
					return "viewRecordLoanerMileage"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .viewExchangeKeysPickupSwipeTitle:
					return "viewExchangeKeysPickupSwipeTitle"
			case .number6:
					return "number6"
			case .change:
					return "change"
			case .viewDrivetoCustomer:
					return "viewDrivetoCustomer"
			case .viewChecklistLoanerAgreementLabel:
					return "viewChecklistLoanerAgreementLabel"
			case .viewStartRequestRetrieveCustomerVehicle:
					return "viewStartRequestRetrieveCustomerVehicle"
			case .viewRetrieveFormsSwipeTitle:
					return "viewRetrieveFormsSwipeTitle"
			case .viewRetrieveFormsInfoNext:
					return "viewRetrieveFormsInfoNext"
			case .number2:
					return "number2"
			case .viewPhoneAdd:
					return "viewPhoneAdd"
			case .viewDrawerNavigationPreferenceGoogle:
					return "viewDrawerNavigationPreferenceGoogle"
			case .viewInspectCustomer:
					return "viewInspectCustomer"
			case .delivery:
					return "delivery"
			case .permissionsCameraDeniedMessage:
					return "permissionsCameraDeniedMessage"
			case .notificationForegroundServiceTextInspectNotes:
					return "notificationForegroundServiceTextInspectNotes"
			case .viewScheduleEmptyToday:
					return "viewScheduleEmptyToday"
			case .viewReceiveVehicleLoanerSwipeButtonTitle:
					return "viewReceiveVehicleLoanerSwipeButtonTitle"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
			case .viewStartRequestRetrieveForms:
					return "viewStartRequestRetrieveForms"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .volvoYearModel:
					return "volvoYearModel"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .help:
					return "help"
			case .no:
					return "no"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .error:
					return "error"
			case .viewGetToText:
					return "viewGetToText"
			case .errorEnterLoanerMileage:
					return "errorEnterLoanerMileage"
			case .yourAccount:
					return "yourAccount"
			case .viewProfileChangeContact:
					return "viewProfileChangeContact"
			case .viewScheduleListHeaderNameCompletedToday:
					return "viewScheduleListHeaderNameCompletedToday"
			case .viewArrivedatCustomer:
					return "viewArrivedatCustomer"
			case .min:
					return "min"
			case .contact:
					return "contact"
			case .passwordRequirements:
					return "passwordRequirements"
			case .viewReceiveVehicleCustomerSwipeButtonTitle:
					return "viewReceiveVehicleCustomerSwipeButtonTitle"
			case .viewExchangeKeysDeliverySwipeTitle:
					return "viewExchangeKeysDeliverySwipeTitle"
			case .loanerColon:
					return "loanerColon"
			case .popupAlreadyStartedDrivingPositive:
					return "popupAlreadyStartedDrivingPositive"
			case .popupTooFarFromCustomerTitle:
					return "popupTooFarFromCustomerTitle"
			case .notificationForegroundServiceTextDriverInspectCustomer:
					return "notificationForegroundServiceTextDriverInspectCustomer"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .notificationForegroundServiceTextDriveLoanerToDealership:
					return "notificationForegroundServiceTextDriveLoanerToDealership"
			case .popupHardRefreshTitle:
					return "popupHardRefreshTitle"
			case .viewScheduleStateRefreshButton:
					return "viewScheduleStateRefreshButton"
			case .number7:
					return "number7"
			case .viewScheduleListHeaderNameCurrent:
					return "viewScheduleListHeaderNameCurrent"
			case .requestCanceled:
					return "requestCanceled"
			case .edit:
					return "edit"
			case .viewScheduleListItemTypePickup:
					return "viewScheduleListItemTypePickup"
			case .yes:
					return "yes"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .errorOffline:
					return "errorOffline"
			case .viewExchangeKeysInfoReminder:
					return "viewExchangeKeysInfoReminder"
			case .signout:
					return "signout"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .pickupColon:
					return "pickupColon"
			case .popupGetToCustomerTitle:
					return "popupGetToCustomerTitle"
			case .settings:
					return "settings"
			case .viewStartRequestRetrieveLoaner:
					return "viewStartRequestRetrieveLoaner"
			case .notificationForegroundServiceTextDriverInspectLoaner:
					return "notificationForegroundServiceTextDriverInspectLoaner"
			case .viewReceiveVehicleLoanerNext:
					return "viewReceiveVehicleLoanerNext"
			case .viewInspectDocumentsOverlayInfo:
					return "viewInspectDocumentsOverlayInfo"
			case .new:
					return "new"
			case .viewDrawerProfileOptionsChangePassword:
					return "viewDrawerProfileOptionsChangePassword"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .viewDrivetoSwipeButtonTitle:
					return "viewDrivetoSwipeButtonTitle"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .viewReceiveVehicleLoaner:
					return "viewReceiveVehicleLoaner"
			case .errorUnknown:
					return "errorUnknown"
			case .notificationForegroundServiceTextDriverInspectDocuments:
					return "notificationForegroundServiceTextDriverInspectDocuments"
			case .notificationForegroundServiceTextDriverVehicleToCustomer:
					return "notificationForegroundServiceTextDriverVehicleToCustomer"
			case .notificationForegroundServiceTextDriverGetToCustomer:
					return "notificationForegroundServiceTextDriverGetToCustomer"
			case .mins:
					return "mins"
			case .number9:
					return "number9"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .number8:
					return "number8"
			case .requestCompleted:
					return "requestCompleted"
			case .viewPhoneAddLabel:
					return "viewPhoneAddLabel"
			case .notificationForegroundServiceTextRetrieveVehicle:
					return "notificationForegroundServiceTextRetrieveVehicle"
			case .color:
					return "color"
			case .viewSigninPhoto:
					return "viewSigninPhoto"
			case .emailAddress:
					return "emailAddress"
			case .popupMileageMaxConfirmation:
					return "popupMileageMaxConfirmation"
			case .viewInspectLoaner:
					return "viewInspectLoaner"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .year:
					return "year"
			case .viewArrivedatDeliverySwipeButtonTitle:
					return "viewArrivedatDeliverySwipeButtonTitle"
			case .viewInspectDocumentsMinPhotosWarning:
					return "viewInspectDocumentsMinPhotosWarning"
			case .permissionsCameraDeniedTitle:
					return "permissionsCameraDeniedTitle"
			case .later:
					return "later"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .viewSigninEmailInvalid:
					return "viewSigninEmailInvalid"
			case .inspectVehicle:
					return "inspectVehicle"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .recentMileageColon:
					return "recentMileageColon"
			case .popupTooFarFromCustomerMessage:
					return "popupTooFarFromCustomerMessage"
			case .notificationForegroundServiceTextDriverLoanerToCustomer:
					return "notificationForegroundServiceTextDriverLoanerToCustomer"
			case .viewNavigateText:
					return "viewNavigateText"
			case .update:
					return "update"
			case .viewDrawerProfileOptionsAttributions:
					return "viewDrawerProfileOptionsAttributions"
			case .viewNavigateAddressCopiedToClipboard:
					return "viewNavigateAddressCopiedToClipboard"
			case .viewTosContent:
					return "viewTosContent"
			case .iAmSure:
					return "iAmSure"
			case .viewExchangeKeysSwipeButtonTitle:
					return "viewExchangeKeysSwipeButtonTitle"
			case .popupMileageMinConfirmation:
					return "popupMileageMinConfirmation"
			case .remove:
					return "remove"
			case .resendCode:
					return "resendCode"
			case .viewRetrieveVehicleCustomer:
					return "viewRetrieveVehicleCustomer"
			case .popupAlreadyStartedDrivingTitle:
					return "popupAlreadyStartedDrivingTitle"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .popupGetToDealershipCopyToClipboard:
					return "popupGetToDealershipCopyToClipboard"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .viewIntro:
					return "viewIntro"
			case .popupGetToCustomerCopyToClipboard:
					return "popupGetToCustomerCopyToClipboard"
			case .back:
					return "back"
			case .viewSchedule:
					return "viewSchedule"
			case .confirmNewPassword:
					return "confirmNewPassword"
			case .vehicleMake:
					return "vehicleMake"
			case .notificationForegroundServiceTextDriverMeetWithCustomer:
					return "notificationForegroundServiceTextDriverMeetWithCustomer"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .notAvailable:
					return "notAvailable"
			case .viewReceiveVehicleInfoReminder:
					return "viewReceiveVehicleInfoReminder"
			case .currentPassword:
					return "currentPassword"
			case .loading:
					return "loading"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .number10:
					return "number10"
			case .close:
					return "close"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .viewInspectLoanerMinPhotosWarning:
					return "viewInspectLoanerMinPhotosWarning"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .viewScheduleStateRefreshInfo:
					return "viewScheduleStateRefreshInfo"
			case .popupTooFarFromCustomerPositive:
					return "popupTooFarFromCustomerPositive"
			case .viewReceiveVehicle:
					return "viewReceiveVehicle"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .viewSigninActionSignin:
					return "viewSigninActionSignin"
			case .readMore:
					return "readMore"
			case .viewInspectCustomerMinPhotoWarning:
					return "viewInspectCustomerMinPhotoWarning"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .viewDrawerContactDealershipText:
					return "viewDrawerContactDealershipText"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .viewInspectCustomerOverlayInfo:
					return "viewInspectCustomerOverlayInfo"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .viewInspectNotesSwipeButtonTitle:
					return "viewInspectNotesSwipeButtonTitle"
			case .notificationForegroundServiceTextRetrieveForms:
					return "notificationForegroundServiceTextRetrieveForms"
			case .viewInspectLoanerMinPhotoWarning:
					return "viewInspectLoanerMinPhotoWarning"
			case .viewRetrieveVehicle:
					return "viewRetrieveVehicle"
			case .viewInspectLoanerOverlayInfo:
					return "viewInspectLoanerOverlayInfo"
			case .notificationBatteryWarningTitle:
					return "notificationBatteryWarningTitle"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .popupForgotPasswordMessage:
					return "popupForgotPasswordMessage"
			case .number1:
					return "number1"
			case .inspectVehicles:
					return "inspectVehicles"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .dealership:
					return "dealership"
			case .exchangeKeys:
					return "exchangeKeys"
			case .popupGetToDealershipTitle:
					return "popupGetToDealershipTitle"
			case .popupDeviceChangeMessage:
					return "popupDeviceChangeMessage"
			case .notificationForegroundServiceTextGetToDealership:
					return "notificationForegroundServiceTextGetToDealership"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .viewRetrieveVehicleCustomerSwipeTitle:
					return "viewRetrieveVehicleCustomerSwipeTitle"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .notificationForegroundServiceTitle:
					return "notificationForegroundServiceTitle"
			case .password:
					return "password"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .notesColon:
					return "notesColon"
			case .viewRecordLoanerMileagePickupSwipeButtonTitle:
					return "viewRecordLoanerMileagePickupSwipeButtonTitle"
			case .notificationActionOpen:
					return "notificationActionOpen"
			case .confirmationCode:
					return "confirmationCode"
			case .viewGettoDealershipSwipeButtonTitle:
					return "viewGettoDealershipSwipeButtonTitle"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .returnToDealership:
					return "returnToDealership"
			case .viewDrawerNavigationPreferenceWaze:
					return "viewDrawerNavigationPreferenceWaze"
			case .viewRecordLoanerMileageDropoffSwipeButtonTitle:
					return "viewRecordLoanerMileageDropoffSwipeButtonTitle"
			case .number5:
					return "number5"
			case .errorFaceDetectionMessage:
					return "errorFaceDetectionMessage"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .viewArrivedatDeliveryInspectVehicles:
					return "viewArrivedatDeliveryInspectVehicles"
			case .requestReset:
					return "requestReset"
			case .done:
					return "done"
			case .notificationForegroundServiceTextDriveCustomerToDealership:
					return "notificationForegroundServiceTextDriveCustomerToDealership"
			case .viewDrawerProfileOptionsChangeContact:
					return "viewDrawerProfileOptionsChangeContact"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .phoneNumber:
					return "phoneNumber"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .serviceColon:
					return "serviceColon"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .viewSigninPasswordShort:
					return "viewSigninPasswordShort"
			case .viewScheduleState:
					return "viewScheduleState"
			case .viewContactText:
					return "viewContactText"
			case .viewRetrieveVehicleCustomerInfoNext:
					return "viewRetrieveVehicleCustomerInfoNext"
			case .number4:
					return "number4"
			case .addressColon:
					return "addressColon"
			case .viewArrivedat:
					return "viewArrivedat"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .appName:
					return "appName"
			case .repairOrderColon:
					return "repairOrderColon"
			case .viewScheduleListItemTypeDeliver:
					return "viewScheduleListItemTypeDeliver"
			case .popupAlreadyStartedDrivingMessage:
					return "popupAlreadyStartedDrivingMessage"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .errorOnline:
					return "errorOnline"
			case .retry:
					return "retry"
			case .notNow:
					return "notNow"
			case .popupDeviceChangeTitle:
					return "popupDeviceChangeTitle"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .dismiss:
					return "dismiss"
			case .viewGettoCustomer:
					return "viewGettoCustomer"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .viewScheduleListHeaderNameUpcomingToday:
					return "viewScheduleListHeaderNameUpcomingToday"
			case .modelColon:
					return "modelColon"
			case .popupTooFarFromDealershipMessage:
					return "popupTooFarFromDealershipMessage"
			case .licensePlateColon:
					return "licensePlateColon"
			case .viewSignin:
					return "viewSignin"
			case .notificationBatteryWarningTextBig:
					return "notificationBatteryWarningTextBig"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .notificationForegroundServiceTextReceiveLoaner:
					return "notificationForegroundServiceTextReceiveLoaner"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .viewSigninPopupProgressSignin:
					return "viewSigninPopupProgressSignin"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .viewRetrieveVehicleLoaner:
					return "viewRetrieveVehicleLoaner"
			case .viewStartRequestDropoff:
					return "viewStartRequestDropoff"
			case .viewContactCall:
					return "viewContactCall"
			case .next:
					return "next"
			case .viewReceiveVehicleCustomer:
					return "viewReceiveVehicleCustomer"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .viewStartRequestSwipeButtonTitle:
					return "viewStartRequestSwipeButtonTitle"
			case .viewDrawerContactDealershipCall:
					return "viewDrawerContactDealershipCall"
			case .viewDriveto:
					return "viewDriveto"
			case .viewSwipeButtonInnerText:
					return "viewSwipeButtonInnerText"
			case .viewEmailBody:
					return "viewEmailBody"
			case .goBack:
					return "goBack"
			case .createPassword:
					return "createPassword"
			case .popupTooFarFromDealershipTitle:
					return "popupTooFarFromDealershipTitle"
			case .notificationForegroundServiceTextRecordLoanerMileage:
					return "notificationForegroundServiceTextRecordLoanerMileage"
			case .pickup:
					return "pickup"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .unknown:
					return "unknown"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .viewGettoCustomerSwipeButtonTitle:
					return "viewGettoCustomerSwipeButtonTitle"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .openSettings:
					return "openSettings"
			case .exchangeKey:
					return "exchangeKey"
			case .requestTaskChangedFromBackend:
					return "requestTaskChangedFromBackend"
			case .errorOops:
					return "errorOops"
			case .notificationBatteryWarningText:
					return "notificationBatteryWarningText"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .viewScheduleCurrent:
					return "viewScheduleCurrent"
			case .viewNavigateWazeText:
					return "viewNavigateWazeText"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .updateNow:
					return "updateNow"
			case .keyCodeColon:
					return "keyCodeColon"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .notificationForegroundServiceTextDriverExchangeKeys:
					return "notificationForegroundServiceTextDriverExchangeKeys"
			case .cancel:
					return "cancel"
			case .viewInspectNotes:
					return "viewInspectNotes"
			case .viewInspectCustomerMinPhotosWarning:
					return "viewInspectCustomerMinPhotosWarning"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .viewDrawerProfileOptionsSignout:
					return "viewDrawerProfileOptionsSignout"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .number3:
					return "number3"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .viewProfileChangePasswordTemp:
					return "viewProfileChangePasswordTemp"
			case .skip:
					return "skip"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .viewArrivedatPickupSwipeButtonTitle:
					return "viewArrivedatPickupSwipeButtonTitle"
			case .viewInspectNotesDescriptionHint:
					return "viewInspectNotesDescriptionHint"
			case .viewRetrieveForms:
					return "viewRetrieveForms"
			case .viewInspectDocuments:
					return "viewInspectDocuments"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .add:
					return "add"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .number11:
					return "number11"
			case .customerColon:
					return "customerColon"
			case .viewReturntoSwipeButtonTitle:
					return "viewReturntoSwipeButtonTitle"
			case .support:
					return "support"
			case .model:
					return "model"
			case .ok:
					return "ok"
			case .notificationForegroundServiceTextRetrieveLoaner:
					return "notificationForegroundServiceTextRetrieveLoaner"
			case .viewDrawerNavigationPreferenceTitle:
					return "viewDrawerNavigationPreferenceTitle"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .viewGettoCustomerArriveatCustomer:
					return "viewGettoCustomerArriveatCustomer"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .popupHardRefreshMessage:
					return "popupHardRefreshMessage"
			case .viewRetrieveVehicleLoanerSwipeTitle:
					return "viewRetrieveVehicleLoanerSwipeTitle"
			case .viewScheduleEmpty:
					return "viewScheduleEmpty"
			case .popupTooFarFromDealershipPositive:
					return "popupTooFarFromDealershipPositive"
			case .viewRecordLoanerMileageDropoffInfoNext:
					return "viewRecordLoanerMileageDropoffInfoNext"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .viewInspectDocumentsMinPhotoWarning:
					return "viewInspectDocumentsMinPhotoWarning"
			case .deliveryColon:
					return "deliveryColon"
			case .popupForgotPasswordTitle:
					return "popupForgotPasswordTitle"
			case .newPassword:
					return "newPassword"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
