//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Localized.loadError
 Localized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case next
	case notAvailable
	case viewHelpCategoryHowLuxeByVolvoWorks
	case notNow
	case inspectVehicle
	case popupUpdatingLocation
	case popupAlreadyStartedDrivingTitle
	case viewNavigateAddressCopiedToClipboard
	case permissionsCameraDeniedTitle
	case viewScheduleListHeaderNameCompletedToday
	case newPassword
	case confirmPhoneNumber
	case viewGettoCustomerArriveatCustomer
	case viewScheduleListItemTypeDeliver
	case errorIllegalRequestStateChange
	case inspectVehicles
	case vehicleMake
	case viewInspectLoanerMinPhotosWarning
	case iAmSure
	case viewNavigateText
	case viewStartRequestSwipeButtonTitle
	case repairOrderColon
	case viewRetrieveFormsSwipeTitle
	case viewSoftwareLicences
	case viewDrivetoSwipeButtonTitle
	case viewSignupPasswordRequireNumber
	case viewScheduleEmptyToday
	case popupGetToDealershipTitle
	case phoneNumberCannotBeEmpty
	case year
	case viewInspectLoanerMinPhotoWarning
	case viewIntroFooterSignup
	case viewSignin
	case viewSigninPasswordShort
	case back
	case viewScheduleListHeaderNameCurrent
	case popupGetToCustomerCopyToClipboard
	case ok
	case viewStartRequestRetrieveCustomerVehicle
	case resendCode
	case viewTosContentPrivacyPolicy
	case loanerColon
	case popupMileageMinConfirmation
	case new
	case errorFaceDetectionMessage
	case viewSigninForgotPassword
	case min
	case popupAlreadyStartedDrivingMessage
	case notificationForegroundServiceTextDriveCustomerToDealership
	case exchangeKeys
	case viewGettoCustomerSwipeButtonTitle
	case viewIntro
	case viewExchangeKeysDeliverySwipeTitle
	case viewInspectNotesSwipeButtonTitle
	case notificationForegroundServiceTextDriverInspectLoaner
	case skip
	case errorInvalidPassword
	case notificationForegroundServiceTextDriverLoanerToCustomer
	case pickup
	case popupSoftUpgradeNegative
	case popupPhoneVerificationResendCodeMessage
	case helpICantUpdateMyPhone
	case popupTooFarFromDealershipMessage
	case number9
	case viewRetrieveVehicleCustomer
	case viewDriveto
	case viewHelpOptionDetailCallVolvo
	case later
	case errorInvalidPasswordConfirm
	case viewGettoDealershipSwipeButtonTitle
	case viewContactText
	case notificationForegroundServiceTextGetToDealership
	case errorInvalidPhoneVerificationCode
	case viewReceiveVehicle
	case notificationForegroundServiceTitle
	case viewRetrieveVehicleLoanerSwipeTitle
	case viewRecordLoanerMileageDropoffInfoNext
	case viewNavigateWazeText
	case notificationForegroundServiceTextRetrieveVehicle
	case viewInspectDocumentsMinPhotosWarning
	case viewDrivetoCustomer
	case viewSwipeButtonInnerText
	case viewPhoneAddLabel
	case viewDrivetoArriveatCustomer
	case goBack
	case viewHelpOptionDetailEmailDealer
	case viewReceiveVehicleCustomerSwipeButtonTitle
	case helpIForgotMyPassword
	case viewChecklistLoanerAgreementLabel
	case readMore
	case permissionsLocationDeniedMessage
	case viewDrawerContactDealershipText
	case errorIllegalRequestTaskChange
	case errorSoftUpgradeMessage
	case viewScheduleServiceStatusSelfDealershipNavigate
	case viewDrawerProfileOptionsAttributions
	case number8
	case emailAddress
	case number1
	case color
	case settings
	case errorRequestNotCancelable
	case viewInspectDocumentsOverlayInfo
	case viewLogoTitle
	case recentMileageColon
	case notificationForegroundServiceTextRecordLoanerMileage
	case number11
	case errorSynchingRequest
	case viewArrivedat
	case viewTosContentTermsOfService
	case viewInspectCustomer
	case deliveryColon
	case updateNow
	case viewStartRequestPickup
	case addressColon
	case viewSigninActionSignin
	case licensePlateColon
	case popupTooFarFromCustomerPositive
	case viewInspectCustomerMinPhotosWarning
	case viewTosContentPrivacyPolicyTitle
	case viewScheduleServiceTypeOtherUnknown
	case viewSigninPhoto
	case popupDeviceChangeMessage
	case password
	case notificationForegroundServiceTextDriverExchangeKeys
	case notificationBatteryWarningTitle
	case viewContactCall
	case notificationForegroundServiceTextDriverInspectCustomer
	case errorInvalidPhoneNumber
	case remove
	case notificationForegroundServiceTextRetrieveLoaner
	case viewDrawerProfileOptionsChangeContact
	case errorUserDisabled
	case errorUnknown
	case viewRecordLoanerMileage
	case viewSigninPopupProgressSignin
	case viewScheduleStateRefreshButton
	case errorVerifyPhoneNumber
	case requestCompleted
	case notificationForegroundServiceTextDriveLoanerToDealership
	case viewHelpCategoryLastLeg
	case errorDuplicateLoanerVehicleBookingAssignment
	case viewSignupPasswordRequireLetter
	case viewEmailIntentChooserTitle
	case viewPhoneVerificationLabel
	case popupTooFarFromDealershipPositive
	case errorInvalidPasswordUnauthorizedCharacters
	case viewStartRequestRetrieveLoaner
	case help
	case exchangeKey
	case notesColon
	case viewInspectNotes
	case viewScheduleListHeaderNameUpcomingToday
	case viewArrivedatDeliverySwipeButtonTitle
	case viewInspectDocumentsMinPhotoWarning
	case error
	case notificationForegroundServiceTextDriverInspectDocuments
	case viewHelpOptionDetailEmailVolvo
	case dealership
	case notificationBatteryWarningText
	case confirmationCode
	case errorInvalidCharacter
	case errorInvalidApplicationVersion
	case viewScheduleCurrent
	case viewInspectLoaner
	case viewExchangeKeysSwipeButtonTitle
	case errorEnterLoanerMileage
	case notificationForegroundServiceTextDriverMeetWithCustomer
	case errorLocationOutOfDropoffArea
	case errorOnline
	case number4
	case errorRemoveVehicleError
	case viewReceiveVehicleLoanerNext
	case viewRetrieveVehicleCustomerInfoNext
	case number3
	case notificationActionOpen
	case viewRetrieveVehicleLoaner
	case loading
	case viewGettoCustomer
	case yourAccount
	case unknown
	case popupHardRefreshMessage
	case viewArrivedatDeliveryInspectVehicles
	case popupAddNewLocationLabel
	case viewHelpOptionDetailCallDealer
	case errorLocationServiceUnavailable
	case returnToDealership
	case errorInvalidLastName
	case viewReceiveVehicleInfoReminder
	case viewArrivedatPickupSwipeButtonTitle
	case viewReceiveVehicleLoanerSwipeButtonTitle
	case errorAmbiguousVehicleUpsert
	case createPassword
	case requestCanceled
	case viewStartRequestRetrieveForms
	case viewExchangeKeysInfoReminder
	case number2
	case done
	case viewProfileChangeContact
	case viewDrawerContactDealershipCall
	case viewScheduleListItemTypePickup
	case viewRetrieveForms
	case viewDrawerNavigationPreferenceWaze
	case viewDrawerNavigationPreferenceTitle
	case passwordRequirements
	case popupSelectTimeSlotUnavailableCallDealership
	case viewProfileChangePasswordTemp
	case viewEmailBody
	case customerColon
	case errorPhoneNumberTaken
	case viewInspectLoanerOverlayInfo
	case viewTosContentTermsOfServiceUrl
	case viewInspectDocuments
	case viewSchedule
	case viewDrawerProfileOptionsChangePassword
	case popupGetToCustomerTitle
	case retry
	case viewTosContentTermsOfServiceTitle
	case popupPhoneVerificationResendCodeTitle
	case errorOops
	case errorPasswordNotMatch
	case viewDrawerProfileOptionsSignout
	case viewRecordLoanerMileageDropoffSwipeButtonTitle
	case viewInspectNotesDescriptionHint
	case popupTooFarFromCustomerMessage
	case viewDrawerNavigationPreferenceGoogle
	case errorInvalidEmail
	case yes
	case notificationForegroundServiceTextInspectNotes
	case errorSoftUpgradeTitle
	case errorLocationOutOfPickupArea
	case viewPhoneAdd
	case viewStartRequestDropoff
	case errorInvalidVerificationCode
	case number10
	case errorForcedUpgradeTitle
	case add
	case viewInspectCustomerOverlayInfo
	case openSettings
	case delivery
	case viewArrivedatCustomer
	case viewExchangeKeysPickupSwipeTitle
	case errorInvalidUserDisabled
	case change
	case no
	case errorLocationServiceNotOfferedInYourArea
	case model
	case popupForgotPasswordMessage
	case viewScheduleEmpty
	case permissionsLocationDeniedTitle
	case errorOffline
	case viewSigninEmailInvalid
	case popupGetToDealershipCopyToClipboard
	case notificationForegroundServiceTextReceiveLoaner
	case errorForcedUpgradeMessage
	case phoneNumber
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case viewRetrieveVehicle
	case support
	case viewRecordLoanerMileagePickupSwipeButtonTitle
	case serviceColon
	case popupSignoutConfirmationMessage
	case errorInvalidCredentials
	case keyCodeColon
	case number5
	case viewScheduleState
	case edit
	case viewRetrieveFormsInfoNext
	case update
	case close
	case signout
	case cancel
	case viewReturntoSwipeButtonTitle
	case popupTooFarFromDealershipTitle
	case currentPassword
	case viewEmailSubject
	case popupMileageMaxConfirmation
	case toastSettingsLocationDisabled
	case viewIntroFooterSignin
	case appName
	case requestTaskChangedFromBackend
	case confirmNewPassword
	case popupHardRefreshTitle
	case viewRetrieveVehicleCustomerSwipeTitle
	case mins
	case phoneNumberAlreadyTaken
	case errorInvalidFirstName
	case popupForgotPasswordTitle
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case notificationForegroundServiceTextDriverVehicleToCustomer
	case notificationForegroundServiceTextRetrieveForms
	case popupTooFarFromCustomerTitle
	case permissionsCameraDeniedMessage
	case viewGetToText
	case errorAmbiguousCustomerUpsert
	case viewScheduleServiceStatusSelfAdvisorPickup
	case contact
	case popupAlreadyStartedDrivingPositive
	case viewTosContentPrivacyPolicyUrl
	case viewInspectCustomerMinPhotoWarning
	case viewScheduleStateRefreshInfo
	case pickupColon
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case errorDatabase
	case viewReceiveVehicleLoaner
	case viewReceiveVehicleCustomer
	case popupDeviceChangeTitle
	case requestReset
	case volvoYearModel
	case popupChooseDealershipTitle
	case modelColon
	case number6
	case viewTosContent
	case dismiss
	case dealershipAddressColon
	case notificationBatteryWarningTextBig
	case errorAccountAlreadyExists
	case number7
	case notificationForegroundServiceTextDriverGetToCustomer

    var key : String {
        switch self {
            case .next:
					return "next"
			case .notAvailable:
					return "notAvailable"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .notNow:
					return "notNow"
			case .inspectVehicle:
					return "inspectVehicle"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .popupAlreadyStartedDrivingTitle:
					return "popupAlreadyStartedDrivingTitle"
			case .viewNavigateAddressCopiedToClipboard:
					return "viewNavigateAddressCopiedToClipboard"
			case .permissionsCameraDeniedTitle:
					return "permissionsCameraDeniedTitle"
			case .viewScheduleListHeaderNameCompletedToday:
					return "viewScheduleListHeaderNameCompletedToday"
			case .newPassword:
					return "newPassword"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .viewGettoCustomerArriveatCustomer:
					return "viewGettoCustomerArriveatCustomer"
			case .viewScheduleListItemTypeDeliver:
					return "viewScheduleListItemTypeDeliver"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .inspectVehicles:
					return "inspectVehicles"
			case .vehicleMake:
					return "vehicleMake"
			case .viewInspectLoanerMinPhotosWarning:
					return "viewInspectLoanerMinPhotosWarning"
			case .iAmSure:
					return "iAmSure"
			case .viewNavigateText:
					return "viewNavigateText"
			case .viewStartRequestSwipeButtonTitle:
					return "viewStartRequestSwipeButtonTitle"
			case .repairOrderColon:
					return "repairOrderColon"
			case .viewRetrieveFormsSwipeTitle:
					return "viewRetrieveFormsSwipeTitle"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .viewDrivetoSwipeButtonTitle:
					return "viewDrivetoSwipeButtonTitle"
			case .viewSignupPasswordRequireNumber:
					return "viewSignupPasswordRequireNumber"
			case .viewScheduleEmptyToday:
					return "viewScheduleEmptyToday"
			case .popupGetToDealershipTitle:
					return "popupGetToDealershipTitle"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .year:
					return "year"
			case .viewInspectLoanerMinPhotoWarning:
					return "viewInspectLoanerMinPhotoWarning"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .viewSignin:
					return "viewSignin"
			case .viewSigninPasswordShort:
					return "viewSigninPasswordShort"
			case .back:
					return "back"
			case .viewScheduleListHeaderNameCurrent:
					return "viewScheduleListHeaderNameCurrent"
			case .popupGetToCustomerCopyToClipboard:
					return "popupGetToCustomerCopyToClipboard"
			case .ok:
					return "ok"
			case .viewStartRequestRetrieveCustomerVehicle:
					return "viewStartRequestRetrieveCustomerVehicle"
			case .resendCode:
					return "resendCode"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .loanerColon:
					return "loanerColon"
			case .popupMileageMinConfirmation:
					return "popupMileageMinConfirmation"
			case .new:
					return "new"
			case .errorFaceDetectionMessage:
					return "errorFaceDetectionMessage"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .min:
					return "min"
			case .popupAlreadyStartedDrivingMessage:
					return "popupAlreadyStartedDrivingMessage"
			case .notificationForegroundServiceTextDriveCustomerToDealership:
					return "notificationForegroundServiceTextDriveCustomerToDealership"
			case .exchangeKeys:
					return "exchangeKeys"
			case .viewGettoCustomerSwipeButtonTitle:
					return "viewGettoCustomerSwipeButtonTitle"
			case .viewIntro:
					return "viewIntro"
			case .viewExchangeKeysDeliverySwipeTitle:
					return "viewExchangeKeysDeliverySwipeTitle"
			case .viewInspectNotesSwipeButtonTitle:
					return "viewInspectNotesSwipeButtonTitle"
			case .notificationForegroundServiceTextDriverInspectLoaner:
					return "notificationForegroundServiceTextDriverInspectLoaner"
			case .skip:
					return "skip"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .notificationForegroundServiceTextDriverLoanerToCustomer:
					return "notificationForegroundServiceTextDriverLoanerToCustomer"
			case .pickup:
					return "pickup"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .popupTooFarFromDealershipMessage:
					return "popupTooFarFromDealershipMessage"
			case .number9:
					return "number9"
			case .viewRetrieveVehicleCustomer:
					return "viewRetrieveVehicleCustomer"
			case .viewDriveto:
					return "viewDriveto"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .later:
					return "later"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .viewGettoDealershipSwipeButtonTitle:
					return "viewGettoDealershipSwipeButtonTitle"
			case .viewContactText:
					return "viewContactText"
			case .notificationForegroundServiceTextGetToDealership:
					return "notificationForegroundServiceTextGetToDealership"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .viewReceiveVehicle:
					return "viewReceiveVehicle"
			case .notificationForegroundServiceTitle:
					return "notificationForegroundServiceTitle"
			case .viewRetrieveVehicleLoanerSwipeTitle:
					return "viewRetrieveVehicleLoanerSwipeTitle"
			case .viewRecordLoanerMileageDropoffInfoNext:
					return "viewRecordLoanerMileageDropoffInfoNext"
			case .viewNavigateWazeText:
					return "viewNavigateWazeText"
			case .notificationForegroundServiceTextRetrieveVehicle:
					return "notificationForegroundServiceTextRetrieveVehicle"
			case .viewInspectDocumentsMinPhotosWarning:
					return "viewInspectDocumentsMinPhotosWarning"
			case .viewDrivetoCustomer:
					return "viewDrivetoCustomer"
			case .viewSwipeButtonInnerText:
					return "viewSwipeButtonInnerText"
			case .viewPhoneAddLabel:
					return "viewPhoneAddLabel"
			case .viewDrivetoArriveatCustomer:
					return "viewDrivetoArriveatCustomer"
			case .goBack:
					return "goBack"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .viewReceiveVehicleCustomerSwipeButtonTitle:
					return "viewReceiveVehicleCustomerSwipeButtonTitle"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .viewChecklistLoanerAgreementLabel:
					return "viewChecklistLoanerAgreementLabel"
			case .readMore:
					return "readMore"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .viewDrawerContactDealershipText:
					return "viewDrawerContactDealershipText"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .viewDrawerProfileOptionsAttributions:
					return "viewDrawerProfileOptionsAttributions"
			case .number8:
					return "number8"
			case .emailAddress:
					return "emailAddress"
			case .number1:
					return "number1"
			case .color:
					return "color"
			case .settings:
					return "settings"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .viewInspectDocumentsOverlayInfo:
					return "viewInspectDocumentsOverlayInfo"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .recentMileageColon:
					return "recentMileageColon"
			case .notificationForegroundServiceTextRecordLoanerMileage:
					return "notificationForegroundServiceTextRecordLoanerMileage"
			case .number11:
					return "number11"
			case .errorSynchingRequest:
					return "errorSynchingRequest"
			case .viewArrivedat:
					return "viewArrivedat"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .viewInspectCustomer:
					return "viewInspectCustomer"
			case .deliveryColon:
					return "deliveryColon"
			case .updateNow:
					return "updateNow"
			case .viewStartRequestPickup:
					return "viewStartRequestPickup"
			case .addressColon:
					return "addressColon"
			case .viewSigninActionSignin:
					return "viewSigninActionSignin"
			case .licensePlateColon:
					return "licensePlateColon"
			case .popupTooFarFromCustomerPositive:
					return "popupTooFarFromCustomerPositive"
			case .viewInspectCustomerMinPhotosWarning:
					return "viewInspectCustomerMinPhotosWarning"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .viewSigninPhoto:
					return "viewSigninPhoto"
			case .popupDeviceChangeMessage:
					return "popupDeviceChangeMessage"
			case .password:
					return "password"
			case .notificationForegroundServiceTextDriverExchangeKeys:
					return "notificationForegroundServiceTextDriverExchangeKeys"
			case .notificationBatteryWarningTitle:
					return "notificationBatteryWarningTitle"
			case .viewContactCall:
					return "viewContactCall"
			case .notificationForegroundServiceTextDriverInspectCustomer:
					return "notificationForegroundServiceTextDriverInspectCustomer"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .remove:
					return "remove"
			case .notificationForegroundServiceTextRetrieveLoaner:
					return "notificationForegroundServiceTextRetrieveLoaner"
			case .viewDrawerProfileOptionsChangeContact:
					return "viewDrawerProfileOptionsChangeContact"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .errorUnknown:
					return "errorUnknown"
			case .viewRecordLoanerMileage:
					return "viewRecordLoanerMileage"
			case .viewSigninPopupProgressSignin:
					return "viewSigninPopupProgressSignin"
			case .viewScheduleStateRefreshButton:
					return "viewScheduleStateRefreshButton"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .requestCompleted:
					return "requestCompleted"
			case .notificationForegroundServiceTextDriveLoanerToDealership:
					return "notificationForegroundServiceTextDriveLoanerToDealership"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
			case .viewSignupPasswordRequireLetter:
					return "viewSignupPasswordRequireLetter"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .popupTooFarFromDealershipPositive:
					return "popupTooFarFromDealershipPositive"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .viewStartRequestRetrieveLoaner:
					return "viewStartRequestRetrieveLoaner"
			case .help:
					return "help"
			case .exchangeKey:
					return "exchangeKey"
			case .notesColon:
					return "notesColon"
			case .viewInspectNotes:
					return "viewInspectNotes"
			case .viewScheduleListHeaderNameUpcomingToday:
					return "viewScheduleListHeaderNameUpcomingToday"
			case .viewArrivedatDeliverySwipeButtonTitle:
					return "viewArrivedatDeliverySwipeButtonTitle"
			case .viewInspectDocumentsMinPhotoWarning:
					return "viewInspectDocumentsMinPhotoWarning"
			case .error:
					return "error"
			case .notificationForegroundServiceTextDriverInspectDocuments:
					return "notificationForegroundServiceTextDriverInspectDocuments"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .dealership:
					return "dealership"
			case .notificationBatteryWarningText:
					return "notificationBatteryWarningText"
			case .confirmationCode:
					return "confirmationCode"
			case .errorInvalidCharacter:
					return "errorInvalidCharacter"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .viewScheduleCurrent:
					return "viewScheduleCurrent"
			case .viewInspectLoaner:
					return "viewInspectLoaner"
			case .viewExchangeKeysSwipeButtonTitle:
					return "viewExchangeKeysSwipeButtonTitle"
			case .errorEnterLoanerMileage:
					return "errorEnterLoanerMileage"
			case .notificationForegroundServiceTextDriverMeetWithCustomer:
					return "notificationForegroundServiceTextDriverMeetWithCustomer"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .errorOnline:
					return "errorOnline"
			case .number4:
					return "number4"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .viewReceiveVehicleLoanerNext:
					return "viewReceiveVehicleLoanerNext"
			case .viewRetrieveVehicleCustomerInfoNext:
					return "viewRetrieveVehicleCustomerInfoNext"
			case .number3:
					return "number3"
			case .notificationActionOpen:
					return "notificationActionOpen"
			case .viewRetrieveVehicleLoaner:
					return "viewRetrieveVehicleLoaner"
			case .loading:
					return "loading"
			case .viewGettoCustomer:
					return "viewGettoCustomer"
			case .yourAccount:
					return "yourAccount"
			case .unknown:
					return "unknown"
			case .popupHardRefreshMessage:
					return "popupHardRefreshMessage"
			case .viewArrivedatDeliveryInspectVehicles:
					return "viewArrivedatDeliveryInspectVehicles"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .returnToDealership:
					return "returnToDealership"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .viewReceiveVehicleInfoReminder:
					return "viewReceiveVehicleInfoReminder"
			case .viewArrivedatPickupSwipeButtonTitle:
					return "viewArrivedatPickupSwipeButtonTitle"
			case .viewReceiveVehicleLoanerSwipeButtonTitle:
					return "viewReceiveVehicleLoanerSwipeButtonTitle"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .createPassword:
					return "createPassword"
			case .requestCanceled:
					return "requestCanceled"
			case .viewStartRequestRetrieveForms:
					return "viewStartRequestRetrieveForms"
			case .viewExchangeKeysInfoReminder:
					return "viewExchangeKeysInfoReminder"
			case .number2:
					return "number2"
			case .done:
					return "done"
			case .viewProfileChangeContact:
					return "viewProfileChangeContact"
			case .viewDrawerContactDealershipCall:
					return "viewDrawerContactDealershipCall"
			case .viewScheduleListItemTypePickup:
					return "viewScheduleListItemTypePickup"
			case .viewRetrieveForms:
					return "viewRetrieveForms"
			case .viewDrawerNavigationPreferenceWaze:
					return "viewDrawerNavigationPreferenceWaze"
			case .viewDrawerNavigationPreferenceTitle:
					return "viewDrawerNavigationPreferenceTitle"
			case .passwordRequirements:
					return "passwordRequirements"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .viewProfileChangePasswordTemp:
					return "viewProfileChangePasswordTemp"
			case .viewEmailBody:
					return "viewEmailBody"
			case .customerColon:
					return "customerColon"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .viewInspectLoanerOverlayInfo:
					return "viewInspectLoanerOverlayInfo"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .viewInspectDocuments:
					return "viewInspectDocuments"
			case .viewSchedule:
					return "viewSchedule"
			case .viewDrawerProfileOptionsChangePassword:
					return "viewDrawerProfileOptionsChangePassword"
			case .popupGetToCustomerTitle:
					return "popupGetToCustomerTitle"
			case .retry:
					return "retry"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
			case .errorOops:
					return "errorOops"
			case .errorPasswordNotMatch:
					return "errorPasswordNotMatch"
			case .viewDrawerProfileOptionsSignout:
					return "viewDrawerProfileOptionsSignout"
			case .viewRecordLoanerMileageDropoffSwipeButtonTitle:
					return "viewRecordLoanerMileageDropoffSwipeButtonTitle"
			case .viewInspectNotesDescriptionHint:
					return "viewInspectNotesDescriptionHint"
			case .popupTooFarFromCustomerMessage:
					return "popupTooFarFromCustomerMessage"
			case .viewDrawerNavigationPreferenceGoogle:
					return "viewDrawerNavigationPreferenceGoogle"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .yes:
					return "yes"
			case .notificationForegroundServiceTextInspectNotes:
					return "notificationForegroundServiceTextInspectNotes"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .viewPhoneAdd:
					return "viewPhoneAdd"
			case .viewStartRequestDropoff:
					return "viewStartRequestDropoff"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .number10:
					return "number10"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .add:
					return "add"
			case .viewInspectCustomerOverlayInfo:
					return "viewInspectCustomerOverlayInfo"
			case .openSettings:
					return "openSettings"
			case .delivery:
					return "delivery"
			case .viewArrivedatCustomer:
					return "viewArrivedatCustomer"
			case .viewExchangeKeysPickupSwipeTitle:
					return "viewExchangeKeysPickupSwipeTitle"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .change:
					return "change"
			case .no:
					return "no"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .model:
					return "model"
			case .popupForgotPasswordMessage:
					return "popupForgotPasswordMessage"
			case .viewScheduleEmpty:
					return "viewScheduleEmpty"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .errorOffline:
					return "errorOffline"
			case .viewSigninEmailInvalid:
					return "viewSigninEmailInvalid"
			case .popupGetToDealershipCopyToClipboard:
					return "popupGetToDealershipCopyToClipboard"
			case .notificationForegroundServiceTextReceiveLoaner:
					return "notificationForegroundServiceTextReceiveLoaner"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .phoneNumber:
					return "phoneNumber"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .viewRetrieveVehicle:
					return "viewRetrieveVehicle"
			case .support:
					return "support"
			case .viewRecordLoanerMileagePickupSwipeButtonTitle:
					return "viewRecordLoanerMileagePickupSwipeButtonTitle"
			case .serviceColon:
					return "serviceColon"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .keyCodeColon:
					return "keyCodeColon"
			case .number5:
					return "number5"
			case .viewScheduleState:
					return "viewScheduleState"
			case .edit:
					return "edit"
			case .viewRetrieveFormsInfoNext:
					return "viewRetrieveFormsInfoNext"
			case .update:
					return "update"
			case .close:
					return "close"
			case .signout:
					return "signout"
			case .cancel:
					return "cancel"
			case .viewReturntoSwipeButtonTitle:
					return "viewReturntoSwipeButtonTitle"
			case .popupTooFarFromDealershipTitle:
					return "popupTooFarFromDealershipTitle"
			case .currentPassword:
					return "currentPassword"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .popupMileageMaxConfirmation:
					return "popupMileageMaxConfirmation"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .appName:
					return "appName"
			case .requestTaskChangedFromBackend:
					return "requestTaskChangedFromBackend"
			case .confirmNewPassword:
					return "confirmNewPassword"
			case .popupHardRefreshTitle:
					return "popupHardRefreshTitle"
			case .viewRetrieveVehicleCustomerSwipeTitle:
					return "viewRetrieveVehicleCustomerSwipeTitle"
			case .mins:
					return "mins"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .popupForgotPasswordTitle:
					return "popupForgotPasswordTitle"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .notificationForegroundServiceTextDriverVehicleToCustomer:
					return "notificationForegroundServiceTextDriverVehicleToCustomer"
			case .notificationForegroundServiceTextRetrieveForms:
					return "notificationForegroundServiceTextRetrieveForms"
			case .popupTooFarFromCustomerTitle:
					return "popupTooFarFromCustomerTitle"
			case .permissionsCameraDeniedMessage:
					return "permissionsCameraDeniedMessage"
			case .viewGetToText:
					return "viewGetToText"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .contact:
					return "contact"
			case .popupAlreadyStartedDrivingPositive:
					return "popupAlreadyStartedDrivingPositive"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .viewInspectCustomerMinPhotoWarning:
					return "viewInspectCustomerMinPhotoWarning"
			case .viewScheduleStateRefreshInfo:
					return "viewScheduleStateRefreshInfo"
			case .pickupColon:
					return "pickupColon"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .errorDatabase:
					return "errorDatabase"
			case .viewReceiveVehicleLoaner:
					return "viewReceiveVehicleLoaner"
			case .viewReceiveVehicleCustomer:
					return "viewReceiveVehicleCustomer"
			case .popupDeviceChangeTitle:
					return "popupDeviceChangeTitle"
			case .requestReset:
					return "requestReset"
			case .volvoYearModel:
					return "volvoYearModel"
			case .popupChooseDealershipTitle:
					return "popupChooseDealershipTitle"
			case .modelColon:
					return "modelColon"
			case .number6:
					return "number6"
			case .viewTosContent:
					return "viewTosContent"
			case .dismiss:
					return "dismiss"
			case .dealershipAddressColon:
					return "dealershipAddressColon"
			case .notificationBatteryWarningTextBig:
					return "notificationBatteryWarningTextBig"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .number7:
					return "number7"
			case .notificationForegroundServiceTextDriverGetToCustomer:
					return "notificationForegroundServiceTextDriverGetToCustomer"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
