//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Localized.loadError
 Localized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case viewArrivedatCustomer
	case number6
	case notificationForegroundServiceTextDriverExchangeKeys
	case later
	case viewProfileChangeContact
	case popupGetToCustomerTitle
	case number4
	case errorLocationOutOfDropoffArea
	case notificationForegroundServiceTextDriverGetToCustomer
	case viewArrivedatPickupSwipeButtonTitle
	case popupHardRefreshMessage
	case popupUpdatingLocation
	case viewInspectLoaner
	case viewExchangeKeysDeliverySwipeTitle
	case errorInvalidEmail
	case notificationForegroundServiceTextGetToDealership
	case goBack
	case viewScheduleListHeaderNameUpcomingToday
	case popupAddNewLocationLabel
	case popupForgotPasswordTitle
	case emailAddress
	case viewProfileChangePasswordTemp
	case yes
	case remove
	case viewRetrieveVehicleLoanerSwipeTitle
	case notificationForegroundServiceTextDriveCustomerToDealership
	case viewGettoDealershipSwipeButtonTitle
	case errorSoftUpgradeMessage
	case helpIForgotMyPassword
	case number11
	case errorVerifyPhoneNumber
	case exchangeKeys
	case modelColon
	case customerColon
	case dealershipAddressColon
	case viewRecordLoanerMileagePickupSwipeButtonTitle
	case popupDeviceChangeTitle
	case viewDrawerNavigationPreferenceGoogle
	case popupGetToCustomerCopyToClipboard
	case viewEmailSubject
	case currentPassword
	case viewScheduleServiceStatusSelfDealershipNavigate
	case viewHelpOptionDetailEmailDealer
	case viewContactText
	case viewTosContentTermsOfServiceUrl
	case viewSignin
	case viewRetrieveVehicle
	case requestReset
	case popupSignoutConfirmationMessage
	case popupAlreadyStartedDrivingPositive
	case errorRequestNotCancelable
	case notificationActionOpen
	case errorInvalidPasswordConfirm
	case viewRetrieveVehicleCustomerInfoNext
	case popupHardRefreshTitle
	case signout
	case mins
	case phoneNumber
	case popupSelectTimeSlotUnavailableCallDealership
	case viewScheduleListItemTypeDeliver
	case errorSynchingRequest
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case unknown
	case vehicleMake
	case viewReceiveVehicleLoanerSwipeButtonTitle
	case viewInspectCustomer
	case confirmPhoneNumber
	case inspectVehicle
	case requestCompleted
	case viewTosContentPrivacyPolicyUrl
	case viewGettoCustomerSwipeButtonTitle
	case contact
	case viewSoftwareLicences
	case errorIllegalRequestTaskChange
	case change
	case number1
	case number9
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case viewNavigateText
	case viewArrivedat
	case viewScheduleServiceStatusSelfAdvisorPickup
	case notificationForegroundServiceTextInspectNotes
	case viewInspectLoanerMinPhotoWarning
	case errorInvalidPasswordUnauthorizedCharacters
	case appName
	case viewChecklistLoanerAgreementLabel
	case close
	case errorDuplicateLoanerVehicleBookingAssignment
	case popupTooFarFromDealershipTitle
	case color
	case popupAlreadyStartedDrivingTitle
	case viewGetToText
	case errorInvalidLastName
	case viewSigninActionSignin
	case viewScheduleListHeaderNameCurrent
	case notNow
	case notificationForegroundServiceTextRetrieveLoaner
	case viewDrivetoCustomer
	case viewRetrieveFormsInfoNext
	case recentMileageColon
	case loanerColon
	case errorPhoneNumberTaken
	case notificationForegroundServiceTextDriverVehicleToCustomer
	case errorOops
	case add
	case returnToDealership
	case viewDrawerProfileOptionsChangePassword
	case viewSigninPopupProgressSignin
	case viewReceiveVehicleCustomer
	case viewHelpOptionDetailEmailVolvo
	case requestCanceled
	case resendCode
	case number5
	case errorLocationOutOfPickupArea
	case popupGetToDealershipCopyToClipboard
	case popupSoftUpgradeNegative
	case viewLogoTitle
	case viewScheduleListHeaderNameCompletedToday
	case errorInvalidFirstName
	case notificationBatteryWarningTitle
	case viewScheduleCurrent
	case popupAlreadyStartedDrivingMessage
	case dismiss
	case notificationForegroundServiceTextReceiveLoaner
	case viewRecordLoanerMileageDropoffSwipeButtonTitle
	case viewSignupPasswordRequireLetter
	case openSettings
	case viewExchangeKeysInfoReminder
	case no
	case cancel
	case ok
	case min
	case viewIntroFooterSignup
	case notificationForegroundServiceTextRetrieveVehicle
	case viewTosContentTermsOfServiceTitle
	case edit
	case viewReturntoSwipeButtonTitle
	case notificationForegroundServiceTextDriverInspectCustomer
	case number3
	case viewScheduleServiceTypeOtherUnknown
	case viewGettoCustomer
	case viewIntro
	case confirmNewPassword
	case yourAccount
	case year
	case settings
	case errorAccountAlreadyExists
	case dealership
	case viewDrawerNavigationPreferenceWaze
	case viewInspectNotesSwipeButtonTitle
	case viewDrawerContactDealershipText
	case viewTosContent
	case viewEmailIntentChooserTitle
	case popupChooseDealershipTitle
	case viewInspectNotes
	case viewSwipeButtonInnerText
	case popupMileageMinConfirmation
	case notificationForegroundServiceTextDriverInspectLoaner
	case errorInvalidPhoneVerificationCode
	case popupDeviceChangeMessage
	case viewInspectLoanerOverlayInfo
	case pickup
	case viewRetrieveVehicleLoaner
	case notesColon
	case number10
	case licensePlateColon
	case password
	case viewStartRequestRetrieveLoaner
	case serviceColon
	case viewInspectDocumentsMinPhotoWarning
	case errorInvalidCredentials
	case viewRetrieveFormsSwipeTitle
	case errorForcedUpgradeTitle
	case support
	case errorForcedUpgradeMessage
	case errorFaceDetectionMessage
	case helpICantUpdateMyPhone
	case iAmSure
	case viewEmailBody
	case retry
	case exchangeKey
	case new
	case viewSignupPasswordRequireNumber
	case permissionsLocationDeniedMessage
	case toastSettingsLocationDisabled
	case errorIllegalRequestStateChange
	case phoneNumberCannotBeEmpty
	case viewReceiveVehicleCustomerSwipeButtonTitle
	case viewPhoneAdd
	case back
	case viewGettoCustomerArriveatCustomer
	case keyCodeColon
	case notificationForegroundServiceTextDriveLoanerToDealership
	case viewTosContentTermsOfService
	case viewArrivedatDeliveryInspectVehicles
	case errorDatabase
	case viewSigninPasswordShort
	case viewIntroFooterSignin
	case viewStartRequestSwipeButtonTitle
	case viewInspectCustomerMinPhotosWarning
	case notificationForegroundServiceTextRecordLoanerMileage
	case viewReceiveVehicleInfoReminder
	case viewInspectDocumentsOverlayInfo
	case viewHelpOptionDetailCallVolvo
	case viewHelpCategoryLastLeg
	case notificationForegroundServiceTextRetrieveForms
	case viewInspectNotesDescriptionHint
	case requestTaskChangedFromBackend
	case errorAmbiguousCustomerUpsert
	case repairOrderColon
	case errorLocationServiceUnavailable
	case viewScheduleListItemTypePickup
	case updateNow
	case viewDrawerContactDealershipCall
	case viewPhoneAddLabel
	case viewDrawerProfileOptionsSignout
	case errorPasswordNotMatch
	case permissionsLocationDeniedTitle
	case popupTooFarFromCustomerTitle
	case error
	case popupTooFarFromCustomerPositive
	case errorInvalidCharacter
	case volvoYearModel
	case permissionsCameraDeniedMessage
	case errorInvalidUserDisabled
	case errorUnknown
	case viewDrawerProfileOptionsAttributions
	case createPassword
	case viewTosContentPrivacyPolicy
	case viewSigninForgotPassword
	case viewContactCall
	case errorLocationServiceNotOfferedInYourArea
	case viewRetrieveVehicleCustomer
	case viewRecordLoanerMileageDropoffInfoNext
	case errorInvalidPhoneNumber
	case popupTooFarFromCustomerMessage
	case viewStartRequestDropoff
	case confirmationCode
	case viewNavigateAddressCopiedToClipboard
	case viewHelpOptionDetailCallDealer
	case viewSigninEmailInvalid
	case notificationForegroundServiceTextDriverLoanerToCustomer
	case model
	case notAvailable
	case viewScheduleEmpty
	case permissionsCameraDeniedTitle
	case number8
	case viewInspectDocuments
	case popupTooFarFromDealershipMessage
	case errorOffline
	case viewReceiveVehicle
	case viewArrivedatDeliverySwipeButtonTitle
	case viewScheduleStateRefreshInfo
	case errorEnterLoanerMileage
	case notificationBatteryWarningTextBig
	case viewReceiveVehicleLoanerNext
	case newPassword
	case skip
	case delivery
	case viewStartRequestRetrieveForms
	case viewStartRequestPickup
	case viewStartRequestRetrieveCustomerVehicle
	case errorOnline
	case viewScheduleStateRefreshButton
	case addressColon
	case next
	case errorInvalidApplicationVersion
	case errorAmbiguousVehicleUpsert
	case popupForgotPasswordMessage
	case viewExchangeKeysSwipeButtonTitle
	case notificationBatteryWarningText
	case viewInspectDocumentsMinPhotosWarning
	case viewDriveto
	case notificationForegroundServiceTextDriverMeetWithCustomer
	case viewTosContentPrivacyPolicyTitle
	case viewNavigateWazeText
	case loading
	case viewRetrieveVehicleCustomerSwipeTitle
	case viewInspectCustomerOverlayInfo
	case notificationForegroundServiceTextDriverInspectDocuments
	case viewHelpCategoryHowLuxeByVolvoWorks
	case errorUserDisabled
	case errorInvalidPassword
	case viewRecordLoanerMileage
	case viewInspectLoanerMinPhotosWarning
	case viewSchedule
	case popupMileageMaxConfirmation
	case deliveryColon
	case done
	case pickupColon
	case errorInvalidVerificationCode
	case viewPhoneVerificationLabel
	case popupPhoneVerificationResendCodeMessage
	case viewExchangeKeysPickupSwipeTitle
	case viewDrawerNavigationPreferenceTitle
	case popupTooFarFromDealershipPositive
	case viewDrivetoSwipeButtonTitle
	case viewRetrieveForms
	case help
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case notificationForegroundServiceTitle
	case phoneNumberAlreadyTaken
	case viewInspectCustomerMinPhotoWarning
	case number7
	case readMore
	case popupGetToDealershipTitle
	case update
	case errorSoftUpgradeTitle
	case viewSigninPhoto
	case inspectVehicles
	case number2
	case viewScheduleEmptyToday
	case viewDrawerProfileOptionsChangeContact
	case viewReceiveVehicleLoaner
	case viewDrivetoArriveatCustomer
	case passwordRequirements
	case viewScheduleState
	case errorRemoveVehicleError
	case popupPhoneVerificationResendCodeTitle

    var key : String {
        switch self {
            case .viewArrivedatCustomer:
					return "viewArrivedatCustomer"
			case .number6:
					return "number6"
			case .notificationForegroundServiceTextDriverExchangeKeys:
					return "notificationForegroundServiceTextDriverExchangeKeys"
			case .later:
					return "later"
			case .viewProfileChangeContact:
					return "viewProfileChangeContact"
			case .popupGetToCustomerTitle:
					return "popupGetToCustomerTitle"
			case .number4:
					return "number4"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .notificationForegroundServiceTextDriverGetToCustomer:
					return "notificationForegroundServiceTextDriverGetToCustomer"
			case .viewArrivedatPickupSwipeButtonTitle:
					return "viewArrivedatPickupSwipeButtonTitle"
			case .popupHardRefreshMessage:
					return "popupHardRefreshMessage"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .viewInspectLoaner:
					return "viewInspectLoaner"
			case .viewExchangeKeysDeliverySwipeTitle:
					return "viewExchangeKeysDeliverySwipeTitle"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .notificationForegroundServiceTextGetToDealership:
					return "notificationForegroundServiceTextGetToDealership"
			case .goBack:
					return "goBack"
			case .viewScheduleListHeaderNameUpcomingToday:
					return "viewScheduleListHeaderNameUpcomingToday"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .popupForgotPasswordTitle:
					return "popupForgotPasswordTitle"
			case .emailAddress:
					return "emailAddress"
			case .viewProfileChangePasswordTemp:
					return "viewProfileChangePasswordTemp"
			case .yes:
					return "yes"
			case .remove:
					return "remove"
			case .viewRetrieveVehicleLoanerSwipeTitle:
					return "viewRetrieveVehicleLoanerSwipeTitle"
			case .notificationForegroundServiceTextDriveCustomerToDealership:
					return "notificationForegroundServiceTextDriveCustomerToDealership"
			case .viewGettoDealershipSwipeButtonTitle:
					return "viewGettoDealershipSwipeButtonTitle"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .number11:
					return "number11"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .exchangeKeys:
					return "exchangeKeys"
			case .modelColon:
					return "modelColon"
			case .customerColon:
					return "customerColon"
			case .dealershipAddressColon:
					return "dealershipAddressColon"
			case .viewRecordLoanerMileagePickupSwipeButtonTitle:
					return "viewRecordLoanerMileagePickupSwipeButtonTitle"
			case .popupDeviceChangeTitle:
					return "popupDeviceChangeTitle"
			case .viewDrawerNavigationPreferenceGoogle:
					return "viewDrawerNavigationPreferenceGoogle"
			case .popupGetToCustomerCopyToClipboard:
					return "popupGetToCustomerCopyToClipboard"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .currentPassword:
					return "currentPassword"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .viewContactText:
					return "viewContactText"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .viewSignin:
					return "viewSignin"
			case .viewRetrieveVehicle:
					return "viewRetrieveVehicle"
			case .requestReset:
					return "requestReset"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .popupAlreadyStartedDrivingPositive:
					return "popupAlreadyStartedDrivingPositive"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .notificationActionOpen:
					return "notificationActionOpen"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .viewRetrieveVehicleCustomerInfoNext:
					return "viewRetrieveVehicleCustomerInfoNext"
			case .popupHardRefreshTitle:
					return "popupHardRefreshTitle"
			case .signout:
					return "signout"
			case .mins:
					return "mins"
			case .phoneNumber:
					return "phoneNumber"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .viewScheduleListItemTypeDeliver:
					return "viewScheduleListItemTypeDeliver"
			case .errorSynchingRequest:
					return "errorSynchingRequest"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .unknown:
					return "unknown"
			case .vehicleMake:
					return "vehicleMake"
			case .viewReceiveVehicleLoanerSwipeButtonTitle:
					return "viewReceiveVehicleLoanerSwipeButtonTitle"
			case .viewInspectCustomer:
					return "viewInspectCustomer"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .inspectVehicle:
					return "inspectVehicle"
			case .requestCompleted:
					return "requestCompleted"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .viewGettoCustomerSwipeButtonTitle:
					return "viewGettoCustomerSwipeButtonTitle"
			case .contact:
					return "contact"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .change:
					return "change"
			case .number1:
					return "number1"
			case .number9:
					return "number9"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .viewNavigateText:
					return "viewNavigateText"
			case .viewArrivedat:
					return "viewArrivedat"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .notificationForegroundServiceTextInspectNotes:
					return "notificationForegroundServiceTextInspectNotes"
			case .viewInspectLoanerMinPhotoWarning:
					return "viewInspectLoanerMinPhotoWarning"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .appName:
					return "appName"
			case .viewChecklistLoanerAgreementLabel:
					return "viewChecklistLoanerAgreementLabel"
			case .close:
					return "close"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
			case .popupTooFarFromDealershipTitle:
					return "popupTooFarFromDealershipTitle"
			case .color:
					return "color"
			case .popupAlreadyStartedDrivingTitle:
					return "popupAlreadyStartedDrivingTitle"
			case .viewGetToText:
					return "viewGetToText"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .viewSigninActionSignin:
					return "viewSigninActionSignin"
			case .viewScheduleListHeaderNameCurrent:
					return "viewScheduleListHeaderNameCurrent"
			case .notNow:
					return "notNow"
			case .notificationForegroundServiceTextRetrieveLoaner:
					return "notificationForegroundServiceTextRetrieveLoaner"
			case .viewDrivetoCustomer:
					return "viewDrivetoCustomer"
			case .viewRetrieveFormsInfoNext:
					return "viewRetrieveFormsInfoNext"
			case .recentMileageColon:
					return "recentMileageColon"
			case .loanerColon:
					return "loanerColon"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .notificationForegroundServiceTextDriverVehicleToCustomer:
					return "notificationForegroundServiceTextDriverVehicleToCustomer"
			case .errorOops:
					return "errorOops"
			case .add:
					return "add"
			case .returnToDealership:
					return "returnToDealership"
			case .viewDrawerProfileOptionsChangePassword:
					return "viewDrawerProfileOptionsChangePassword"
			case .viewSigninPopupProgressSignin:
					return "viewSigninPopupProgressSignin"
			case .viewReceiveVehicleCustomer:
					return "viewReceiveVehicleCustomer"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .requestCanceled:
					return "requestCanceled"
			case .resendCode:
					return "resendCode"
			case .number5:
					return "number5"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .popupGetToDealershipCopyToClipboard:
					return "popupGetToDealershipCopyToClipboard"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .viewScheduleListHeaderNameCompletedToday:
					return "viewScheduleListHeaderNameCompletedToday"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .notificationBatteryWarningTitle:
					return "notificationBatteryWarningTitle"
			case .viewScheduleCurrent:
					return "viewScheduleCurrent"
			case .popupAlreadyStartedDrivingMessage:
					return "popupAlreadyStartedDrivingMessage"
			case .dismiss:
					return "dismiss"
			case .notificationForegroundServiceTextReceiveLoaner:
					return "notificationForegroundServiceTextReceiveLoaner"
			case .viewRecordLoanerMileageDropoffSwipeButtonTitle:
					return "viewRecordLoanerMileageDropoffSwipeButtonTitle"
			case .viewSignupPasswordRequireLetter:
					return "viewSignupPasswordRequireLetter"
			case .openSettings:
					return "openSettings"
			case .viewExchangeKeysInfoReminder:
					return "viewExchangeKeysInfoReminder"
			case .no:
					return "no"
			case .cancel:
					return "cancel"
			case .ok:
					return "ok"
			case .min:
					return "min"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .notificationForegroundServiceTextRetrieveVehicle:
					return "notificationForegroundServiceTextRetrieveVehicle"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .edit:
					return "edit"
			case .viewReturntoSwipeButtonTitle:
					return "viewReturntoSwipeButtonTitle"
			case .notificationForegroundServiceTextDriverInspectCustomer:
					return "notificationForegroundServiceTextDriverInspectCustomer"
			case .number3:
					return "number3"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .viewGettoCustomer:
					return "viewGettoCustomer"
			case .viewIntro:
					return "viewIntro"
			case .confirmNewPassword:
					return "confirmNewPassword"
			case .yourAccount:
					return "yourAccount"
			case .year:
					return "year"
			case .settings:
					return "settings"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .dealership:
					return "dealership"
			case .viewDrawerNavigationPreferenceWaze:
					return "viewDrawerNavigationPreferenceWaze"
			case .viewInspectNotesSwipeButtonTitle:
					return "viewInspectNotesSwipeButtonTitle"
			case .viewDrawerContactDealershipText:
					return "viewDrawerContactDealershipText"
			case .viewTosContent:
					return "viewTosContent"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .popupChooseDealershipTitle:
					return "popupChooseDealershipTitle"
			case .viewInspectNotes:
					return "viewInspectNotes"
			case .viewSwipeButtonInnerText:
					return "viewSwipeButtonInnerText"
			case .popupMileageMinConfirmation:
					return "popupMileageMinConfirmation"
			case .notificationForegroundServiceTextDriverInspectLoaner:
					return "notificationForegroundServiceTextDriverInspectLoaner"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .popupDeviceChangeMessage:
					return "popupDeviceChangeMessage"
			case .viewInspectLoanerOverlayInfo:
					return "viewInspectLoanerOverlayInfo"
			case .pickup:
					return "pickup"
			case .viewRetrieveVehicleLoaner:
					return "viewRetrieveVehicleLoaner"
			case .notesColon:
					return "notesColon"
			case .number10:
					return "number10"
			case .licensePlateColon:
					return "licensePlateColon"
			case .password:
					return "password"
			case .viewStartRequestRetrieveLoaner:
					return "viewStartRequestRetrieveLoaner"
			case .serviceColon:
					return "serviceColon"
			case .viewInspectDocumentsMinPhotoWarning:
					return "viewInspectDocumentsMinPhotoWarning"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .viewRetrieveFormsSwipeTitle:
					return "viewRetrieveFormsSwipeTitle"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .support:
					return "support"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .errorFaceDetectionMessage:
					return "errorFaceDetectionMessage"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .iAmSure:
					return "iAmSure"
			case .viewEmailBody:
					return "viewEmailBody"
			case .retry:
					return "retry"
			case .exchangeKey:
					return "exchangeKey"
			case .new:
					return "new"
			case .viewSignupPasswordRequireNumber:
					return "viewSignupPasswordRequireNumber"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .viewReceiveVehicleCustomerSwipeButtonTitle:
					return "viewReceiveVehicleCustomerSwipeButtonTitle"
			case .viewPhoneAdd:
					return "viewPhoneAdd"
			case .back:
					return "back"
			case .viewGettoCustomerArriveatCustomer:
					return "viewGettoCustomerArriveatCustomer"
			case .keyCodeColon:
					return "keyCodeColon"
			case .notificationForegroundServiceTextDriveLoanerToDealership:
					return "notificationForegroundServiceTextDriveLoanerToDealership"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .viewArrivedatDeliveryInspectVehicles:
					return "viewArrivedatDeliveryInspectVehicles"
			case .errorDatabase:
					return "errorDatabase"
			case .viewSigninPasswordShort:
					return "viewSigninPasswordShort"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .viewStartRequestSwipeButtonTitle:
					return "viewStartRequestSwipeButtonTitle"
			case .viewInspectCustomerMinPhotosWarning:
					return "viewInspectCustomerMinPhotosWarning"
			case .notificationForegroundServiceTextRecordLoanerMileage:
					return "notificationForegroundServiceTextRecordLoanerMileage"
			case .viewReceiveVehicleInfoReminder:
					return "viewReceiveVehicleInfoReminder"
			case .viewInspectDocumentsOverlayInfo:
					return "viewInspectDocumentsOverlayInfo"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .notificationForegroundServiceTextRetrieveForms:
					return "notificationForegroundServiceTextRetrieveForms"
			case .viewInspectNotesDescriptionHint:
					return "viewInspectNotesDescriptionHint"
			case .requestTaskChangedFromBackend:
					return "requestTaskChangedFromBackend"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .repairOrderColon:
					return "repairOrderColon"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .viewScheduleListItemTypePickup:
					return "viewScheduleListItemTypePickup"
			case .updateNow:
					return "updateNow"
			case .viewDrawerContactDealershipCall:
					return "viewDrawerContactDealershipCall"
			case .viewPhoneAddLabel:
					return "viewPhoneAddLabel"
			case .viewDrawerProfileOptionsSignout:
					return "viewDrawerProfileOptionsSignout"
			case .errorPasswordNotMatch:
					return "errorPasswordNotMatch"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .popupTooFarFromCustomerTitle:
					return "popupTooFarFromCustomerTitle"
			case .error:
					return "error"
			case .popupTooFarFromCustomerPositive:
					return "popupTooFarFromCustomerPositive"
			case .errorInvalidCharacter:
					return "errorInvalidCharacter"
			case .volvoYearModel:
					return "volvoYearModel"
			case .permissionsCameraDeniedMessage:
					return "permissionsCameraDeniedMessage"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .errorUnknown:
					return "errorUnknown"
			case .viewDrawerProfileOptionsAttributions:
					return "viewDrawerProfileOptionsAttributions"
			case .createPassword:
					return "createPassword"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .viewContactCall:
					return "viewContactCall"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .viewRetrieveVehicleCustomer:
					return "viewRetrieveVehicleCustomer"
			case .viewRecordLoanerMileageDropoffInfoNext:
					return "viewRecordLoanerMileageDropoffInfoNext"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .popupTooFarFromCustomerMessage:
					return "popupTooFarFromCustomerMessage"
			case .viewStartRequestDropoff:
					return "viewStartRequestDropoff"
			case .confirmationCode:
					return "confirmationCode"
			case .viewNavigateAddressCopiedToClipboard:
					return "viewNavigateAddressCopiedToClipboard"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .viewSigninEmailInvalid:
					return "viewSigninEmailInvalid"
			case .notificationForegroundServiceTextDriverLoanerToCustomer:
					return "notificationForegroundServiceTextDriverLoanerToCustomer"
			case .model:
					return "model"
			case .notAvailable:
					return "notAvailable"
			case .viewScheduleEmpty:
					return "viewScheduleEmpty"
			case .permissionsCameraDeniedTitle:
					return "permissionsCameraDeniedTitle"
			case .number8:
					return "number8"
			case .viewInspectDocuments:
					return "viewInspectDocuments"
			case .popupTooFarFromDealershipMessage:
					return "popupTooFarFromDealershipMessage"
			case .errorOffline:
					return "errorOffline"
			case .viewReceiveVehicle:
					return "viewReceiveVehicle"
			case .viewArrivedatDeliverySwipeButtonTitle:
					return "viewArrivedatDeliverySwipeButtonTitle"
			case .viewScheduleStateRefreshInfo:
					return "viewScheduleStateRefreshInfo"
			case .errorEnterLoanerMileage:
					return "errorEnterLoanerMileage"
			case .notificationBatteryWarningTextBig:
					return "notificationBatteryWarningTextBig"
			case .viewReceiveVehicleLoanerNext:
					return "viewReceiveVehicleLoanerNext"
			case .newPassword:
					return "newPassword"
			case .skip:
					return "skip"
			case .delivery:
					return "delivery"
			case .viewStartRequestRetrieveForms:
					return "viewStartRequestRetrieveForms"
			case .viewStartRequestPickup:
					return "viewStartRequestPickup"
			case .viewStartRequestRetrieveCustomerVehicle:
					return "viewStartRequestRetrieveCustomerVehicle"
			case .errorOnline:
					return "errorOnline"
			case .viewScheduleStateRefreshButton:
					return "viewScheduleStateRefreshButton"
			case .addressColon:
					return "addressColon"
			case .next:
					return "next"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .popupForgotPasswordMessage:
					return "popupForgotPasswordMessage"
			case .viewExchangeKeysSwipeButtonTitle:
					return "viewExchangeKeysSwipeButtonTitle"
			case .notificationBatteryWarningText:
					return "notificationBatteryWarningText"
			case .viewInspectDocumentsMinPhotosWarning:
					return "viewInspectDocumentsMinPhotosWarning"
			case .viewDriveto:
					return "viewDriveto"
			case .notificationForegroundServiceTextDriverMeetWithCustomer:
					return "notificationForegroundServiceTextDriverMeetWithCustomer"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .viewNavigateWazeText:
					return "viewNavigateWazeText"
			case .loading:
					return "loading"
			case .viewRetrieveVehicleCustomerSwipeTitle:
					return "viewRetrieveVehicleCustomerSwipeTitle"
			case .viewInspectCustomerOverlayInfo:
					return "viewInspectCustomerOverlayInfo"
			case .notificationForegroundServiceTextDriverInspectDocuments:
					return "notificationForegroundServiceTextDriverInspectDocuments"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .viewRecordLoanerMileage:
					return "viewRecordLoanerMileage"
			case .viewInspectLoanerMinPhotosWarning:
					return "viewInspectLoanerMinPhotosWarning"
			case .viewSchedule:
					return "viewSchedule"
			case .popupMileageMaxConfirmation:
					return "popupMileageMaxConfirmation"
			case .deliveryColon:
					return "deliveryColon"
			case .done:
					return "done"
			case .pickupColon:
					return "pickupColon"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .viewExchangeKeysPickupSwipeTitle:
					return "viewExchangeKeysPickupSwipeTitle"
			case .viewDrawerNavigationPreferenceTitle:
					return "viewDrawerNavigationPreferenceTitle"
			case .popupTooFarFromDealershipPositive:
					return "popupTooFarFromDealershipPositive"
			case .viewDrivetoSwipeButtonTitle:
					return "viewDrivetoSwipeButtonTitle"
			case .viewRetrieveForms:
					return "viewRetrieveForms"
			case .help:
					return "help"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .notificationForegroundServiceTitle:
					return "notificationForegroundServiceTitle"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .viewInspectCustomerMinPhotoWarning:
					return "viewInspectCustomerMinPhotoWarning"
			case .number7:
					return "number7"
			case .readMore:
					return "readMore"
			case .popupGetToDealershipTitle:
					return "popupGetToDealershipTitle"
			case .update:
					return "update"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .viewSigninPhoto:
					return "viewSigninPhoto"
			case .inspectVehicles:
					return "inspectVehicles"
			case .number2:
					return "number2"
			case .viewScheduleEmptyToday:
					return "viewScheduleEmptyToday"
			case .viewDrawerProfileOptionsChangeContact:
					return "viewDrawerProfileOptionsChangeContact"
			case .viewReceiveVehicleLoaner:
					return "viewReceiveVehicleLoaner"
			case .viewDrivetoArriveatCustomer:
					return "viewDrivetoArriveatCustomer"
			case .passwordRequirements:
					return "passwordRequirements"
			case .viewScheduleState:
					return "viewScheduleState"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
