//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Unlocalized.loadError
 Unlocalized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case errorOffline
	case permissionsCameraDeniedMessage
	case remove
	case support
	case errorForcedUpgradeTitle
	case viewProfileChangePasswordTemp
	case viewInspectNotesSwipeButtonTitle
	case viewInspectLoanerMinPhotoWarning
	case viewLogoTitle
	case errorFaceDetectionMessage
	case number8
	case year
	case viewDrawerProfileOptionsChangeContact
	case viewScheduleListHeaderNameUpcomingToday
	case viewTosContentTermsOfService
	case viewContactCall
	case number2
	case viewRecordLoanerMileagePickupSwipeButtonTitle
	case viewRetrieveVehicleLoanerSwipeTitle
	case errorAmbiguousCustomerUpsert
	case vehicleMake
	case viewScheduleStateRefreshInfo
	case viewTosContentTermsOfServiceTitle
	case exchangeKeys
	case delivery
	case notificationForegroundServiceTextDriverInspectCustomer
	case popupChooseDealershipTitle
	case add
	case inspectVehicle
	case popupAlreadyStartedDrivingMessage
	case viewRetrieveFormsSwipeTitle
	case mins
	case errorSoftUpgradeTitle
	case modelColon
	case permissionsLocationDeniedTitle
	case confirmNewPassword
	case viewScheduleState
	case viewInspectLoaner
	case number11
	case viewScheduleEmpty
	case viewReceiveVehicleLoaner
	case notificationForegroundServiceTextRetrieveForms
	case viewInspectDocumentsMinPhotoWarning
	case dismiss
	case errorInvalidPasswordConfirm
	case viewReceiveVehicle
	case dealership
	case viewRetrieveVehicleCustomerInfoNext
	case viewTosContentPrivacyPolicy
	case viewDrawerProfileOptionsAttributions
	case resendCode
	case viewHelpCategoryLastLeg
	case notificationForegroundServiceTextDriveLoanerToDealership
	case viewExchangeKeysInfoReminder
	case popupTooFarFromCustomerMessage
	case viewHelpCategoryHowLuxeByVolvoWorks
	case viewDrivetoSwipeButtonTitle
	case viewInspectDocuments
	case exchangeKey
	case notificationForegroundServiceTextRetrieveVehicle
	case popupSoftUpgradeNegative
	case phoneNumberCannotBeEmpty
	case viewScheduleServiceStatusSelfDealershipNavigate
	case popupUpdatingLocation
	case permissionsLocationDeniedMessage
	case viewEmailBody
	case recentMileageColon
	case notificationForegroundServiceTextDriverVehicleToCustomer
	case viewPhoneVerificationLabel
	case errorVerifyPhoneNumber
	case notificationForegroundServiceTextGetToDealership
	case viewRetrieveVehicleCustomerSwipeTitle
	case retry
	case viewInspectDocumentsOverlayInfo
	case popupDeviceChangeMessage
	case viewScheduleServiceStatusSelfAdvisorPickup
	case viewHelpOptionDetailCallVolvo
	case viewEmailSubject
	case errorInvalidPhoneNumber
	case requestCompleted
	case toastSettingsLocationDisabled
	case errorSoftUpgradeMessage
	case viewInspectCustomerMinPhotosWarning
	case viewReceiveVehicleLoanerSwipeButtonTitle
	case popupMileageMinConfirmation
	case min
	case viewRetrieveVehicleLoaner
	case popupAlreadyStartedDrivingPositive
	case viewInspectNotes
	case inspectVehicles
	case done
	case viewSchedule
	case error
	case new
	case notificationForegroundServiceTextDriverLoanerToCustomer
	case confirmPhoneNumber
	case viewArrivedatCustomer
	case viewIntroFooterSignup
	case viewRecordLoanerMileage
	case errorLocationOutOfPickupArea
	case popupDeviceChangeTitle
	case volvoYearModel
	case viewDrawerNavigationPreferenceWaze
	case next
	case viewArrivedatDeliveryInspectVehicles
	case viewRetrieveVehicleCustomer
	case viewInspectDocumentsMinPhotosWarning
	case errorIllegalRequestTaskChange
	case popupTooFarFromDealershipTitle
	case viewInspectLoanerOverlayInfo
	case number5
	case notificationForegroundServiceTextRetrieveLoaner
	case change
	case settings
	case popupPhoneVerificationResendCodeTitle
	case cancel
	case viewTosContentPrivacyPolicyUrl
	case number1
	case viewScheduleListItemTypePickup
	case popupTooFarFromCustomerTitle
	case back
	case errorIllegalRequestStateChange
	case customerColon
	case help
	case errorInvalidEmail
	case skip
	case passwordRequirements
	case popupHardRefreshMessage
	case viewRetrieveForms
	case notificationBatteryWarningTextBig
	case appName
	case viewIntro
	case goBack
	case update
	case emailAddress
	case model
	case viewStartRequestDropoff
	case viewStartRequestSwipeButtonTitle
	case errorRemoveVehicleError
	case popupAddNewLocationLabel
	case keyCodeColon
	case viewGettoDealershipSwipeButtonTitle
	case errorInvalidFirstName
	case readMore
	case viewScheduleCurrent
	case notificationForegroundServiceTextRecordLoanerMileage
	case iAmSure
	case errorInvalidVerificationCode
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case viewRetrieveFormsInfoNext
	case popupGetToCustomerTitle
	case viewSigninActionSignin
	case popupGetToDealershipTitle
	case viewInspectNotesDescriptionHint
	case viewNavigateAddressCopiedToClipboard
	case errorLocationOutOfDropoffArea
	case viewArrivedatDeliverySwipeButtonTitle
	case viewStartRequestPickup
	case requestReset
	case viewNavigateText
	case number6
	case viewScheduleServiceTypeOtherUnknown
	case deliveryColon
	case number9
	case viewScheduleEmptyToday
	case viewGettoCustomerSwipeButtonTitle
	case viewGettoCustomerArriveatCustomer
	case viewDrivetoCustomer
	case viewReceiveVehicleInfoReminder
	case number10
	case errorUnknown
	case viewHelpOptionDetailEmailDealer
	case viewReceiveVehicleCustomerSwipeButtonTitle
	case helpICantUpdateMyPhone
	case viewScheduleStateRefreshButton
	case errorOnline
	case notificationForegroundServiceTextReceiveLoaner
	case viewChecklistLoanerAgreementLabel
	case viewTosContent
	case updateNow
	case requestTaskChangedFromBackend
	case viewScheduleListHeaderNameCurrent
	case requestCanceled
	case errorInvalidCredentials
	case errorInvalidLastName
	case viewInspectCustomer
	case notificationForegroundServiceTextDriverGetToCustomer
	case viewReturntoSwipeButtonTitle
	case popupTooFarFromDealershipMessage
	case popupTooFarFromCustomerPositive
	case later
	case viewHelpOptionDetailCallDealer
	case licensePlateColon
	case notificationBatteryWarningText
	case viewDriveto
	case errorForcedUpgradeMessage
	case viewPhoneAdd
	case viewDrawerNavigationPreferenceTitle
	case helpIForgotMyPassword
	case viewArrivedat
	case viewRecordLoanerMileageDropoffInfoNext
	case viewHelpOptionDetailEmailVolvo
	case popupGetToCustomerCopyToClipboard
	case pickupColon
	case errorInvalidApplicationVersion
	case viewPhoneAddLabel
	case unknown
	case viewNavigateWazeText
	case popupAlreadyStartedDrivingTitle
	case viewSigninPasswordShort
	case viewEmailIntentChooserTitle
	case returnToDealership
	case errorInvalidUserDisabled
	case currentPassword
	case viewProfileChangeContact
	case viewScheduleListHeaderNameCompletedToday
	case close
	case loanerColon
	case viewDrawerProfileOptionsChangePassword
	case viewDrawerContactDealershipText
	case viewReceiveVehicleCustomer
	case errorUserDisabled
	case errorPhoneNumberTaken
	case errorOops
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case viewReceiveVehicleLoanerNext
	case notificationForegroundServiceTitle
	case viewSwipeButtonInnerText
	case serviceColon
	case popupSelectTimeSlotUnavailableCallDealership
	case popupPhoneVerificationResendCodeMessage
	case viewRetrieveVehicle
	case notificationForegroundServiceTextDriverInspectDocuments
	case notesColon
	case errorRequestNotCancelable
	case viewExchangeKeysPickupSwipeTitle
	case errorAmbiguousVehicleUpsert
	case viewTosContentPrivacyPolicyTitle
	case popupGetToDealershipCopyToClipboard
	case notificationForegroundServiceTextDriverInspectLoaner
	case viewStartRequestRetrieveCustomerVehicle
	case viewGettoCustomer
	case notificationBatteryWarningTitle
	case notificationForegroundServiceTextDriveCustomerToDealership
	case viewStartRequestRetrieveForms
	case viewGetToText
	case viewArrivedatPickupSwipeButtonTitle
	case errorInvalidPasswordUnauthorizedCharacters
	case viewDrawerContactDealershipCall
	case yes
	case popupForgotPasswordTitle
	case phoneNumberAlreadyTaken
	case notificationActionOpen
	case number3
	case popupHardRefreshTitle
	case viewInspectCustomerMinPhotoWarning
	case signout
	case notificationForegroundServiceTextDriverExchangeKeys
	case viewDrawerProfileOptionsSignout
	case errorInvalidPhoneVerificationCode
	case repairOrderColon
	case addressColon
	case pickup
	case openSettings
	case notificationForegroundServiceTextInspectNotes
	case popupForgotPasswordMessage
	case viewContactText
	case number4
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case viewScheduleListItemTypeDeliver
	case loading
	case viewExchangeKeysSwipeButtonTitle
	case color
	case password
	case viewSigninEmailInvalid
	case notAvailable
	case errorLocationServiceNotOfferedInYourArea
	case viewSigninPopupProgressSignin
	case viewStartRequestRetrieveLoaner
	case confirmationCode
	case viewDrivetoArriveatCustomer
	case viewIntroFooterSignin
	case viewRecordLoanerMileageDropoffSwipeButtonTitle
	case yourAccount
	case viewSigninPhoto
	case viewDrawerNavigationPreferenceGoogle
	case errorEnterLoanerMileage
	case errorLocationServiceUnavailable
	case no
	case phoneNumber
	case contact
	case errorDuplicateLoanerVehicleBookingAssignment
	case viewSignin
	case edit
	case errorAccountAlreadyExists
	case popupMileageMaxConfirmation
	case viewInspectLoanerMinPhotosWarning
	case createPassword
	case viewSigninForgotPassword
	case viewTosContentTermsOfServiceUrl
	case viewInspectCustomerOverlayInfo
	case newPassword
	case viewSoftwareLicences
	case viewExchangeKeysDeliverySwipeTitle
	case popupSignoutConfirmationMessage
	case notificationForegroundServiceTextDriverMeetWithCustomer
	case popupTooFarFromDealershipPositive
	case notNow
	case ok
	case number7
	case errorInvalidPassword
	case permissionsCameraDeniedTitle

    var key : String {
        switch self {
            case .errorOffline:
					return "errorOffline"
			case .permissionsCameraDeniedMessage:
					return "permissionsCameraDeniedMessage"
			case .remove:
					return "remove"
			case .support:
					return "support"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .viewProfileChangePasswordTemp:
					return "viewProfileChangePasswordTemp"
			case .viewInspectNotesSwipeButtonTitle:
					return "viewInspectNotesSwipeButtonTitle"
			case .viewInspectLoanerMinPhotoWarning:
					return "viewInspectLoanerMinPhotoWarning"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .errorFaceDetectionMessage:
					return "errorFaceDetectionMessage"
			case .number8:
					return "number8"
			case .year:
					return "year"
			case .viewDrawerProfileOptionsChangeContact:
					return "viewDrawerProfileOptionsChangeContact"
			case .viewScheduleListHeaderNameUpcomingToday:
					return "viewScheduleListHeaderNameUpcomingToday"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .viewContactCall:
					return "viewContactCall"
			case .number2:
					return "number2"
			case .viewRecordLoanerMileagePickupSwipeButtonTitle:
					return "viewRecordLoanerMileagePickupSwipeButtonTitle"
			case .viewRetrieveVehicleLoanerSwipeTitle:
					return "viewRetrieveVehicleLoanerSwipeTitle"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .vehicleMake:
					return "vehicleMake"
			case .viewScheduleStateRefreshInfo:
					return "viewScheduleStateRefreshInfo"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .exchangeKeys:
					return "exchangeKeys"
			case .delivery:
					return "delivery"
			case .notificationForegroundServiceTextDriverInspectCustomer:
					return "notificationForegroundServiceTextDriverInspectCustomer"
			case .popupChooseDealershipTitle:
					return "popupChooseDealershipTitle"
			case .add:
					return "add"
			case .inspectVehicle:
					return "inspectVehicle"
			case .popupAlreadyStartedDrivingMessage:
					return "popupAlreadyStartedDrivingMessage"
			case .viewRetrieveFormsSwipeTitle:
					return "viewRetrieveFormsSwipeTitle"
			case .mins:
					return "mins"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .modelColon:
					return "modelColon"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .confirmNewPassword:
					return "confirmNewPassword"
			case .viewScheduleState:
					return "viewScheduleState"
			case .viewInspectLoaner:
					return "viewInspectLoaner"
			case .number11:
					return "number11"
			case .viewScheduleEmpty:
					return "viewScheduleEmpty"
			case .viewReceiveVehicleLoaner:
					return "viewReceiveVehicleLoaner"
			case .notificationForegroundServiceTextRetrieveForms:
					return "notificationForegroundServiceTextRetrieveForms"
			case .viewInspectDocumentsMinPhotoWarning:
					return "viewInspectDocumentsMinPhotoWarning"
			case .dismiss:
					return "dismiss"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .viewReceiveVehicle:
					return "viewReceiveVehicle"
			case .dealership:
					return "dealership"
			case .viewRetrieveVehicleCustomerInfoNext:
					return "viewRetrieveVehicleCustomerInfoNext"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .viewDrawerProfileOptionsAttributions:
					return "viewDrawerProfileOptionsAttributions"
			case .resendCode:
					return "resendCode"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .notificationForegroundServiceTextDriveLoanerToDealership:
					return "notificationForegroundServiceTextDriveLoanerToDealership"
			case .viewExchangeKeysInfoReminder:
					return "viewExchangeKeysInfoReminder"
			case .popupTooFarFromCustomerMessage:
					return "popupTooFarFromCustomerMessage"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .viewDrivetoSwipeButtonTitle:
					return "viewDrivetoSwipeButtonTitle"
			case .viewInspectDocuments:
					return "viewInspectDocuments"
			case .exchangeKey:
					return "exchangeKey"
			case .notificationForegroundServiceTextRetrieveVehicle:
					return "notificationForegroundServiceTextRetrieveVehicle"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .viewEmailBody:
					return "viewEmailBody"
			case .recentMileageColon:
					return "recentMileageColon"
			case .notificationForegroundServiceTextDriverVehicleToCustomer:
					return "notificationForegroundServiceTextDriverVehicleToCustomer"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .notificationForegroundServiceTextGetToDealership:
					return "notificationForegroundServiceTextGetToDealership"
			case .viewRetrieveVehicleCustomerSwipeTitle:
					return "viewRetrieveVehicleCustomerSwipeTitle"
			case .retry:
					return "retry"
			case .viewInspectDocumentsOverlayInfo:
					return "viewInspectDocumentsOverlayInfo"
			case .popupDeviceChangeMessage:
					return "popupDeviceChangeMessage"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .requestCompleted:
					return "requestCompleted"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .viewInspectCustomerMinPhotosWarning:
					return "viewInspectCustomerMinPhotosWarning"
			case .viewReceiveVehicleLoanerSwipeButtonTitle:
					return "viewReceiveVehicleLoanerSwipeButtonTitle"
			case .popupMileageMinConfirmation:
					return "popupMileageMinConfirmation"
			case .min:
					return "min"
			case .viewRetrieveVehicleLoaner:
					return "viewRetrieveVehicleLoaner"
			case .popupAlreadyStartedDrivingPositive:
					return "popupAlreadyStartedDrivingPositive"
			case .viewInspectNotes:
					return "viewInspectNotes"
			case .inspectVehicles:
					return "inspectVehicles"
			case .done:
					return "done"
			case .viewSchedule:
					return "viewSchedule"
			case .error:
					return "error"
			case .new:
					return "new"
			case .notificationForegroundServiceTextDriverLoanerToCustomer:
					return "notificationForegroundServiceTextDriverLoanerToCustomer"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .viewArrivedatCustomer:
					return "viewArrivedatCustomer"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .viewRecordLoanerMileage:
					return "viewRecordLoanerMileage"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .popupDeviceChangeTitle:
					return "popupDeviceChangeTitle"
			case .volvoYearModel:
					return "volvoYearModel"
			case .viewDrawerNavigationPreferenceWaze:
					return "viewDrawerNavigationPreferenceWaze"
			case .next:
					return "next"
			case .viewArrivedatDeliveryInspectVehicles:
					return "viewArrivedatDeliveryInspectVehicles"
			case .viewRetrieveVehicleCustomer:
					return "viewRetrieveVehicleCustomer"
			case .viewInspectDocumentsMinPhotosWarning:
					return "viewInspectDocumentsMinPhotosWarning"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .popupTooFarFromDealershipTitle:
					return "popupTooFarFromDealershipTitle"
			case .viewInspectLoanerOverlayInfo:
					return "viewInspectLoanerOverlayInfo"
			case .number5:
					return "number5"
			case .notificationForegroundServiceTextRetrieveLoaner:
					return "notificationForegroundServiceTextRetrieveLoaner"
			case .change:
					return "change"
			case .settings:
					return "settings"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
			case .cancel:
					return "cancel"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .number1:
					return "number1"
			case .viewScheduleListItemTypePickup:
					return "viewScheduleListItemTypePickup"
			case .popupTooFarFromCustomerTitle:
					return "popupTooFarFromCustomerTitle"
			case .back:
					return "back"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .customerColon:
					return "customerColon"
			case .help:
					return "help"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .skip:
					return "skip"
			case .passwordRequirements:
					return "passwordRequirements"
			case .popupHardRefreshMessage:
					return "popupHardRefreshMessage"
			case .viewRetrieveForms:
					return "viewRetrieveForms"
			case .notificationBatteryWarningTextBig:
					return "notificationBatteryWarningTextBig"
			case .appName:
					return "appName"
			case .viewIntro:
					return "viewIntro"
			case .goBack:
					return "goBack"
			case .update:
					return "update"
			case .emailAddress:
					return "emailAddress"
			case .model:
					return "model"
			case .viewStartRequestDropoff:
					return "viewStartRequestDropoff"
			case .viewStartRequestSwipeButtonTitle:
					return "viewStartRequestSwipeButtonTitle"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .keyCodeColon:
					return "keyCodeColon"
			case .viewGettoDealershipSwipeButtonTitle:
					return "viewGettoDealershipSwipeButtonTitle"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .readMore:
					return "readMore"
			case .viewScheduleCurrent:
					return "viewScheduleCurrent"
			case .notificationForegroundServiceTextRecordLoanerMileage:
					return "notificationForegroundServiceTextRecordLoanerMileage"
			case .iAmSure:
					return "iAmSure"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .viewRetrieveFormsInfoNext:
					return "viewRetrieveFormsInfoNext"
			case .popupGetToCustomerTitle:
					return "popupGetToCustomerTitle"
			case .viewSigninActionSignin:
					return "viewSigninActionSignin"
			case .popupGetToDealershipTitle:
					return "popupGetToDealershipTitle"
			case .viewInspectNotesDescriptionHint:
					return "viewInspectNotesDescriptionHint"
			case .viewNavigateAddressCopiedToClipboard:
					return "viewNavigateAddressCopiedToClipboard"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .viewArrivedatDeliverySwipeButtonTitle:
					return "viewArrivedatDeliverySwipeButtonTitle"
			case .viewStartRequestPickup:
					return "viewStartRequestPickup"
			case .requestReset:
					return "requestReset"
			case .viewNavigateText:
					return "viewNavigateText"
			case .number6:
					return "number6"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .deliveryColon:
					return "deliveryColon"
			case .number9:
					return "number9"
			case .viewScheduleEmptyToday:
					return "viewScheduleEmptyToday"
			case .viewGettoCustomerSwipeButtonTitle:
					return "viewGettoCustomerSwipeButtonTitle"
			case .viewGettoCustomerArriveatCustomer:
					return "viewGettoCustomerArriveatCustomer"
			case .viewDrivetoCustomer:
					return "viewDrivetoCustomer"
			case .viewReceiveVehicleInfoReminder:
					return "viewReceiveVehicleInfoReminder"
			case .number10:
					return "number10"
			case .errorUnknown:
					return "errorUnknown"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .viewReceiveVehicleCustomerSwipeButtonTitle:
					return "viewReceiveVehicleCustomerSwipeButtonTitle"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .viewScheduleStateRefreshButton:
					return "viewScheduleStateRefreshButton"
			case .errorOnline:
					return "errorOnline"
			case .notificationForegroundServiceTextReceiveLoaner:
					return "notificationForegroundServiceTextReceiveLoaner"
			case .viewChecklistLoanerAgreementLabel:
					return "viewChecklistLoanerAgreementLabel"
			case .viewTosContent:
					return "viewTosContent"
			case .updateNow:
					return "updateNow"
			case .requestTaskChangedFromBackend:
					return "requestTaskChangedFromBackend"
			case .viewScheduleListHeaderNameCurrent:
					return "viewScheduleListHeaderNameCurrent"
			case .requestCanceled:
					return "requestCanceled"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .viewInspectCustomer:
					return "viewInspectCustomer"
			case .notificationForegroundServiceTextDriverGetToCustomer:
					return "notificationForegroundServiceTextDriverGetToCustomer"
			case .viewReturntoSwipeButtonTitle:
					return "viewReturntoSwipeButtonTitle"
			case .popupTooFarFromDealershipMessage:
					return "popupTooFarFromDealershipMessage"
			case .popupTooFarFromCustomerPositive:
					return "popupTooFarFromCustomerPositive"
			case .later:
					return "later"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .licensePlateColon:
					return "licensePlateColon"
			case .notificationBatteryWarningText:
					return "notificationBatteryWarningText"
			case .viewDriveto:
					return "viewDriveto"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .viewPhoneAdd:
					return "viewPhoneAdd"
			case .viewDrawerNavigationPreferenceTitle:
					return "viewDrawerNavigationPreferenceTitle"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .viewArrivedat:
					return "viewArrivedat"
			case .viewRecordLoanerMileageDropoffInfoNext:
					return "viewRecordLoanerMileageDropoffInfoNext"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .popupGetToCustomerCopyToClipboard:
					return "popupGetToCustomerCopyToClipboard"
			case .pickupColon:
					return "pickupColon"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .viewPhoneAddLabel:
					return "viewPhoneAddLabel"
			case .unknown:
					return "unknown"
			case .viewNavigateWazeText:
					return "viewNavigateWazeText"
			case .popupAlreadyStartedDrivingTitle:
					return "popupAlreadyStartedDrivingTitle"
			case .viewSigninPasswordShort:
					return "viewSigninPasswordShort"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .returnToDealership:
					return "returnToDealership"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .currentPassword:
					return "currentPassword"
			case .viewProfileChangeContact:
					return "viewProfileChangeContact"
			case .viewScheduleListHeaderNameCompletedToday:
					return "viewScheduleListHeaderNameCompletedToday"
			case .close:
					return "close"
			case .loanerColon:
					return "loanerColon"
			case .viewDrawerProfileOptionsChangePassword:
					return "viewDrawerProfileOptionsChangePassword"
			case .viewDrawerContactDealershipText:
					return "viewDrawerContactDealershipText"
			case .viewReceiveVehicleCustomer:
					return "viewReceiveVehicleCustomer"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .errorOops:
					return "errorOops"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .viewReceiveVehicleLoanerNext:
					return "viewReceiveVehicleLoanerNext"
			case .notificationForegroundServiceTitle:
					return "notificationForegroundServiceTitle"
			case .viewSwipeButtonInnerText:
					return "viewSwipeButtonInnerText"
			case .serviceColon:
					return "serviceColon"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .viewRetrieveVehicle:
					return "viewRetrieveVehicle"
			case .notificationForegroundServiceTextDriverInspectDocuments:
					return "notificationForegroundServiceTextDriverInspectDocuments"
			case .notesColon:
					return "notesColon"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .viewExchangeKeysPickupSwipeTitle:
					return "viewExchangeKeysPickupSwipeTitle"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .popupGetToDealershipCopyToClipboard:
					return "popupGetToDealershipCopyToClipboard"
			case .notificationForegroundServiceTextDriverInspectLoaner:
					return "notificationForegroundServiceTextDriverInspectLoaner"
			case .viewStartRequestRetrieveCustomerVehicle:
					return "viewStartRequestRetrieveCustomerVehicle"
			case .viewGettoCustomer:
					return "viewGettoCustomer"
			case .notificationBatteryWarningTitle:
					return "notificationBatteryWarningTitle"
			case .notificationForegroundServiceTextDriveCustomerToDealership:
					return "notificationForegroundServiceTextDriveCustomerToDealership"
			case .viewStartRequestRetrieveForms:
					return "viewStartRequestRetrieveForms"
			case .viewGetToText:
					return "viewGetToText"
			case .viewArrivedatPickupSwipeButtonTitle:
					return "viewArrivedatPickupSwipeButtonTitle"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .viewDrawerContactDealershipCall:
					return "viewDrawerContactDealershipCall"
			case .yes:
					return "yes"
			case .popupForgotPasswordTitle:
					return "popupForgotPasswordTitle"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .notificationActionOpen:
					return "notificationActionOpen"
			case .number3:
					return "number3"
			case .popupHardRefreshTitle:
					return "popupHardRefreshTitle"
			case .viewInspectCustomerMinPhotoWarning:
					return "viewInspectCustomerMinPhotoWarning"
			case .signout:
					return "signout"
			case .notificationForegroundServiceTextDriverExchangeKeys:
					return "notificationForegroundServiceTextDriverExchangeKeys"
			case .viewDrawerProfileOptionsSignout:
					return "viewDrawerProfileOptionsSignout"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .repairOrderColon:
					return "repairOrderColon"
			case .addressColon:
					return "addressColon"
			case .pickup:
					return "pickup"
			case .openSettings:
					return "openSettings"
			case .notificationForegroundServiceTextInspectNotes:
					return "notificationForegroundServiceTextInspectNotes"
			case .popupForgotPasswordMessage:
					return "popupForgotPasswordMessage"
			case .viewContactText:
					return "viewContactText"
			case .number4:
					return "number4"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .viewScheduleListItemTypeDeliver:
					return "viewScheduleListItemTypeDeliver"
			case .loading:
					return "loading"
			case .viewExchangeKeysSwipeButtonTitle:
					return "viewExchangeKeysSwipeButtonTitle"
			case .color:
					return "color"
			case .password:
					return "password"
			case .viewSigninEmailInvalid:
					return "viewSigninEmailInvalid"
			case .notAvailable:
					return "notAvailable"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .viewSigninPopupProgressSignin:
					return "viewSigninPopupProgressSignin"
			case .viewStartRequestRetrieveLoaner:
					return "viewStartRequestRetrieveLoaner"
			case .confirmationCode:
					return "confirmationCode"
			case .viewDrivetoArriveatCustomer:
					return "viewDrivetoArriveatCustomer"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .viewRecordLoanerMileageDropoffSwipeButtonTitle:
					return "viewRecordLoanerMileageDropoffSwipeButtonTitle"
			case .yourAccount:
					return "yourAccount"
			case .viewSigninPhoto:
					return "viewSigninPhoto"
			case .viewDrawerNavigationPreferenceGoogle:
					return "viewDrawerNavigationPreferenceGoogle"
			case .errorEnterLoanerMileage:
					return "errorEnterLoanerMileage"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .no:
					return "no"
			case .phoneNumber:
					return "phoneNumber"
			case .contact:
					return "contact"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
			case .viewSignin:
					return "viewSignin"
			case .edit:
					return "edit"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .popupMileageMaxConfirmation:
					return "popupMileageMaxConfirmation"
			case .viewInspectLoanerMinPhotosWarning:
					return "viewInspectLoanerMinPhotosWarning"
			case .createPassword:
					return "createPassword"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .viewInspectCustomerOverlayInfo:
					return "viewInspectCustomerOverlayInfo"
			case .newPassword:
					return "newPassword"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .viewExchangeKeysDeliverySwipeTitle:
					return "viewExchangeKeysDeliverySwipeTitle"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .notificationForegroundServiceTextDriverMeetWithCustomer:
					return "notificationForegroundServiceTextDriverMeetWithCustomer"
			case .popupTooFarFromDealershipPositive:
					return "popupTooFarFromDealershipPositive"
			case .notNow:
					return "notNow"
			case .ok:
					return "ok"
			case .number7:
					return "number7"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .permissionsCameraDeniedTitle:
					return "permissionsCameraDeniedTitle"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
