# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def import_pods
    pod 'Alamofire', '4.5.1'
    pod 'AlamofireObjectMapper', '5.0.0'
    pod 'AlamofireNetworkActivityLogger', '2.2'
    pod 'BrightFutures', '6.0.1'
    pod 'CocoaLumberjack/Swift', '3.3.0'
    pod 'Crashlytics', '3.10.1'
    pod 'DateToolsSwift', '4.0.0'
    pod 'Fabric', '1.7.6'
    pod 'Firebase/Core', '4.7.0'
    pod 'Firebase/Messaging', '4.7.0'
    pod 'Firebase/RemoteConfig', '4.7.0'
    pod 'GoogleMaps', '2.5.0'
    pod 'GooglePlaces', '2.5.0'
    pod 'KeychainAccess', '3.1.0'
    pod 'Kingfisher', '4.2.0'
    pod 'MBProgressHUD', '1.1.0'
    pod 'PhoneNumberKit', '2.0'
    pod 'RealmSwift', '3.0.2'
    pod 'SDWebImage', '4.0.0'
    pod 'SlideMenuControllerSwift', '4.0.0'
    pod 'SnapKit', '4.0.0'
    pod 'SwiftyJSON', '4.0.0-alpha.1'
    pod 'SwiftEventBus', '2.1.2'
    pod 'UIColor_Hex_Swift', '3.0.2'
end

target 'voluxe-customer' do
    # Pods for voluxe-customer
    import_pods
end

target 'voluxe-customerTests' do
    import_pods
end

target 'voluxe-customerUITests' do
    import_pods
end


