//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Localized.loadError
 Localized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case helpHowLuxebyVolvoWorks
	case deliveryLocation
	case viewScheduleServiceStatusInfoScheduledPickup
	case viewProfileContactHeader
	case helpRequestingDataFromLuxebyVolvoDetail
	case helpNoneOfTheAvailableTimesWorkForMeDetail
	case errorIllegalRequestStateChange
	case helpTroubleWithTheLuxebyVolvoApp
	case errorRequestNotCancelable
	case helpILostAnItem
	case skip
	case helpTermsOfServiceDetail
	case viewSettingsDistanceUnitHeader
	case viewScheduleServiceStatusSelfAdvisorPickup
	case viewScheduleServiceVehicleServiceScheduled
	case needALoaner
	case errorUpdatePhoneNumberAlreadyExist
	case popupPhoneVerificationResendCodeTitle
	case number11
	case mins
	case helpPrivacyPolicyInformationDetail
	case popupSelectLocationCurrentLocation
	case viewVehicleAddModelHint
	case popupSelectTimeSlotUnavailableCallDealershipNotAvailable
	case errorForcedUpgradeTitle
	case number8
	case updateNow
	case underTheHood
	case confirm
	case pickup
	case popupSelectLocationPermissionNote
	case number3
	case helpICantUpdateMyPhoneDetail
	case errorInvalidCredentials
	case yourAccount
	case viewEditTextInfoHintFirstName
	case refresh
	case errorLocationServiceUnavailable
	case popupSelectTimeSlotTimesLabelPickup
	case viewScheduleServiceStatusCompleteInfo
	case viewScheduleServiceOptionInfoPickup
	case cancelPickup
	case toastSettingsLocationDisabled
	case appName
	case permissionAllowNotificationMessage
	case popupAdvisorDropoffSelfPickup
	case permissionLocationTitle
	case helpNoneOfTheAvailableTimesWorkForMe
	case viewHelpOptionDetailEmailVolvo
	case viewScheduleServiceStatusComplete
	case viewSettingsDistanceUnitTitle
	case errorPhoneNumberTaken
	case popupSelectTimeSlotLabelDropoff
	case viewScheduleServiceOptionPickup
	case completedService
	case number5
	case confirmationCode
	case viewHelpCategoryLastLeg
	case helpTooFewLoanersAvailable
	case popupSelectTimeSlotTimesLabelDropoff
	case helpMyVehicleWasDamaged
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case viewScheduleServiceOptionDropoff
	case helpIForgotMyPassword
	case signout
	case viewScheduleServiceStatusTimeWindowEstimatedDelivery
	case notAvailable
	case imNotSure
	case popupPhoneVerificationResendCodeMessage
	case viewScheduleServiceOptionPickupSelfDropPickup
	case helpNoParticipatingDealershipsInArea
	case map
	case viewEmailIntentChooserTitle
	case later
	case confirmPhoneNumber
	case popupDefaultCancelPickupMessage
	case popupRemoveVehicleMessage
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case permissionAllowNotificationTitle
	case showDetails
	case viewSigninPasswordDescription
	case notNow
	case helpTermsOfService
	case resendCode
	case iDontKnow
	case errorVerifyPhoneNumber
	case viewProfileAccountPasswordHeader
	case vehicleMake
	case errorInvalidPasswordUnauthorizedCharacters
	case number2
	case viewScheduleServiceOptionNoteDropoff
	case viewEditTextTitlePassword
	case newService
	case viewScheduleService
	case errorDuplicateLoanerVehicleBookingAssignment
	case popupContactText
	case errorInvalidPhoneVerificationCode
	case viewHelpOptionDetailCallVolvo
	case popupSelectDealershipLabel
	case viewScheduleServiceTypeDetailNameLabelMilestone
	case viewHelpCategoryHowLuxeByVolvoWorks
	case loading
	case helpMyDriverWasUnprofessional
	case helpThereWasAnIssueWithMyLoanerVehicleDetail
	case popupAddNewLocationLabel
	case viewSigninNameLabel
	case viewScheduleServiceStatusTimeWindowEstimatedPickup
	case viewScheduleServiceStatusInServiceInfo
	case viewHelpOptionDetailEmailDealer
	case yourVolvo
	case viewTosContentTermsOfServiceTitle
	case unknown
	case popupContactTitle
	case viewPhoneVerificationCodeHint
	case cancel
	case ok
	case viewScheduleServiceScheduledLabel
	case errorInvalidUserDisabled
	case color
	case delete
	case viewEditTextPhoneDescription
	case popupSelectTimeSlotLabelPickup
	case updateYourPassword
	case viewTosContentPrivacyPolicyUrl
	case viewScheduleServiceTypeMilestoneDetailNameLabel
	case errorDuplicateRequest
	case readMore
	case viewScheduleServiceStatusInfoNearBy
	case error
	case model
	case contact
	case passwordRequirements
	case helpOther
	case viewProfileLocationHeader
	case viewSettingsSoftwareLicencesHeader
	case helpICantUpdateMyPhone
	case viewScheduleServiceStatusTimeDeliveryWindow
	case scheduleService
	case popupAdvisorPickupMessage
	case helpMyPickupDeliveryLocationWasWrong
	case viewVehicleAddYearHint
	case permissionNotificationMessage
	case min
	case year
	case viewSignupPasswordRequireNumber
	case viewScheduleServiceStatusCompleteRate
	case viewScheduleServiceTypeOtherDetailLabel
	case viewScheduleServiceStatusInfoArrived
	case cancelDropoff
	case new
	case viewEditTextTitleFirstName
	case viewDatesLoanersOnly
	case errorPasswordNotMatch
	case settings
	case viewScheduleServiceTypeMilestone
	case dealership
	case popupDefaultCancelDropoffMessage
	case cancelDelivery
	case errorOops
	case viewScheduleServiceStatusTimePickupWindow
	case scheduledDelivery
	case viewScheduleServiceTypeOtherUnknown
	case viewScheduleServiceStatusAtDealershipInfo
	case number6
	case popupSelectTimeSlotUnavailableCallDealership
	case emailAddress
	case helpMyDriverDidntMatchThePicture
	case viewSigninEmailLabel
	case errorNoMatchingCustomer
	case viewHelpOptionPp
	case popupAdvisorDropoffMessage
	case helpRequestingDataFromLuxebyVolvo
	case permissionAllowButtonTitle
	case errorInvalidPhoneNumber
	case errorUnknown
	case helpICantCancelMyPickupOrDelivery
	case addNewLocation
	case close
	case viewRatingRangeValueOne
	case helpMyVehicleWasDamagedDetail
	case createPassword
	case viewSignupContactLabel
	case scheduleDelivery
	case yourVolvos
	case helpMyDriverWasLateDetail
	case openSettings
	case helpDeleteMyLuxebyVolvoAccount
	case phoneNumberCannotBeEmpty
	case helpTheAppIsntWorkingCorrectlyDetail
	case viewScheduleServiceTypeOtherDetailExtraTitle
	case viewHelpOptionTos
	case yes
	case viewEditTextInfoHintPhoneNumber
	case errorAmbiguousCustomerUpsert
	case currentService
	case viewScheduleServiceOptionConfirmButtonPositiveDropoff
	case errorInvalidPhoneNumberFormatted
	case permissionsLocationDeniedTitle
	case viewEditTextInfoHintLastName
	case viewEditTextTitleEmail
	case viewScheduleServiceStatusFeedback
	case popupSelectLocationLabel
	case errorOnline
	case errorInvalidPasswordConfirm
	case vehicleInterior
	case viewSettingsVolvoAddNewLabel
	case viewEditTextTitlePhoneNumber
	case viewHelpOptionDetailCallDealer
	case helpICouldntContactMyDriver
	case helpOtherDetail
	case viewScheduleServiceStatusReminderPickup
	case viewScheduleServiceStatusInfoEnRoute
	case viewScheduleServiceOptionPickupSelfDeliveryDropoff
	case helpMyCurrentLocationIsntWorkingDetail
	case phoneNumber
	case viewScheduleServiceStatusInfoScheduledDropoff
	case popupSelectLocationPermissionDenied
	case errorAmbiguousVehicleUpsert
	case viewEmailBody
	case viewScheduleServiceTypeOtherDetail
	case viewScheduleServiceStatusSelfDealershipNavigate
	case errorPhoneNumberNotInFile
	case popupSignoutConfirmationMessage
	case helpIMissedMyPickupDeliveryDetail
	case viewScheduleServiceStatusFeedbackCommentTitle
	case viewTosContentTermsOfService
	case errorUserDisabled
	case remove
	case viewRatingRangeValueTen
	case update
	case viewScheduleServiceOptionInfoDropoff
	case errorForcedUpgradeMessage
	case helpPushNotificationsArentWorkingDetail
	case viewTosContentTermsOfServiceUrl
	case viewEditTextTitlePasswordNew
	case viewScheduleServiceTypeDetailNameLabelOther
	case viewIntro
	case viewSigninPhoneLabel
	case number1
	case change
	case helpPushNotificationsArentWorking
	case viewVehicleAddColorHint
	case helpMyDriverWasUnprofessionalDetail
	case helpThereWasAnIssueWithMyLoanerVehicle
	case popupUpdatingLocation
	case errorLocationOutOfDropoffArea
	case viewPhoneVerificationLabel
	case errorAccountAlreadyExists
	case viewTosContentPrivacyPolicyTitle
	case viewScheduleServiceDetailConfirmService
	case errorInvalidCharacter
	case popupAddNewLocationEditHint
	case volvoYearModel
	case viewScheduleServiceOptionInfoSelfDropoff
	case viewTosContent
	case viewIntroFooterSignup
	case viewSettingsSoftwareLicencesTitle
	case errorInvalidPassword
	case viewScheduleServiceStatusFeedbackCommentHint
	case viewEmailSubject
	case no
	case viewSignupNameLabel
	case viewVehicleAddLabel
	case helpSomethingUnsafeHappened
	case helpSomethingUnsafeHappenedDetail
	case viewTosContentPrivacyPolicy
	case viewEditTextInfoHintPasswordConfirm
	case helpICouldntContactMyDriverDetail
	case errorDatabase
	case viewLogoTitle
	case helpMyPickupDeliveryLocationWasWrongDetail
	case viewSignupPasswordRequireLetter
	case viewHelpOptionTitle
	case helpTooFewLoanersAvailableDetail
	case viewSigninPhoneContactChangeLabel
	case errorOffline
	case viewSignupPasswordDescription
	case helpDeleteMyLuxebyVolvoAccountDetail
	case popupSelectTimeSlotTimesLabelDelivery
	case requestReset
	case viewSignupPasswordLabel
	case edit
	case errorInvalidVerificationCode
	case viewSigninForgotPassword
	case helpMyCurrentLocationIsntWorking
	case password
	case back
	case helpICantArrangeServiceDetail
	case schedulePickup
	case vehicleExterior
	case viewScheduledSelfDrop
	case viewScheduleServiceOptionInfoSelfPickup
	case helpICantCancelMyPickupOrDeliveryDetail
	case yourLastDelivery
	case viewScheduleServiceStatusFeedbackCommentLabel
	case retry
	case helpThereWasAnIssueWithMyPaperworkDetail
	case helpMyDriverWasLate
	case phoneNumberAlreadyTaken
	case permissionsLocationDeniedMessage
	case viewScheduleServiceTypeOther
	case errorIllegalRequestTaskChange
	case helpIMissedMyPickupDelivery
	case popupSelectTimeSlotUnavailableLabel
	case viewDealershipCloseToLocation
	case popupAdvisorDropoffSelfPickupDescription
	case viewScheduleServiceTypeDescription
	case errorPhoneNumberAlreadyExist
	case viewSigninPasswordLabel
	case viewScheduleServiceTypeOtherLabel
	case popupAdvisorDropoffLabel
	case changePhoneNumber
	case viewEditTextInfoHintEmail
	case removeVehicle
	case selectedService
	case helpILostAnItemDetail
	case permissionGrantTitle
	case number4
	case viewScheduleServiceTypeOtherDetailExtraLabel
	case next
	case popupSelectTimeSlotLabelDelivery
	case helpICantArrangeService
	case viewScheduleServiceTypeOtherSubLabel
	case popupAdvisorDropoffRescheduleDescription
	case help
	case dismiss
	case done
	case helpPrivacyPolicyInformation
	case errorInvalidApplicationVersion
	case viewIntroFooterSignin
	case viewScheduleServiceStatusCompleteTitle
	case helpMyDriverDidntMatchThePictureDetail
	case scheduledPickup
	case errorInvalidFirstName
	case viewScheduleServiceTypeOtherDetailExtraHint
	case yourLastPickup
	case helpTheAppIsntWorkingCorrectly
	case delivery
	case helpIForgotMyPasswordDetail
	case viewScheduleServiceOptionNotePickup
	case errorSoftUpgradeTitle
	case number10
	case currentPassword
	case errorSoftUpgradeMessage
	case errorInvalidEmail
	case popupSoftUpgradeNegative
	case errorRemoveVehicleError
	case popupRemoveAddressMessage
	case pickupLocation
	case viewScheduleServiceOptionConfirmButtonPositivePickup
	case recommendedService
	case popupAdvisorDropoffReschedule
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case errorInvalidLastName
	case number7
	case viewEditTextTitleLastName
	case npsExtremelyLikely
	case errorEmailAlreadyExist
	case helpThereWasAnIssueWithMyPaperwork
	case errorDeleteVehicleBooking
	case popupContactCall
	case viewSoftwareLicences
	case helpAppOtherDetail
	case add
	case errorLocationServiceNotOfferedInYourArea
	case npsNotLikely
	case viewEditTextTitlePasswordConfirm
	case errorLocationOutOfPickupArea
	case number9
	case helpNoParticipatingDealershipsInAreaDetail
	case popupAdvisorDropoffSelfDrop

    var key : String {
        switch self {
            case .helpHowLuxebyVolvoWorks:
					return "helpHowLuxebyVolvoWorks"
			case .deliveryLocation:
					return "deliveryLocation"
			case .viewScheduleServiceStatusInfoScheduledPickup:
					return "viewScheduleServiceStatusInfoScheduledPickup"
			case .viewProfileContactHeader:
					return "viewProfileContactHeader"
			case .helpRequestingDataFromLuxebyVolvoDetail:
					return "helpRequestingDataFromLuxebyVolvoDetail"
			case .helpNoneOfTheAvailableTimesWorkForMeDetail:
					return "helpNoneOfTheAvailableTimesWorkForMeDetail"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .helpTroubleWithTheLuxebyVolvoApp:
					return "helpTroubleWithTheLuxebyVolvoApp"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .helpILostAnItem:
					return "helpILostAnItem"
			case .skip:
					return "skip"
			case .helpTermsOfServiceDetail:
					return "helpTermsOfServiceDetail"
			case .viewSettingsDistanceUnitHeader:
					return "viewSettingsDistanceUnitHeader"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .viewScheduleServiceVehicleServiceScheduled:
					return "viewScheduleServiceVehicleServiceScheduled"
			case .needALoaner:
					return "needALoaner"
			case .errorUpdatePhoneNumberAlreadyExist:
					return "errorUpdatePhoneNumberAlreadyExist"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
			case .number11:
					return "number11"
			case .mins:
					return "mins"
			case .helpPrivacyPolicyInformationDetail:
					return "helpPrivacyPolicyInformationDetail"
			case .popupSelectLocationCurrentLocation:
					return "popupSelectLocationCurrentLocation"
			case .viewVehicleAddModelHint:
					return "viewVehicleAddModelHint"
			case .popupSelectTimeSlotUnavailableCallDealershipNotAvailable:
					return "popupSelectTimeSlotUnavailableCallDealershipNotAvailable"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .number8:
					return "number8"
			case .updateNow:
					return "updateNow"
			case .underTheHood:
					return "underTheHood"
			case .confirm:
					return "confirm"
			case .pickup:
					return "pickup"
			case .popupSelectLocationPermissionNote:
					return "popupSelectLocationPermissionNote"
			case .number3:
					return "number3"
			case .helpICantUpdateMyPhoneDetail:
					return "helpICantUpdateMyPhoneDetail"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .yourAccount:
					return "yourAccount"
			case .viewEditTextInfoHintFirstName:
					return "viewEditTextInfoHintFirstName"
			case .refresh:
					return "refresh"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .popupSelectTimeSlotTimesLabelPickup:
					return "popupSelectTimeSlotTimesLabelPickup"
			case .viewScheduleServiceStatusCompleteInfo:
					return "viewScheduleServiceStatusCompleteInfo"
			case .viewScheduleServiceOptionInfoPickup:
					return "viewScheduleServiceOptionInfoPickup"
			case .cancelPickup:
					return "cancelPickup"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .appName:
					return "appName"
			case .permissionAllowNotificationMessage:
					return "permissionAllowNotificationMessage"
			case .popupAdvisorDropoffSelfPickup:
					return "popupAdvisorDropoffSelfPickup"
			case .permissionLocationTitle:
					return "permissionLocationTitle"
			case .helpNoneOfTheAvailableTimesWorkForMe:
					return "helpNoneOfTheAvailableTimesWorkForMe"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .viewScheduleServiceStatusComplete:
					return "viewScheduleServiceStatusComplete"
			case .viewSettingsDistanceUnitTitle:
					return "viewSettingsDistanceUnitTitle"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .popupSelectTimeSlotLabelDropoff:
					return "popupSelectTimeSlotLabelDropoff"
			case .viewScheduleServiceOptionPickup:
					return "viewScheduleServiceOptionPickup"
			case .completedService:
					return "completedService"
			case .number5:
					return "number5"
			case .confirmationCode:
					return "confirmationCode"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .helpTooFewLoanersAvailable:
					return "helpTooFewLoanersAvailable"
			case .popupSelectTimeSlotTimesLabelDropoff:
					return "popupSelectTimeSlotTimesLabelDropoff"
			case .helpMyVehicleWasDamaged:
					return "helpMyVehicleWasDamaged"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .viewScheduleServiceOptionDropoff:
					return "viewScheduleServiceOptionDropoff"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .signout:
					return "signout"
			case .viewScheduleServiceStatusTimeWindowEstimatedDelivery:
					return "viewScheduleServiceStatusTimeWindowEstimatedDelivery"
			case .notAvailable:
					return "notAvailable"
			case .imNotSure:
					return "imNotSure"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .viewScheduleServiceOptionPickupSelfDropPickup:
					return "viewScheduleServiceOptionPickupSelfDropPickup"
			case .helpNoParticipatingDealershipsInArea:
					return "helpNoParticipatingDealershipsInArea"
			case .map:
					return "map"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .later:
					return "later"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .popupDefaultCancelPickupMessage:
					return "popupDefaultCancelPickupMessage"
			case .popupRemoveVehicleMessage:
					return "popupRemoveVehicleMessage"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .permissionAllowNotificationTitle:
					return "permissionAllowNotificationTitle"
			case .showDetails:
					return "showDetails"
			case .viewSigninPasswordDescription:
					return "viewSigninPasswordDescription"
			case .notNow:
					return "notNow"
			case .helpTermsOfService:
					return "helpTermsOfService"
			case .resendCode:
					return "resendCode"
			case .iDontKnow:
					return "iDontKnow"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .viewProfileAccountPasswordHeader:
					return "viewProfileAccountPasswordHeader"
			case .vehicleMake:
					return "vehicleMake"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .number2:
					return "number2"
			case .viewScheduleServiceOptionNoteDropoff:
					return "viewScheduleServiceOptionNoteDropoff"
			case .viewEditTextTitlePassword:
					return "viewEditTextTitlePassword"
			case .newService:
					return "newService"
			case .viewScheduleService:
					return "viewScheduleService"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
			case .popupContactText:
					return "popupContactText"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .popupSelectDealershipLabel:
					return "popupSelectDealershipLabel"
			case .viewScheduleServiceTypeDetailNameLabelMilestone:
					return "viewScheduleServiceTypeDetailNameLabelMilestone"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .loading:
					return "loading"
			case .helpMyDriverWasUnprofessional:
					return "helpMyDriverWasUnprofessional"
			case .helpThereWasAnIssueWithMyLoanerVehicleDetail:
					return "helpThereWasAnIssueWithMyLoanerVehicleDetail"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .viewSigninNameLabel:
					return "viewSigninNameLabel"
			case .viewScheduleServiceStatusTimeWindowEstimatedPickup:
					return "viewScheduleServiceStatusTimeWindowEstimatedPickup"
			case .viewScheduleServiceStatusInServiceInfo:
					return "viewScheduleServiceStatusInServiceInfo"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .yourVolvo:
					return "yourVolvo"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .unknown:
					return "unknown"
			case .popupContactTitle:
					return "popupContactTitle"
			case .viewPhoneVerificationCodeHint:
					return "viewPhoneVerificationCodeHint"
			case .cancel:
					return "cancel"
			case .ok:
					return "ok"
			case .viewScheduleServiceScheduledLabel:
					return "viewScheduleServiceScheduledLabel"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .color:
					return "color"
			case .delete:
					return "delete"
			case .viewEditTextPhoneDescription:
					return "viewEditTextPhoneDescription"
			case .popupSelectTimeSlotLabelPickup:
					return "popupSelectTimeSlotLabelPickup"
			case .updateYourPassword:
					return "updateYourPassword"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .viewScheduleServiceTypeMilestoneDetailNameLabel:
					return "viewScheduleServiceTypeMilestoneDetailNameLabel"
			case .errorDuplicateRequest:
					return "errorDuplicateRequest"
			case .readMore:
					return "readMore"
			case .viewScheduleServiceStatusInfoNearBy:
					return "viewScheduleServiceStatusInfoNearBy"
			case .error:
					return "error"
			case .model:
					return "model"
			case .contact:
					return "contact"
			case .passwordRequirements:
					return "passwordRequirements"
			case .helpOther:
					return "helpOther"
			case .viewProfileLocationHeader:
					return "viewProfileLocationHeader"
			case .viewSettingsSoftwareLicencesHeader:
					return "viewSettingsSoftwareLicencesHeader"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .viewScheduleServiceStatusTimeDeliveryWindow:
					return "viewScheduleServiceStatusTimeDeliveryWindow"
			case .scheduleService:
					return "scheduleService"
			case .popupAdvisorPickupMessage:
					return "popupAdvisorPickupMessage"
			case .helpMyPickupDeliveryLocationWasWrong:
					return "helpMyPickupDeliveryLocationWasWrong"
			case .viewVehicleAddYearHint:
					return "viewVehicleAddYearHint"
			case .permissionNotificationMessage:
					return "permissionNotificationMessage"
			case .min:
					return "min"
			case .year:
					return "year"
			case .viewSignupPasswordRequireNumber:
					return "viewSignupPasswordRequireNumber"
			case .viewScheduleServiceStatusCompleteRate:
					return "viewScheduleServiceStatusCompleteRate"
			case .viewScheduleServiceTypeOtherDetailLabel:
					return "viewScheduleServiceTypeOtherDetailLabel"
			case .viewScheduleServiceStatusInfoArrived:
					return "viewScheduleServiceStatusInfoArrived"
			case .cancelDropoff:
					return "cancelDropoff"
			case .new:
					return "new"
			case .viewEditTextTitleFirstName:
					return "viewEditTextTitleFirstName"
			case .viewDatesLoanersOnly:
					return "viewDatesLoanersOnly"
			case .errorPasswordNotMatch:
					return "errorPasswordNotMatch"
			case .settings:
					return "settings"
			case .viewScheduleServiceTypeMilestone:
					return "viewScheduleServiceTypeMilestone"
			case .dealership:
					return "dealership"
			case .popupDefaultCancelDropoffMessage:
					return "popupDefaultCancelDropoffMessage"
			case .cancelDelivery:
					return "cancelDelivery"
			case .errorOops:
					return "errorOops"
			case .viewScheduleServiceStatusTimePickupWindow:
					return "viewScheduleServiceStatusTimePickupWindow"
			case .scheduledDelivery:
					return "scheduledDelivery"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .viewScheduleServiceStatusAtDealershipInfo:
					return "viewScheduleServiceStatusAtDealershipInfo"
			case .number6:
					return "number6"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .emailAddress:
					return "emailAddress"
			case .helpMyDriverDidntMatchThePicture:
					return "helpMyDriverDidntMatchThePicture"
			case .viewSigninEmailLabel:
					return "viewSigninEmailLabel"
			case .errorNoMatchingCustomer:
					return "errorNoMatchingCustomer"
			case .viewHelpOptionPp:
					return "viewHelpOptionPp"
			case .popupAdvisorDropoffMessage:
					return "popupAdvisorDropoffMessage"
			case .helpRequestingDataFromLuxebyVolvo:
					return "helpRequestingDataFromLuxebyVolvo"
			case .permissionAllowButtonTitle:
					return "permissionAllowButtonTitle"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .errorUnknown:
					return "errorUnknown"
			case .helpICantCancelMyPickupOrDelivery:
					return "helpICantCancelMyPickupOrDelivery"
			case .addNewLocation:
					return "addNewLocation"
			case .close:
					return "close"
			case .viewRatingRangeValueOne:
					return "viewRatingRangeValueOne"
			case .helpMyVehicleWasDamagedDetail:
					return "helpMyVehicleWasDamagedDetail"
			case .createPassword:
					return "createPassword"
			case .viewSignupContactLabel:
					return "viewSignupContactLabel"
			case .scheduleDelivery:
					return "scheduleDelivery"
			case .yourVolvos:
					return "yourVolvos"
			case .helpMyDriverWasLateDetail:
					return "helpMyDriverWasLateDetail"
			case .openSettings:
					return "openSettings"
			case .helpDeleteMyLuxebyVolvoAccount:
					return "helpDeleteMyLuxebyVolvoAccount"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .helpTheAppIsntWorkingCorrectlyDetail:
					return "helpTheAppIsntWorkingCorrectlyDetail"
			case .viewScheduleServiceTypeOtherDetailExtraTitle:
					return "viewScheduleServiceTypeOtherDetailExtraTitle"
			case .viewHelpOptionTos:
					return "viewHelpOptionTos"
			case .yes:
					return "yes"
			case .viewEditTextInfoHintPhoneNumber:
					return "viewEditTextInfoHintPhoneNumber"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .currentService:
					return "currentService"
			case .viewScheduleServiceOptionConfirmButtonPositiveDropoff:
					return "viewScheduleServiceOptionConfirmButtonPositiveDropoff"
			case .errorInvalidPhoneNumberFormatted:
					return "errorInvalidPhoneNumberFormatted"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .viewEditTextInfoHintLastName:
					return "viewEditTextInfoHintLastName"
			case .viewEditTextTitleEmail:
					return "viewEditTextTitleEmail"
			case .viewScheduleServiceStatusFeedback:
					return "viewScheduleServiceStatusFeedback"
			case .popupSelectLocationLabel:
					return "popupSelectLocationLabel"
			case .errorOnline:
					return "errorOnline"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .vehicleInterior:
					return "vehicleInterior"
			case .viewSettingsVolvoAddNewLabel:
					return "viewSettingsVolvoAddNewLabel"
			case .viewEditTextTitlePhoneNumber:
					return "viewEditTextTitlePhoneNumber"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .helpICouldntContactMyDriver:
					return "helpICouldntContactMyDriver"
			case .helpOtherDetail:
					return "helpOtherDetail"
			case .viewScheduleServiceStatusReminderPickup:
					return "viewScheduleServiceStatusReminderPickup"
			case .viewScheduleServiceStatusInfoEnRoute:
					return "viewScheduleServiceStatusInfoEnRoute"
			case .viewScheduleServiceOptionPickupSelfDeliveryDropoff:
					return "viewScheduleServiceOptionPickupSelfDeliveryDropoff"
			case .helpMyCurrentLocationIsntWorkingDetail:
					return "helpMyCurrentLocationIsntWorkingDetail"
			case .phoneNumber:
					return "phoneNumber"
			case .viewScheduleServiceStatusInfoScheduledDropoff:
					return "viewScheduleServiceStatusInfoScheduledDropoff"
			case .popupSelectLocationPermissionDenied:
					return "popupSelectLocationPermissionDenied"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .viewEmailBody:
					return "viewEmailBody"
			case .viewScheduleServiceTypeOtherDetail:
					return "viewScheduleServiceTypeOtherDetail"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .errorPhoneNumberNotInFile:
					return "errorPhoneNumberNotInFile"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .helpIMissedMyPickupDeliveryDetail:
					return "helpIMissedMyPickupDeliveryDetail"
			case .viewScheduleServiceStatusFeedbackCommentTitle:
					return "viewScheduleServiceStatusFeedbackCommentTitle"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .remove:
					return "remove"
			case .viewRatingRangeValueTen:
					return "viewRatingRangeValueTen"
			case .update:
					return "update"
			case .viewScheduleServiceOptionInfoDropoff:
					return "viewScheduleServiceOptionInfoDropoff"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .helpPushNotificationsArentWorkingDetail:
					return "helpPushNotificationsArentWorkingDetail"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .viewEditTextTitlePasswordNew:
					return "viewEditTextTitlePasswordNew"
			case .viewScheduleServiceTypeDetailNameLabelOther:
					return "viewScheduleServiceTypeDetailNameLabelOther"
			case .viewIntro:
					return "viewIntro"
			case .viewSigninPhoneLabel:
					return "viewSigninPhoneLabel"
			case .number1:
					return "number1"
			case .change:
					return "change"
			case .helpPushNotificationsArentWorking:
					return "helpPushNotificationsArentWorking"
			case .viewVehicleAddColorHint:
					return "viewVehicleAddColorHint"
			case .helpMyDriverWasUnprofessionalDetail:
					return "helpMyDriverWasUnprofessionalDetail"
			case .helpThereWasAnIssueWithMyLoanerVehicle:
					return "helpThereWasAnIssueWithMyLoanerVehicle"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .viewScheduleServiceDetailConfirmService:
					return "viewScheduleServiceDetailConfirmService"
			case .errorInvalidCharacter:
					return "errorInvalidCharacter"
			case .popupAddNewLocationEditHint:
					return "popupAddNewLocationEditHint"
			case .volvoYearModel:
					return "volvoYearModel"
			case .viewScheduleServiceOptionInfoSelfDropoff:
					return "viewScheduleServiceOptionInfoSelfDropoff"
			case .viewTosContent:
					return "viewTosContent"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .viewSettingsSoftwareLicencesTitle:
					return "viewSettingsSoftwareLicencesTitle"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .viewScheduleServiceStatusFeedbackCommentHint:
					return "viewScheduleServiceStatusFeedbackCommentHint"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .no:
					return "no"
			case .viewSignupNameLabel:
					return "viewSignupNameLabel"
			case .viewVehicleAddLabel:
					return "viewVehicleAddLabel"
			case .helpSomethingUnsafeHappened:
					return "helpSomethingUnsafeHappened"
			case .helpSomethingUnsafeHappenedDetail:
					return "helpSomethingUnsafeHappenedDetail"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .viewEditTextInfoHintPasswordConfirm:
					return "viewEditTextInfoHintPasswordConfirm"
			case .helpICouldntContactMyDriverDetail:
					return "helpICouldntContactMyDriverDetail"
			case .errorDatabase:
					return "errorDatabase"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .helpMyPickupDeliveryLocationWasWrongDetail:
					return "helpMyPickupDeliveryLocationWasWrongDetail"
			case .viewSignupPasswordRequireLetter:
					return "viewSignupPasswordRequireLetter"
			case .viewHelpOptionTitle:
					return "viewHelpOptionTitle"
			case .helpTooFewLoanersAvailableDetail:
					return "helpTooFewLoanersAvailableDetail"
			case .viewSigninPhoneContactChangeLabel:
					return "viewSigninPhoneContactChangeLabel"
			case .errorOffline:
					return "errorOffline"
			case .viewSignupPasswordDescription:
					return "viewSignupPasswordDescription"
			case .helpDeleteMyLuxebyVolvoAccountDetail:
					return "helpDeleteMyLuxebyVolvoAccountDetail"
			case .popupSelectTimeSlotTimesLabelDelivery:
					return "popupSelectTimeSlotTimesLabelDelivery"
			case .requestReset:
					return "requestReset"
			case .viewSignupPasswordLabel:
					return "viewSignupPasswordLabel"
			case .edit:
					return "edit"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .helpMyCurrentLocationIsntWorking:
					return "helpMyCurrentLocationIsntWorking"
			case .password:
					return "password"
			case .back:
					return "back"
			case .helpICantArrangeServiceDetail:
					return "helpICantArrangeServiceDetail"
			case .schedulePickup:
					return "schedulePickup"
			case .vehicleExterior:
					return "vehicleExterior"
			case .viewScheduledSelfDrop:
					return "viewScheduledSelfDrop"
			case .viewScheduleServiceOptionInfoSelfPickup:
					return "viewScheduleServiceOptionInfoSelfPickup"
			case .helpICantCancelMyPickupOrDeliveryDetail:
					return "helpICantCancelMyPickupOrDeliveryDetail"
			case .yourLastDelivery:
					return "yourLastDelivery"
			case .viewScheduleServiceStatusFeedbackCommentLabel:
					return "viewScheduleServiceStatusFeedbackCommentLabel"
			case .retry:
					return "retry"
			case .helpThereWasAnIssueWithMyPaperworkDetail:
					return "helpThereWasAnIssueWithMyPaperworkDetail"
			case .helpMyDriverWasLate:
					return "helpMyDriverWasLate"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .viewScheduleServiceTypeOther:
					return "viewScheduleServiceTypeOther"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .helpIMissedMyPickupDelivery:
					return "helpIMissedMyPickupDelivery"
			case .popupSelectTimeSlotUnavailableLabel:
					return "popupSelectTimeSlotUnavailableLabel"
			case .viewDealershipCloseToLocation:
					return "viewDealershipCloseToLocation"
			case .popupAdvisorDropoffSelfPickupDescription:
					return "popupAdvisorDropoffSelfPickupDescription"
			case .viewScheduleServiceTypeDescription:
					return "viewScheduleServiceTypeDescription"
			case .errorPhoneNumberAlreadyExist:
					return "errorPhoneNumberAlreadyExist"
			case .viewSigninPasswordLabel:
					return "viewSigninPasswordLabel"
			case .viewScheduleServiceTypeOtherLabel:
					return "viewScheduleServiceTypeOtherLabel"
			case .popupAdvisorDropoffLabel:
					return "popupAdvisorDropoffLabel"
			case .changePhoneNumber:
					return "changePhoneNumber"
			case .viewEditTextInfoHintEmail:
					return "viewEditTextInfoHintEmail"
			case .removeVehicle:
					return "removeVehicle"
			case .selectedService:
					return "selectedService"
			case .helpILostAnItemDetail:
					return "helpILostAnItemDetail"
			case .permissionGrantTitle:
					return "permissionGrantTitle"
			case .number4:
					return "number4"
			case .viewScheduleServiceTypeOtherDetailExtraLabel:
					return "viewScheduleServiceTypeOtherDetailExtraLabel"
			case .next:
					return "next"
			case .popupSelectTimeSlotLabelDelivery:
					return "popupSelectTimeSlotLabelDelivery"
			case .helpICantArrangeService:
					return "helpICantArrangeService"
			case .viewScheduleServiceTypeOtherSubLabel:
					return "viewScheduleServiceTypeOtherSubLabel"
			case .popupAdvisorDropoffRescheduleDescription:
					return "popupAdvisorDropoffRescheduleDescription"
			case .help:
					return "help"
			case .dismiss:
					return "dismiss"
			case .done:
					return "done"
			case .helpPrivacyPolicyInformation:
					return "helpPrivacyPolicyInformation"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .viewScheduleServiceStatusCompleteTitle:
					return "viewScheduleServiceStatusCompleteTitle"
			case .helpMyDriverDidntMatchThePictureDetail:
					return "helpMyDriverDidntMatchThePictureDetail"
			case .scheduledPickup:
					return "scheduledPickup"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .viewScheduleServiceTypeOtherDetailExtraHint:
					return "viewScheduleServiceTypeOtherDetailExtraHint"
			case .yourLastPickup:
					return "yourLastPickup"
			case .helpTheAppIsntWorkingCorrectly:
					return "helpTheAppIsntWorkingCorrectly"
			case .delivery:
					return "delivery"
			case .helpIForgotMyPasswordDetail:
					return "helpIForgotMyPasswordDetail"
			case .viewScheduleServiceOptionNotePickup:
					return "viewScheduleServiceOptionNotePickup"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .number10:
					return "number10"
			case .currentPassword:
					return "currentPassword"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .popupRemoveAddressMessage:
					return "popupRemoveAddressMessage"
			case .pickupLocation:
					return "pickupLocation"
			case .viewScheduleServiceOptionConfirmButtonPositivePickup:
					return "viewScheduleServiceOptionConfirmButtonPositivePickup"
			case .recommendedService:
					return "recommendedService"
			case .popupAdvisorDropoffReschedule:
					return "popupAdvisorDropoffReschedule"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .number7:
					return "number7"
			case .viewEditTextTitleLastName:
					return "viewEditTextTitleLastName"
			case .npsExtremelyLikely:
					return "npsExtremelyLikely"
			case .errorEmailAlreadyExist:
					return "errorEmailAlreadyExist"
			case .helpThereWasAnIssueWithMyPaperwork:
					return "helpThereWasAnIssueWithMyPaperwork"
			case .errorDeleteVehicleBooking:
					return "errorDeleteVehicleBooking"
			case .popupContactCall:
					return "popupContactCall"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .helpAppOtherDetail:
					return "helpAppOtherDetail"
			case .add:
					return "add"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .npsNotLikely:
					return "npsNotLikely"
			case .viewEditTextTitlePasswordConfirm:
					return "viewEditTextTitlePasswordConfirm"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .number9:
					return "number9"
			case .helpNoParticipatingDealershipsInAreaDetail:
					return "helpNoParticipatingDealershipsInAreaDetail"
			case .popupAdvisorDropoffSelfDrop:
					return "popupAdvisorDropoffSelfDrop"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
