//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Localized.loadError
 Localized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case viewScheduleServiceTypeOtherDetailLabel
	case helpIForgotMyPassword
	case viewScheduleServiceStatusFeedbackCommentHint
	case helpMyPickupDeliveryLocationWasWrongDetail
	case popupAddNewLocationEditHint
	case viewScheduleServiceTypeOtherUnknown
	case errorInvalidLastName
	case delivery
	case viewScheduleServiceStatusTimeDeliveryWindow
	case viewEditTextTitlePasswordNew
	case errorAmbiguousVehicleUpsert
	case popupPhoneVerificationResendCodeTitle
	case helpOtherDetail
	case popupSignoutConfirmationMessage
	case permissionLocationTitle
	case viewSettingsDistanceUnitHeader
	case helpMyVehicleWasDamaged
	case viewScheduleServiceTypeOtherDetailExtraHint
	case unknown
	case permissionsLocationDeniedMessage
	case settings
	case viewScheduleServiceOptionInfoDropoff
	case refresh
	case viewScheduleServiceOptionPickup
	case updateNow
	case helpTermsOfService
	case errorOnline
	case helpNoneOfTheAvailableTimesWorkForMeDetail
	case viewSigninPasswordLabel
	case passwordRequirements
	case permissionAllowNotificationTitle
	case requestReset
	case notNow
	case viewVehicleAddLabel
	case viewSigninEmailLabel
	case viewSignupPasswordRequireNumber
	case popupSelectTimeSlotUnavailableCallDealership
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case viewHelpOptionDetailCallVolvo
	case viewHelpOptionTos
	case viewEditTextTitleEmail
	case changePhoneNumber
	case skip
	case helpMyDriverDidntMatchThePictureDetail
	case viewScheduleServiceStatusTimeWindowEstimatedDelivery
	case viewScheduleServiceOptionNotePickup
	case viewScheduleServiceTypeMilestoneDetailNameLabel
	case no
	case errorForcedUpgradeMessage
	case viewScheduleServiceStatusFeedback
	case phoneNumberCannotBeEmpty
	case dismiss
	case errorInvalidPasswordConfirm
	case errorPasswordNotMatch
	case viewScheduleServiceTypeOtherDetailExtraTitle
	case helpTermsOfServiceDetail
	case viewScheduleServiceStatusTimePickupWindow
	case errorAmbiguousCustomerUpsert
	case viewTosContentPrivacyPolicyTitle
	case completedService
	case helpIMissedMyPickupDelivery
	case errorAccountAlreadyExists
	case viewScheduleServiceOptionDropoff
	case viewScheduleServiceStatusCompleteTitle
	case helpNoneOfTheAvailableTimesWorkForMe
	case helpTooFewLoanersAvailable
	case viewSoftwareLicences
	case popupAdvisorDropoffRescheduleDescription
	case viewEditTextTitleFirstName
	case change
	case vehicleExterior
	case viewScheduleServiceStatusAtDealershipInfo
	case remove
	case viewScheduleServiceStatusSelfDealershipNavigate
	case needALoaner
	case year
	case viewEmailIntentChooserTitle
	case popupSelectDealershipLabel
	case viewDealershipCloseToLocation
	case popupAdvisorDropoffSelfPickup
	case color
	case number4
	case helpMyDriverWasLate
	case helpICantUpdateMyPhone
	case viewEditTextPhoneDescription
	case helpMyDriverDidntMatchThePicture
	case viewScheduleServiceTypeOtherDetailExtraLabel
	case confirmPhoneNumber
	case helpICouldntContactMyDriver
	case popupSelectTimeSlotTimesLabelDropoff
	case delete
	case viewScheduleServiceTypeDescription
	case popupSelectTimeSlotLabelPickup
	case viewSigninPhoneContactChangeLabel
	case later
	case map
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case viewScheduleServiceTypeOtherSubLabel
	case errorDatabase
	case helpSomethingUnsafeHappened
	case helpMyVehicleWasDamagedDetail
	case permissionNotificationMessage
	case helpICantArrangeServiceDetail
	case popupSelectLocationPermissionNote
	case emailAddress
	case viewEditTextTitlePassword
	case popupContactText
	case viewHelpCategoryLastLeg
	case helpRequestingDataFromLuxebyVolvo
	case helpRequestingDataFromLuxebyVolvoDetail
	case helpDeleteMyLuxebyVolvoAccountDetail
	case errorLocationServiceNotOfferedInYourArea
	case viewEditTextTitleLastName
	case errorPhoneNumberAlreadyExist
	case resendCode
	case errorLocationOutOfPickupArea
	case popupSelectLocationLabel
	case viewIntroFooterSignup
	case popupSelectLocationCurrentLocation
	case viewScheduleServiceStatusReminderPickup
	case viewHelpOptionDetailEmailDealer
	case viewScheduleServiceTypeOtherDetail
	case helpHowLuxebyVolvoWorks
	case helpPushNotificationsArentWorkingDetail
	case phoneNumber
	case popupUpdatingLocation
	case viewScheduleServiceStatusInfoArrived
	case errorInvalidApplicationVersion
	case popupSelectTimeSlotUnavailableLabel
	case toastSettingsLocationDisabled
	case viewTosContentTermsOfServiceUrl
	case popupSelectTimeSlotTimesLabelDelivery
	case errorRemoveVehicleError
	case viewSigninNameLabel
	case helpPushNotificationsArentWorking
	case helpDeleteMyLuxebyVolvoAccount
	case errorInvalidEmail
	case viewScheduleServiceOptionNoteDropoff
	case helpNoParticipatingDealershipsInArea
	case errorForcedUpgradeTitle
	case popupRemoveVehicleMessage
	case errorUserDisabled
	case helpILostAnItemDetail
	case helpPrivacyPolicyInformationDetail
	case vehicleInterior
	case npsNotLikely
	case removeVehicle
	case imNotSure
	case viewRatingRangeValueTen
	case errorVerifyPhoneNumber
	case viewRatingRangeValueOne
	case errorInvalidFirstName
	case helpMyDriverWasUnprofessional
	case popupPhoneVerificationResendCodeMessage
	case viewScheduleServiceStatusInfoScheduledPickup
	case viewProfileLocationHeader
	case errorDeleteVehicleBooking
	case helpPrivacyPolicyInformation
	case ok
	case viewScheduleServiceStatusCompleteRate
	case scheduledDelivery
	case viewPhoneVerificationCodeHint
	case newService
	case errorInvalidVerificationCode
	case viewIntroFooterSignin
	case viewScheduleServiceTypeMilestone
	case errorInvalidUserDisabled
	case error
	case errorInvalidPassword
	case helpICantCancelMyPickupOrDeliveryDetail
	case update
	case viewEditTextInfoHintPhoneNumber
	case popupAdvisorDropoffMessage
	case viewScheduleServiceScheduledLabel
	case helpThereWasAnIssueWithMyLoanerVehicleDetail
	case number11
	case viewTosContentPrivacyPolicy
	case helpNoParticipatingDealershipsInAreaDetail
	case errorOffline
	case helpAppOtherDetail
	case errorPhoneNumberNotInFile
	case errorInvalidPhoneNumber
	case new
	case retry
	case loading
	case popupSelectTimeSlotTimesLabelPickup
	case currentService
	case helpICouldntContactMyDriverDetail
	case popupSelectTimeSlotLabelDropoff
	case createPassword
	case viewTosContentTermsOfService
	case viewHelpCategoryHowLuxeByVolvoWorks
	case popupAdvisorDropoffSelfDrop
	case popupAdvisorPickupMessage
	case number9
	case help
	case viewHelpOptionPp
	case helpIMissedMyPickupDeliveryDetail
	case viewSignupNameLabel
	case viewTosContentTermsOfServiceTitle
	case viewScheduleServiceTypeOtherLabel
	case errorLocationOutOfDropoffArea
	case helpOther
	case yourVolvo
	case viewScheduleServiceVehicleServiceScheduled
	case popupRemoveAddressMessage
	case popupContactTitle
	case yourAccount
	case helpTheAppIsntWorkingCorrectlyDetail
	case popupAdvisorDropoffLabel
	case edit
	case viewScheduleServiceStatusSelfAdvisorPickup
	case viewSettingsSoftwareLicencesHeader
	case scheduleService
	case number10
	case readMore
	case done
	case viewScheduleServiceOptionPickupSelfDropPickup
	case viewScheduleServiceTypeDetailNameLabelMilestone
	case cancelDelivery
	case showDetails
	case cancelPickup
	case vehicleMake
	case yourLastPickup
	case viewScheduleServiceOptionInfoPickup
	case errorNoMatchingCustomer
	case back
	case viewScheduleServiceTypeDetailNameLabelOther
	case popupAdvisorDropoffReschedule
	case errorInvalidCharacter
	case viewScheduleServiceOptionConfirmButtonPositivePickup
	case popupAdvisorDropoffSelfPickupDescription
	case notAvailable
	case viewScheduleServiceStatusFeedbackCommentLabel
	case viewScheduleServiceStatusInfoNearBy
	case password
	case yourLastDelivery
	case permissionGrantTitle
	case next
	case viewEditTextInfoHintFirstName
	case scheduleDelivery
	case viewEditTextTitlePhoneNumber
	case viewSettingsSoftwareLicencesTitle
	case errorRequestNotCancelable
	case number5
	case recommendedService
	case pickupLocation
	case viewSigninForgotPassword
	case viewPhoneVerificationLabel
	case schedulePickup
	case updateYourPassword
	case helpILostAnItem
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case contact
	case helpThereWasAnIssueWithMyPaperwork
	case popupSelectLocationPermissionDenied
	case viewProfileContactHeader
	case viewProfileAccountPasswordHeader
	case viewEditTextInfoHintLastName
	case errorIllegalRequestStateChange
	case permissionAllowButtonTitle
	case helpMyCurrentLocationIsntWorkingDetail
	case number3
	case viewEditTextInfoHintPasswordConfirm
	case scheduledPickup
	case model
	case viewScheduleServiceStatusFeedbackCommentTitle
	case helpTooFewLoanersAvailableDetail
	case viewSignupPasswordDescription
	case viewSettingsVolvoAddNewLabel
	case volvoYearModel
	case viewEmailBody
	case viewScheduleServiceOptionInfoSelfPickup
	case min
	case viewTosContent
	case viewSettingsDistanceUnitTitle
	case number2
	case errorInvalidCredentials
	case cancel
	case viewScheduleServiceStatusInServiceInfo
	case viewSignupContactLabel
	case errorDuplicateRequest
	case add
	case errorInvalidPhoneNumberFormatted
	case confirm
	case viewIntro
	case viewScheduleServiceStatusComplete
	case viewScheduleServiceTypeOther
	case errorSoftUpgradeTitle
	case helpMyDriverWasUnprofessionalDetail
	case viewEditTextInfoHintEmail
	case helpThereWasAnIssueWithMyLoanerVehicle
	case number6
	case viewSigninPasswordDescription
	case errorInvalidPhoneVerificationCode
	case errorInvalidPasswordUnauthorizedCharacters
	case yes
	case popupSoftUpgradeNegative
	case errorIllegalRequestTaskChange
	case viewSignupPasswordRequireLetter
	case cancelDropoff
	case viewSignupPasswordLabel
	case helpIForgotMyPasswordDetail
	case permissionAllowNotificationMessage
	case viewHelpOptionDetailEmailVolvo
	case viewVehicleAddYearHint
	case deliveryLocation
	case number1
	case viewEmailSubject
	case addNewLocation
	case helpMyCurrentLocationIsntWorking
	case selectedService
	case viewEditTextTitlePasswordConfirm
	case viewScheduleServiceStatusInfoEnRoute
	case viewScheduleServiceOptionPickupSelfDeliveryDropoff
	case popupSelectTimeSlotLabelDelivery
	case helpSomethingUnsafeHappenedDetail
	case helpMyPickupDeliveryLocationWasWrong
	case viewVehicleAddModelHint
	case viewTosContentPrivacyPolicyUrl
	case popupDefaultCancelPickupMessage
	case viewHelpOptionTitle
	case popupContactCall
	case iDontKnow
	case openSettings
	case popupSelectTimeSlotUnavailableCallDealershipNotAvailable
	case helpTroubleWithTheLuxebyVolvoApp
	case helpICantUpdateMyPhoneDetail
	case viewHelpOptionDetailCallDealer
	case errorEmailAlreadyExist
	case viewLogoTitle
	case errorUpdatePhoneNumberAlreadyExist
	case viewScheduleServiceStatusInfoScheduledDropoff
	case signout
	case popupAddNewLocationLabel
	case helpTheAppIsntWorkingCorrectly
	case viewScheduleServiceOptionConfirmButtonPositiveDropoff
	case viewVehicleAddColorHint
	case errorSoftUpgradeMessage
	case currentPassword
	case viewScheduledSelfDrop
	case close
	case pickup
	case helpMyDriverWasLateDetail
	case viewScheduleServiceDetailConfirmService
	case underTheHood
	case viewScheduleServiceStatusTimeWindowEstimatedPickup
	case viewDatesLoanersOnly
	case dealership
	case errorOops
	case permissionsLocationDeniedTitle
	case mins
	case viewScheduleServiceOptionInfoSelfDropoff
	case popupDefaultCancelDropoffMessage
	case confirmationCode
	case number7
	case errorPhoneNumberTaken
	case viewSigninPhoneLabel
	case viewScheduleService
	case errorUnknown
	case number8
	case appName
	case npsExtremelyLikely
	case helpThereWasAnIssueWithMyPaperworkDetail
	case phoneNumberAlreadyTaken
	case helpICantCancelMyPickupOrDelivery
	case errorLocationServiceUnavailable
	case viewScheduleServiceStatusCompleteInfo
	case helpICantArrangeService
	case yourVolvos
	case errorDuplicateLoanerVehicleBookingAssignment

    var key : String {
        switch self {
            case .viewScheduleServiceTypeOtherDetailLabel:
					return "viewScheduleServiceTypeOtherDetailLabel"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .viewScheduleServiceStatusFeedbackCommentHint:
					return "viewScheduleServiceStatusFeedbackCommentHint"
			case .helpMyPickupDeliveryLocationWasWrongDetail:
					return "helpMyPickupDeliveryLocationWasWrongDetail"
			case .popupAddNewLocationEditHint:
					return "popupAddNewLocationEditHint"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .delivery:
					return "delivery"
			case .viewScheduleServiceStatusTimeDeliveryWindow:
					return "viewScheduleServiceStatusTimeDeliveryWindow"
			case .viewEditTextTitlePasswordNew:
					return "viewEditTextTitlePasswordNew"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
			case .helpOtherDetail:
					return "helpOtherDetail"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .permissionLocationTitle:
					return "permissionLocationTitle"
			case .viewSettingsDistanceUnitHeader:
					return "viewSettingsDistanceUnitHeader"
			case .helpMyVehicleWasDamaged:
					return "helpMyVehicleWasDamaged"
			case .viewScheduleServiceTypeOtherDetailExtraHint:
					return "viewScheduleServiceTypeOtherDetailExtraHint"
			case .unknown:
					return "unknown"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .settings:
					return "settings"
			case .viewScheduleServiceOptionInfoDropoff:
					return "viewScheduleServiceOptionInfoDropoff"
			case .refresh:
					return "refresh"
			case .viewScheduleServiceOptionPickup:
					return "viewScheduleServiceOptionPickup"
			case .updateNow:
					return "updateNow"
			case .helpTermsOfService:
					return "helpTermsOfService"
			case .errorOnline:
					return "errorOnline"
			case .helpNoneOfTheAvailableTimesWorkForMeDetail:
					return "helpNoneOfTheAvailableTimesWorkForMeDetail"
			case .viewSigninPasswordLabel:
					return "viewSigninPasswordLabel"
			case .passwordRequirements:
					return "passwordRequirements"
			case .permissionAllowNotificationTitle:
					return "permissionAllowNotificationTitle"
			case .requestReset:
					return "requestReset"
			case .notNow:
					return "notNow"
			case .viewVehicleAddLabel:
					return "viewVehicleAddLabel"
			case .viewSigninEmailLabel:
					return "viewSigninEmailLabel"
			case .viewSignupPasswordRequireNumber:
					return "viewSignupPasswordRequireNumber"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .viewHelpOptionTos:
					return "viewHelpOptionTos"
			case .viewEditTextTitleEmail:
					return "viewEditTextTitleEmail"
			case .changePhoneNumber:
					return "changePhoneNumber"
			case .skip:
					return "skip"
			case .helpMyDriverDidntMatchThePictureDetail:
					return "helpMyDriverDidntMatchThePictureDetail"
			case .viewScheduleServiceStatusTimeWindowEstimatedDelivery:
					return "viewScheduleServiceStatusTimeWindowEstimatedDelivery"
			case .viewScheduleServiceOptionNotePickup:
					return "viewScheduleServiceOptionNotePickup"
			case .viewScheduleServiceTypeMilestoneDetailNameLabel:
					return "viewScheduleServiceTypeMilestoneDetailNameLabel"
			case .no:
					return "no"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .viewScheduleServiceStatusFeedback:
					return "viewScheduleServiceStatusFeedback"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .dismiss:
					return "dismiss"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .errorPasswordNotMatch:
					return "errorPasswordNotMatch"
			case .viewScheduleServiceTypeOtherDetailExtraTitle:
					return "viewScheduleServiceTypeOtherDetailExtraTitle"
			case .helpTermsOfServiceDetail:
					return "helpTermsOfServiceDetail"
			case .viewScheduleServiceStatusTimePickupWindow:
					return "viewScheduleServiceStatusTimePickupWindow"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .completedService:
					return "completedService"
			case .helpIMissedMyPickupDelivery:
					return "helpIMissedMyPickupDelivery"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .viewScheduleServiceOptionDropoff:
					return "viewScheduleServiceOptionDropoff"
			case .viewScheduleServiceStatusCompleteTitle:
					return "viewScheduleServiceStatusCompleteTitle"
			case .helpNoneOfTheAvailableTimesWorkForMe:
					return "helpNoneOfTheAvailableTimesWorkForMe"
			case .helpTooFewLoanersAvailable:
					return "helpTooFewLoanersAvailable"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .popupAdvisorDropoffRescheduleDescription:
					return "popupAdvisorDropoffRescheduleDescription"
			case .viewEditTextTitleFirstName:
					return "viewEditTextTitleFirstName"
			case .change:
					return "change"
			case .vehicleExterior:
					return "vehicleExterior"
			case .viewScheduleServiceStatusAtDealershipInfo:
					return "viewScheduleServiceStatusAtDealershipInfo"
			case .remove:
					return "remove"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .needALoaner:
					return "needALoaner"
			case .year:
					return "year"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .popupSelectDealershipLabel:
					return "popupSelectDealershipLabel"
			case .viewDealershipCloseToLocation:
					return "viewDealershipCloseToLocation"
			case .popupAdvisorDropoffSelfPickup:
					return "popupAdvisorDropoffSelfPickup"
			case .color:
					return "color"
			case .number4:
					return "number4"
			case .helpMyDriverWasLate:
					return "helpMyDriverWasLate"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .viewEditTextPhoneDescription:
					return "viewEditTextPhoneDescription"
			case .helpMyDriverDidntMatchThePicture:
					return "helpMyDriverDidntMatchThePicture"
			case .viewScheduleServiceTypeOtherDetailExtraLabel:
					return "viewScheduleServiceTypeOtherDetailExtraLabel"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .helpICouldntContactMyDriver:
					return "helpICouldntContactMyDriver"
			case .popupSelectTimeSlotTimesLabelDropoff:
					return "popupSelectTimeSlotTimesLabelDropoff"
			case .delete:
					return "delete"
			case .viewScheduleServiceTypeDescription:
					return "viewScheduleServiceTypeDescription"
			case .popupSelectTimeSlotLabelPickup:
					return "popupSelectTimeSlotLabelPickup"
			case .viewSigninPhoneContactChangeLabel:
					return "viewSigninPhoneContactChangeLabel"
			case .later:
					return "later"
			case .map:
					return "map"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .viewScheduleServiceTypeOtherSubLabel:
					return "viewScheduleServiceTypeOtherSubLabel"
			case .errorDatabase:
					return "errorDatabase"
			case .helpSomethingUnsafeHappened:
					return "helpSomethingUnsafeHappened"
			case .helpMyVehicleWasDamagedDetail:
					return "helpMyVehicleWasDamagedDetail"
			case .permissionNotificationMessage:
					return "permissionNotificationMessage"
			case .helpICantArrangeServiceDetail:
					return "helpICantArrangeServiceDetail"
			case .popupSelectLocationPermissionNote:
					return "popupSelectLocationPermissionNote"
			case .emailAddress:
					return "emailAddress"
			case .viewEditTextTitlePassword:
					return "viewEditTextTitlePassword"
			case .popupContactText:
					return "popupContactText"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .helpRequestingDataFromLuxebyVolvo:
					return "helpRequestingDataFromLuxebyVolvo"
			case .helpRequestingDataFromLuxebyVolvoDetail:
					return "helpRequestingDataFromLuxebyVolvoDetail"
			case .helpDeleteMyLuxebyVolvoAccountDetail:
					return "helpDeleteMyLuxebyVolvoAccountDetail"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .viewEditTextTitleLastName:
					return "viewEditTextTitleLastName"
			case .errorPhoneNumberAlreadyExist:
					return "errorPhoneNumberAlreadyExist"
			case .resendCode:
					return "resendCode"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .popupSelectLocationLabel:
					return "popupSelectLocationLabel"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .popupSelectLocationCurrentLocation:
					return "popupSelectLocationCurrentLocation"
			case .viewScheduleServiceStatusReminderPickup:
					return "viewScheduleServiceStatusReminderPickup"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .viewScheduleServiceTypeOtherDetail:
					return "viewScheduleServiceTypeOtherDetail"
			case .helpHowLuxebyVolvoWorks:
					return "helpHowLuxebyVolvoWorks"
			case .helpPushNotificationsArentWorkingDetail:
					return "helpPushNotificationsArentWorkingDetail"
			case .phoneNumber:
					return "phoneNumber"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .viewScheduleServiceStatusInfoArrived:
					return "viewScheduleServiceStatusInfoArrived"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .popupSelectTimeSlotUnavailableLabel:
					return "popupSelectTimeSlotUnavailableLabel"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .popupSelectTimeSlotTimesLabelDelivery:
					return "popupSelectTimeSlotTimesLabelDelivery"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .viewSigninNameLabel:
					return "viewSigninNameLabel"
			case .helpPushNotificationsArentWorking:
					return "helpPushNotificationsArentWorking"
			case .helpDeleteMyLuxebyVolvoAccount:
					return "helpDeleteMyLuxebyVolvoAccount"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .viewScheduleServiceOptionNoteDropoff:
					return "viewScheduleServiceOptionNoteDropoff"
			case .helpNoParticipatingDealershipsInArea:
					return "helpNoParticipatingDealershipsInArea"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .popupRemoveVehicleMessage:
					return "popupRemoveVehicleMessage"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .helpILostAnItemDetail:
					return "helpILostAnItemDetail"
			case .helpPrivacyPolicyInformationDetail:
					return "helpPrivacyPolicyInformationDetail"
			case .vehicleInterior:
					return "vehicleInterior"
			case .npsNotLikely:
					return "npsNotLikely"
			case .removeVehicle:
					return "removeVehicle"
			case .imNotSure:
					return "imNotSure"
			case .viewRatingRangeValueTen:
					return "viewRatingRangeValueTen"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .viewRatingRangeValueOne:
					return "viewRatingRangeValueOne"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .helpMyDriverWasUnprofessional:
					return "helpMyDriverWasUnprofessional"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .viewScheduleServiceStatusInfoScheduledPickup:
					return "viewScheduleServiceStatusInfoScheduledPickup"
			case .viewProfileLocationHeader:
					return "viewProfileLocationHeader"
			case .errorDeleteVehicleBooking:
					return "errorDeleteVehicleBooking"
			case .helpPrivacyPolicyInformation:
					return "helpPrivacyPolicyInformation"
			case .ok:
					return "ok"
			case .viewScheduleServiceStatusCompleteRate:
					return "viewScheduleServiceStatusCompleteRate"
			case .scheduledDelivery:
					return "scheduledDelivery"
			case .viewPhoneVerificationCodeHint:
					return "viewPhoneVerificationCodeHint"
			case .newService:
					return "newService"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .viewScheduleServiceTypeMilestone:
					return "viewScheduleServiceTypeMilestone"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .error:
					return "error"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .helpICantCancelMyPickupOrDeliveryDetail:
					return "helpICantCancelMyPickupOrDeliveryDetail"
			case .update:
					return "update"
			case .viewEditTextInfoHintPhoneNumber:
					return "viewEditTextInfoHintPhoneNumber"
			case .popupAdvisorDropoffMessage:
					return "popupAdvisorDropoffMessage"
			case .viewScheduleServiceScheduledLabel:
					return "viewScheduleServiceScheduledLabel"
			case .helpThereWasAnIssueWithMyLoanerVehicleDetail:
					return "helpThereWasAnIssueWithMyLoanerVehicleDetail"
			case .number11:
					return "number11"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .helpNoParticipatingDealershipsInAreaDetail:
					return "helpNoParticipatingDealershipsInAreaDetail"
			case .errorOffline:
					return "errorOffline"
			case .helpAppOtherDetail:
					return "helpAppOtherDetail"
			case .errorPhoneNumberNotInFile:
					return "errorPhoneNumberNotInFile"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .new:
					return "new"
			case .retry:
					return "retry"
			case .loading:
					return "loading"
			case .popupSelectTimeSlotTimesLabelPickup:
					return "popupSelectTimeSlotTimesLabelPickup"
			case .currentService:
					return "currentService"
			case .helpICouldntContactMyDriverDetail:
					return "helpICouldntContactMyDriverDetail"
			case .popupSelectTimeSlotLabelDropoff:
					return "popupSelectTimeSlotLabelDropoff"
			case .createPassword:
					return "createPassword"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .popupAdvisorDropoffSelfDrop:
					return "popupAdvisorDropoffSelfDrop"
			case .popupAdvisorPickupMessage:
					return "popupAdvisorPickupMessage"
			case .number9:
					return "number9"
			case .help:
					return "help"
			case .viewHelpOptionPp:
					return "viewHelpOptionPp"
			case .helpIMissedMyPickupDeliveryDetail:
					return "helpIMissedMyPickupDeliveryDetail"
			case .viewSignupNameLabel:
					return "viewSignupNameLabel"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .viewScheduleServiceTypeOtherLabel:
					return "viewScheduleServiceTypeOtherLabel"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .helpOther:
					return "helpOther"
			case .yourVolvo:
					return "yourVolvo"
			case .viewScheduleServiceVehicleServiceScheduled:
					return "viewScheduleServiceVehicleServiceScheduled"
			case .popupRemoveAddressMessage:
					return "popupRemoveAddressMessage"
			case .popupContactTitle:
					return "popupContactTitle"
			case .yourAccount:
					return "yourAccount"
			case .helpTheAppIsntWorkingCorrectlyDetail:
					return "helpTheAppIsntWorkingCorrectlyDetail"
			case .popupAdvisorDropoffLabel:
					return "popupAdvisorDropoffLabel"
			case .edit:
					return "edit"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .viewSettingsSoftwareLicencesHeader:
					return "viewSettingsSoftwareLicencesHeader"
			case .scheduleService:
					return "scheduleService"
			case .number10:
					return "number10"
			case .readMore:
					return "readMore"
			case .done:
					return "done"
			case .viewScheduleServiceOptionPickupSelfDropPickup:
					return "viewScheduleServiceOptionPickupSelfDropPickup"
			case .viewScheduleServiceTypeDetailNameLabelMilestone:
					return "viewScheduleServiceTypeDetailNameLabelMilestone"
			case .cancelDelivery:
					return "cancelDelivery"
			case .showDetails:
					return "showDetails"
			case .cancelPickup:
					return "cancelPickup"
			case .vehicleMake:
					return "vehicleMake"
			case .yourLastPickup:
					return "yourLastPickup"
			case .viewScheduleServiceOptionInfoPickup:
					return "viewScheduleServiceOptionInfoPickup"
			case .errorNoMatchingCustomer:
					return "errorNoMatchingCustomer"
			case .back:
					return "back"
			case .viewScheduleServiceTypeDetailNameLabelOther:
					return "viewScheduleServiceTypeDetailNameLabelOther"
			case .popupAdvisorDropoffReschedule:
					return "popupAdvisorDropoffReschedule"
			case .errorInvalidCharacter:
					return "errorInvalidCharacter"
			case .viewScheduleServiceOptionConfirmButtonPositivePickup:
					return "viewScheduleServiceOptionConfirmButtonPositivePickup"
			case .popupAdvisorDropoffSelfPickupDescription:
					return "popupAdvisorDropoffSelfPickupDescription"
			case .notAvailable:
					return "notAvailable"
			case .viewScheduleServiceStatusFeedbackCommentLabel:
					return "viewScheduleServiceStatusFeedbackCommentLabel"
			case .viewScheduleServiceStatusInfoNearBy:
					return "viewScheduleServiceStatusInfoNearBy"
			case .password:
					return "password"
			case .yourLastDelivery:
					return "yourLastDelivery"
			case .permissionGrantTitle:
					return "permissionGrantTitle"
			case .next:
					return "next"
			case .viewEditTextInfoHintFirstName:
					return "viewEditTextInfoHintFirstName"
			case .scheduleDelivery:
					return "scheduleDelivery"
			case .viewEditTextTitlePhoneNumber:
					return "viewEditTextTitlePhoneNumber"
			case .viewSettingsSoftwareLicencesTitle:
					return "viewSettingsSoftwareLicencesTitle"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .number5:
					return "number5"
			case .recommendedService:
					return "recommendedService"
			case .pickupLocation:
					return "pickupLocation"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .schedulePickup:
					return "schedulePickup"
			case .updateYourPassword:
					return "updateYourPassword"
			case .helpILostAnItem:
					return "helpILostAnItem"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .contact:
					return "contact"
			case .helpThereWasAnIssueWithMyPaperwork:
					return "helpThereWasAnIssueWithMyPaperwork"
			case .popupSelectLocationPermissionDenied:
					return "popupSelectLocationPermissionDenied"
			case .viewProfileContactHeader:
					return "viewProfileContactHeader"
			case .viewProfileAccountPasswordHeader:
					return "viewProfileAccountPasswordHeader"
			case .viewEditTextInfoHintLastName:
					return "viewEditTextInfoHintLastName"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .permissionAllowButtonTitle:
					return "permissionAllowButtonTitle"
			case .helpMyCurrentLocationIsntWorkingDetail:
					return "helpMyCurrentLocationIsntWorkingDetail"
			case .number3:
					return "number3"
			case .viewEditTextInfoHintPasswordConfirm:
					return "viewEditTextInfoHintPasswordConfirm"
			case .scheduledPickup:
					return "scheduledPickup"
			case .model:
					return "model"
			case .viewScheduleServiceStatusFeedbackCommentTitle:
					return "viewScheduleServiceStatusFeedbackCommentTitle"
			case .helpTooFewLoanersAvailableDetail:
					return "helpTooFewLoanersAvailableDetail"
			case .viewSignupPasswordDescription:
					return "viewSignupPasswordDescription"
			case .viewSettingsVolvoAddNewLabel:
					return "viewSettingsVolvoAddNewLabel"
			case .volvoYearModel:
					return "volvoYearModel"
			case .viewEmailBody:
					return "viewEmailBody"
			case .viewScheduleServiceOptionInfoSelfPickup:
					return "viewScheduleServiceOptionInfoSelfPickup"
			case .min:
					return "min"
			case .viewTosContent:
					return "viewTosContent"
			case .viewSettingsDistanceUnitTitle:
					return "viewSettingsDistanceUnitTitle"
			case .number2:
					return "number2"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .cancel:
					return "cancel"
			case .viewScheduleServiceStatusInServiceInfo:
					return "viewScheduleServiceStatusInServiceInfo"
			case .viewSignupContactLabel:
					return "viewSignupContactLabel"
			case .errorDuplicateRequest:
					return "errorDuplicateRequest"
			case .add:
					return "add"
			case .errorInvalidPhoneNumberFormatted:
					return "errorInvalidPhoneNumberFormatted"
			case .confirm:
					return "confirm"
			case .viewIntro:
					return "viewIntro"
			case .viewScheduleServiceStatusComplete:
					return "viewScheduleServiceStatusComplete"
			case .viewScheduleServiceTypeOther:
					return "viewScheduleServiceTypeOther"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .helpMyDriverWasUnprofessionalDetail:
					return "helpMyDriverWasUnprofessionalDetail"
			case .viewEditTextInfoHintEmail:
					return "viewEditTextInfoHintEmail"
			case .helpThereWasAnIssueWithMyLoanerVehicle:
					return "helpThereWasAnIssueWithMyLoanerVehicle"
			case .number6:
					return "number6"
			case .viewSigninPasswordDescription:
					return "viewSigninPasswordDescription"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .yes:
					return "yes"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .viewSignupPasswordRequireLetter:
					return "viewSignupPasswordRequireLetter"
			case .cancelDropoff:
					return "cancelDropoff"
			case .viewSignupPasswordLabel:
					return "viewSignupPasswordLabel"
			case .helpIForgotMyPasswordDetail:
					return "helpIForgotMyPasswordDetail"
			case .permissionAllowNotificationMessage:
					return "permissionAllowNotificationMessage"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .viewVehicleAddYearHint:
					return "viewVehicleAddYearHint"
			case .deliveryLocation:
					return "deliveryLocation"
			case .number1:
					return "number1"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .addNewLocation:
					return "addNewLocation"
			case .helpMyCurrentLocationIsntWorking:
					return "helpMyCurrentLocationIsntWorking"
			case .selectedService:
					return "selectedService"
			case .viewEditTextTitlePasswordConfirm:
					return "viewEditTextTitlePasswordConfirm"
			case .viewScheduleServiceStatusInfoEnRoute:
					return "viewScheduleServiceStatusInfoEnRoute"
			case .viewScheduleServiceOptionPickupSelfDeliveryDropoff:
					return "viewScheduleServiceOptionPickupSelfDeliveryDropoff"
			case .popupSelectTimeSlotLabelDelivery:
					return "popupSelectTimeSlotLabelDelivery"
			case .helpSomethingUnsafeHappenedDetail:
					return "helpSomethingUnsafeHappenedDetail"
			case .helpMyPickupDeliveryLocationWasWrong:
					return "helpMyPickupDeliveryLocationWasWrong"
			case .viewVehicleAddModelHint:
					return "viewVehicleAddModelHint"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .popupDefaultCancelPickupMessage:
					return "popupDefaultCancelPickupMessage"
			case .viewHelpOptionTitle:
					return "viewHelpOptionTitle"
			case .popupContactCall:
					return "popupContactCall"
			case .iDontKnow:
					return "iDontKnow"
			case .openSettings:
					return "openSettings"
			case .popupSelectTimeSlotUnavailableCallDealershipNotAvailable:
					return "popupSelectTimeSlotUnavailableCallDealershipNotAvailable"
			case .helpTroubleWithTheLuxebyVolvoApp:
					return "helpTroubleWithTheLuxebyVolvoApp"
			case .helpICantUpdateMyPhoneDetail:
					return "helpICantUpdateMyPhoneDetail"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .errorEmailAlreadyExist:
					return "errorEmailAlreadyExist"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .errorUpdatePhoneNumberAlreadyExist:
					return "errorUpdatePhoneNumberAlreadyExist"
			case .viewScheduleServiceStatusInfoScheduledDropoff:
					return "viewScheduleServiceStatusInfoScheduledDropoff"
			case .signout:
					return "signout"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .helpTheAppIsntWorkingCorrectly:
					return "helpTheAppIsntWorkingCorrectly"
			case .viewScheduleServiceOptionConfirmButtonPositiveDropoff:
					return "viewScheduleServiceOptionConfirmButtonPositiveDropoff"
			case .viewVehicleAddColorHint:
					return "viewVehicleAddColorHint"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .currentPassword:
					return "currentPassword"
			case .viewScheduledSelfDrop:
					return "viewScheduledSelfDrop"
			case .close:
					return "close"
			case .pickup:
					return "pickup"
			case .helpMyDriverWasLateDetail:
					return "helpMyDriverWasLateDetail"
			case .viewScheduleServiceDetailConfirmService:
					return "viewScheduleServiceDetailConfirmService"
			case .underTheHood:
					return "underTheHood"
			case .viewScheduleServiceStatusTimeWindowEstimatedPickup:
					return "viewScheduleServiceStatusTimeWindowEstimatedPickup"
			case .viewDatesLoanersOnly:
					return "viewDatesLoanersOnly"
			case .dealership:
					return "dealership"
			case .errorOops:
					return "errorOops"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .mins:
					return "mins"
			case .viewScheduleServiceOptionInfoSelfDropoff:
					return "viewScheduleServiceOptionInfoSelfDropoff"
			case .popupDefaultCancelDropoffMessage:
					return "popupDefaultCancelDropoffMessage"
			case .confirmationCode:
					return "confirmationCode"
			case .number7:
					return "number7"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .viewSigninPhoneLabel:
					return "viewSigninPhoneLabel"
			case .viewScheduleService:
					return "viewScheduleService"
			case .errorUnknown:
					return "errorUnknown"
			case .number8:
					return "number8"
			case .appName:
					return "appName"
			case .npsExtremelyLikely:
					return "npsExtremelyLikely"
			case .helpThereWasAnIssueWithMyPaperworkDetail:
					return "helpThereWasAnIssueWithMyPaperworkDetail"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .helpICantCancelMyPickupOrDelivery:
					return "helpICantCancelMyPickupOrDelivery"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .viewScheduleServiceStatusCompleteInfo:
					return "viewScheduleServiceStatusCompleteInfo"
			case .helpICantArrangeService:
					return "helpICantArrangeService"
			case .yourVolvos:
					return "yourVolvos"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
