//
//  LocalizedTemplate.swift
//  voluxe-customer
//
//  Created by Johan Giroux on 1/30/19.
//  Copyright © 2019 Luxe - Volvo Cars. All rights reserved.
//

import Foundation

/**
 Usage:
 Localized.loadError
 Localized.welcomeMessage.with("Dan")
 */

enum Localized: CustomStringConvertible {
    
    class Bundles {
        static let framework = Bundle(for: Localized.Bundles.self)
    }
    
    case back
	case helpHowLuxebyVolvoWorks
	case viewHelpCategoryLastLeg
	case helpILostAnItemDetail
	case viewEditTextInfoHintEmail
	case viewScheduleServiceStatusCompleteRate
	case recommendedService
	case error
	case requestReset
	case viewPhoneVerificationCodeHint
	case viewSignupPasswordRequireLetter
	case retry
	case viewEditTextTitlePasswordNew
	case dismiss
	case errorDeleteVehicleBooking
	case cancelPickup
	case yourLastPickup
	case helpNoParticipatingDealershipsInAreaDetail
	case viewScheduleServiceStatusSelfFooterTitleDropoff
	case updateNow
	case viewVehicleAddColorHint
	case viewScheduleServiceOptionInfoDropoff
	case currentPassword
	case viewEditTextInfoHintFirstName
	case no
	case viewScheduleServiceOptionPickupSelfDropPickup
	case year
	case viewScheduleServiceStatusInfoScheduledPickup
	case resendCode
	case schedulePickup
	case viewScheduleServiceOptionInfoSelfDropoff
	case viewScheduleServiceStatusInfoArrived
	case phoneNumber
	case popupPhoneVerificationResendCodeTitle
	case password
	case loading
	case pickupLocation
	case viewTosContent
	case popupAddNewLocationLabel
	case viewSettingsDistanceUnitHeader
	case popupSignoutConfirmationMessage
	case viewSigninPasswordLabel
	case errorInvalidPhoneVerificationCode
	case new
	case popupAddNewLocationEditHint
	case helpIMissedMyPickupDelivery
	case viewEditTextInfoHintPasswordConfirm
	case viewScheduleServiceTypeDetailNameLabelOther
	case delete
	case viewScheduleServiceTypeMilestone
	case permissionGrantTitle
	case viewScheduleServiceTypeOther
	case viewScheduleServiceTypeOtherDetailLabel
	case scheduledPickup
	case viewHelpOptionDetailEmailVolvo
	case errorRequestNotCancelable
	case vehicleMake
	case popupAdvisorDropoffSelfDrop
	case errorIllegalRequestStateChange
	case viewSigninPhoneLabel
	case viewSettingsSoftwareLicencesHeader
	case helpMyCurrentLocationIsntWorkingDetail
	case viewScheduleServiceStatusFeedback
	case helpMyVehicleWasDamagedDetail
	case confirm
	case cancelDelivery
	case helpPrivacyPolicyInformationDetail
	case viewScheduleServiceOptionPickup
	case viewScheduleServiceTypeOtherDetailExtraLabel
	case viewEditTextPhoneDescription
	case viewRatingRangeValueOne
	case errorInvalidPasswordConfirm
	case showDetails
	case update
	case viewScheduleServiceOptionConfirmButtonPositivePickup
	case popupSelectTimeSlotTimesLabelDropoff
	case confirmationCode
	case errorOops
	case helpRequestingDataFromLuxebyVolvo
	case viewHelpOptionDetailEmailDealer
	case errorLocationOutOfPickupArea
	case number1
	case errorUnknown
	case yourVolvos
	case removeVehicle
	case viewScheduleServiceTypeMilestoneDetailNameLabel
	case popupSelectTimeSlotUnavailableCallDealership
	case viewIntro
	case errorSoftUpgradeTitle
	case iDontKnow
	case viewScheduleServiceStatusFeedbackCommentHint
	case errorInvalidEmail
	case popupContactTitle
	case errorUserDisabled
	case helpMyVehicleWasDamaged
	case openSettings
	case errorPasswordNotMatch
	case popupSelectTimeSlotTimesLabelPickup
	case confirmPhoneNumber
	case viewScheduleServiceStatusCompleteInfo
	case underTheHood
	case notAvailable
	case viewVehicleAddLabel
	case emailAddress
	case helpTooFewLoanersAvailable
	case viewScheduleServiceTypeOtherDetailExtraHint
	case popupAdvisorDropoffSelfPickup
	case helpThereWasAnIssueWithMyLoanerVehicle
	case helpMyDriverDidntMatchThePicture
	case errorOffline
	case yourAccount
	case helpTermsOfServiceDetail
	case settings
	case viewTosContentPrivacyPolicyUrl
	case viewScheduleServiceTypeOtherDetailExtraTitle
	case helpTooFewLoanersAvailableDetail
	case viewSignupNameLabel
	case helpNoneOfTheAvailableTimesWorkForMeDetail
	case helpAppOtherDetail
	case popupUpdatingLocation
	case viewTosContentTermsOfServiceTitle
	case viewEditTextTitlePhoneNumber
	case popupContactCall
	case viewLogoTitle
	case viewScheduleServiceOptionNoteDropoff
	case viewScheduleServiceStatusTimePickupWindow
	case appName
	case viewEmailSubject
	case helpICantArrangeService
	case add
	case helpTroubleWithTheLuxebyVolvoApp
	case viewSigninEmailLabel
	case helpICantCancelMyPickupOrDeliveryDetail
	case currentService
	case popupPhoneVerificationResendCodeMessage
	case viewEditTextTitleLastName
	case popupSelectTimeSlotTimesLabelDelivery
	case newService
	case viewSigninPhoneContactChangeLabel
	case viewSigninPasswordDescription
	case errorNoMatchingCustomer
	case popupAdvisorPickupMessage
	case errorOnline
	case viewSettingsDistanceUnitTitle
	case color
	case contact
	case errorInvalidApplicationVersion
	case viewScheduleServiceOptionConfirmButtonPositiveDropoff
	case errorEmailAlreadyExist
	case errorDuplicateLoanerVehicleBookingAssignment
	case errorIllegalRequestTaskChange
	case helpThereWasAnIssueWithMyPaperwork
	case helpMyDriverWasUnprofessional
	case permissionLocationTitle
	case cancelDropoff
	case viewVehicleAddYearHint
	case viewHelpOptionPp
	case permissionNotificationMessage
	case scheduledDelivery
	case viewScheduleServiceVehicleServiceScheduled
	case signout
	case viewScheduleServiceOptionDropoff
	case helpNoParticipatingDealershipsInArea
	case viewHelpOptionDetailCallDealer
	case permissionAllowNotificationTitle
	case close
	case errorPhoneNumberNotInFile
	case scheduleService
	case permissionAllowNotificationMessage
	case viewHelpOptionTitle
	case helpSomethingUnsafeHappenedDetail
	case viewScheduleServiceStatusSelfAdvisorPickup
	case popupSelectLocationPermissionDenied
	case createPassword
	case permissionsLocationDeniedMessage
	case help
	case yourLastDelivery
	case viewProfileContactHeader
	case errorAmbiguousVehicleUpsert
	case number11
	case vehicleInterior
	case viewDatesLoanersOnly
	case viewDealershipCloseToLocation
	case helpThereWasAnIssueWithMyLoanerVehicleDetail
	case viewSignupPasswordRequireNumber
	case helpMyDriverWasLate
	case viewSoftwareLicences
	case popupRemoveAddressMessage
	case cancel
	case helpICouldntContactMyDriverDetail
	case popupDefaultCancelDropoffMessage
	case viewEditTextTitleEmail
	case viewScheduleServiceStatusInfoScheduledDropoff
	case readMore
	case yes
	case viewEditTextInfoHintPhoneNumber
	case helpTermsOfService
	case completedService
	case viewSignupPasswordLabel
	case viewScheduleServiceStatusSelfDealershipNavigate
	case deliveryLocation
	case popupAdvisorDropoffSelfPickupDescription
	case helpNoneOfTheAvailableTimesWorkForMe
	case errorForcedUpgradeMessage
	case viewEmailIntentChooserTitle
	case viewScheduleService
	case helpILostAnItem
	case ok
	case helpICantArrangeServiceDetail
	case viewScheduleServiceOptionInfoPickup
	case viewHelpOptionTos
	case number8
	case popupSelectTimeSlotLabelDropoff
	case phoneNumberAlreadyTaken
	case refresh
	case viewPhoneVerificationLabel
	case popupSelectTimeSlotLabelDelivery
	case viewScheduleServiceStatusAtDealershipInfo
	case map
	case scheduleDelivery
	case viewEditTextTitlePassword
	case viewEditTextTitlePasswordConfirm
	case viewScheduleServiceStatusFeedbackCommentTitle
	case min
	case viewScheduleServiceDetailConfirmService
	case errorAccountAlreadyExists
	case popupSoftUpgradeNegative
	case viewScheduleServiceTypeOtherLabel
	case updateYourPassword
	case number9
	case helpSomethingUnsafeHappened
	case viewHelpCategoryHowLuxeByVolvoWorks
	case viewScheduleServiceStatusComplete
	case popupSelectDealershipLabel
	case errorInvalidCredentials
	case helpICantCancelMyPickupOrDelivery
	case errorInvalidPhoneNumber
	case errorInvalidPhoneNumberFormatted
	case helpIForgotMyPasswordDetail
	case viewSignupContactLabel
	case helpPushNotificationsArentWorking
	case viewTosContentPrivacyPolicyTitle
	case viewScheduleServiceTypeDescription
	case viewScheduleServiceOptionInfoSelfPickup
	case helpMyPickupDeliveryLocationWasWrongDetail
	case viewRatingRangeValueTen
	case popupSelectTimeSlotUnavailableLabel
	case popupAdvisorDropoffReschedule
	case viewScheduleServiceStatusInServiceInfo
	case errorInvalidFirstName
	case pickup
	case popupAdvisorDropoffMessage
	case number7
	case popupSelectTimeSlotUnavailableCallDealershipNotAvailable
	case next
	case viewScheduleServiceTypeDetailNameLabelMilestone
	case helpIMissedMyPickupDeliveryDetail
	case viewEditTextTitleFirstName
	case popupRemoveVehicleMessage
	case remove
	case change
	case errorInvalidLastName
	case permissionsLocationDeniedTitle
	case viewScheduleServiceScheduledLabel
	case helpDeleteMyLuxebyVolvoAccount
	case edit
	case popupSelectLocationPermissionNote
	case viewScheduleServiceStatusReminderPickup
	case errorAmbiguousCustomerUpsert
	case viewScheduleServiceStatusFeedbackCommentLabel
	case errorLocationServiceNotOfferedInYourArea
	case helpPushNotificationsArentWorkingDetail
	case errorInvalidVerificationCode
	case errorSoftUpgradeMessage
	case viewScheduleServiceStatusCompleteTitle
	case viewScheduledSelfDrop
	case viewSignupPasswordDescription
	case viewScheduleServiceStatusInfoNearBy
	case vehicleExterior
	case number3
	case notNow
	case helpMyPickupDeliveryLocationWasWrong
	case errorPhoneNumberAlreadyExist
	case dealership
	case helpICantUpdateMyPhone
	case viewScheduleServiceStatusTimeWindowEstimatedDelivery
	case mins
	case number2
	case errorDuplicateRequest
	case viewScheduleServiceTypeOtherSubLabel
	case viewHelpOptionDetailCallVolvo
	case errorInvalidUserDisabled
	case popupSelectLocationCurrentLocation
	case done
	case later
	case viewSettingsSoftwareLicencesTitle
	case unknown
	case helpMyDriverWasUnprofessionalDetail
	case popupContactText
	case popupSelectLocationLabel
	case errorUpdatePhoneNumberAlreadyExist
	case helpMyDriverWasLateDetail
	case viewIntroFooterSignup
	case helpTheAppIsntWorkingCorrectlyDetail
	case popupAdvisorDropoffLabel
	case viewScheduleServiceOptionNotePickup
	case helpMyDriverDidntMatchThePictureDetail
	case skip
	case viewSigninNameLabel
	case popupDefaultCancelPickupMessage
	case helpMyCurrentLocationIsntWorking
	case errorForcedUpgradeTitle
	case errorLocationOutOfDropoffArea
	case viewEditTextInfoHintLastName
	case selectedService
	case viewSigninForgotPassword
	case errorRemoveVehicleError
	case helpOther
	case volvoYearModel
	case viewScheduleServiceStatusSelfAdvisorDropoff
	case number5
	case popupAdvisorDropoffRescheduleDescription
	case errorInvalidPassword
	case helpThereWasAnIssueWithMyPaperworkDetail
	case errorVerifyPhoneNumber
	case viewProfileLocationHeader
	case viewScheduleServiceOptionPickupSelfDeliveryDropoff
	case toastSettingsLocationDisabled
	case helpTheAppIsntWorkingCorrectly
	case viewScheduleServiceStatusTimeDeliveryWindow
	case viewScheduleServiceStatusInfoEnRoute
	case helpOtherDetail
	case changePhoneNumber
	case permissionAllowButtonTitle
	case viewSettingsVolvoAddNewLabel
	case viewTosContentPrivacyPolicy
	case yourVolvo
	case phoneNumberCannotBeEmpty
	case number6
	case viewVehicleAddModelHint
	case model
	case popupSelectTimeSlotLabelPickup
	case viewScheduleServiceTypeOtherUnknown
	case helpICantUpdateMyPhoneDetail
	case number10
	case helpDeleteMyLuxebyVolvoAccountDetail
	case viewProfileAccountPasswordHeader
	case needALoaner
	case helpPrivacyPolicyInformation
	case addNewLocation
	case imNotSure
	case viewScheduleServiceTypeOtherDetail
	case errorLocationServiceUnavailable
	case viewTosContentTermsOfServiceUrl
	case errorInvalidCharacter
	case errorDatabase
	case delivery
	case helpICouldntContactMyDriver
	case helpIForgotMyPassword
	case viewHelpCategoryTroubleWithLuxeByVolvoApp
	case viewIntroFooterSignin
	case viewEmailBody
	case viewTosContentTermsOfService
	case helpRequestingDataFromLuxebyVolvoDetail
	case number4
	case passwordRequirements
	case errorInvalidPasswordUnauthorizedCharacters
	case errorPhoneNumberTaken
	case viewScheduleServiceStatusTimeWindowEstimatedPickup

    var key : String {
        switch self {
            case .back:
					return "back"
			case .helpHowLuxebyVolvoWorks:
					return "helpHowLuxebyVolvoWorks"
			case .viewHelpCategoryLastLeg:
					return "viewHelpCategoryLastLeg"
			case .helpILostAnItemDetail:
					return "helpILostAnItemDetail"
			case .viewEditTextInfoHintEmail:
					return "viewEditTextInfoHintEmail"
			case .viewScheduleServiceStatusCompleteRate:
					return "viewScheduleServiceStatusCompleteRate"
			case .recommendedService:
					return "recommendedService"
			case .error:
					return "error"
			case .requestReset:
					return "requestReset"
			case .viewPhoneVerificationCodeHint:
					return "viewPhoneVerificationCodeHint"
			case .viewSignupPasswordRequireLetter:
					return "viewSignupPasswordRequireLetter"
			case .retry:
					return "retry"
			case .viewEditTextTitlePasswordNew:
					return "viewEditTextTitlePasswordNew"
			case .dismiss:
					return "dismiss"
			case .errorDeleteVehicleBooking:
					return "errorDeleteVehicleBooking"
			case .cancelPickup:
					return "cancelPickup"
			case .yourLastPickup:
					return "yourLastPickup"
			case .helpNoParticipatingDealershipsInAreaDetail:
					return "helpNoParticipatingDealershipsInAreaDetail"
			case .viewScheduleServiceStatusSelfFooterTitleDropoff:
					return "viewScheduleServiceStatusSelfFooterTitleDropoff"
			case .updateNow:
					return "updateNow"
			case .viewVehicleAddColorHint:
					return "viewVehicleAddColorHint"
			case .viewScheduleServiceOptionInfoDropoff:
					return "viewScheduleServiceOptionInfoDropoff"
			case .currentPassword:
					return "currentPassword"
			case .viewEditTextInfoHintFirstName:
					return "viewEditTextInfoHintFirstName"
			case .no:
					return "no"
			case .viewScheduleServiceOptionPickupSelfDropPickup:
					return "viewScheduleServiceOptionPickupSelfDropPickup"
			case .year:
					return "year"
			case .viewScheduleServiceStatusInfoScheduledPickup:
					return "viewScheduleServiceStatusInfoScheduledPickup"
			case .resendCode:
					return "resendCode"
			case .schedulePickup:
					return "schedulePickup"
			case .viewScheduleServiceOptionInfoSelfDropoff:
					return "viewScheduleServiceOptionInfoSelfDropoff"
			case .viewScheduleServiceStatusInfoArrived:
					return "viewScheduleServiceStatusInfoArrived"
			case .phoneNumber:
					return "phoneNumber"
			case .popupPhoneVerificationResendCodeTitle:
					return "popupPhoneVerificationResendCodeTitle"
			case .password:
					return "password"
			case .loading:
					return "loading"
			case .pickupLocation:
					return "pickupLocation"
			case .viewTosContent:
					return "viewTosContent"
			case .popupAddNewLocationLabel:
					return "popupAddNewLocationLabel"
			case .viewSettingsDistanceUnitHeader:
					return "viewSettingsDistanceUnitHeader"
			case .popupSignoutConfirmationMessage:
					return "popupSignoutConfirmationMessage"
			case .viewSigninPasswordLabel:
					return "viewSigninPasswordLabel"
			case .errorInvalidPhoneVerificationCode:
					return "errorInvalidPhoneVerificationCode"
			case .new:
					return "new"
			case .popupAddNewLocationEditHint:
					return "popupAddNewLocationEditHint"
			case .helpIMissedMyPickupDelivery:
					return "helpIMissedMyPickupDelivery"
			case .viewEditTextInfoHintPasswordConfirm:
					return "viewEditTextInfoHintPasswordConfirm"
			case .viewScheduleServiceTypeDetailNameLabelOther:
					return "viewScheduleServiceTypeDetailNameLabelOther"
			case .delete:
					return "delete"
			case .viewScheduleServiceTypeMilestone:
					return "viewScheduleServiceTypeMilestone"
			case .permissionGrantTitle:
					return "permissionGrantTitle"
			case .viewScheduleServiceTypeOther:
					return "viewScheduleServiceTypeOther"
			case .viewScheduleServiceTypeOtherDetailLabel:
					return "viewScheduleServiceTypeOtherDetailLabel"
			case .scheduledPickup:
					return "scheduledPickup"
			case .viewHelpOptionDetailEmailVolvo:
					return "viewHelpOptionDetailEmailVolvo"
			case .errorRequestNotCancelable:
					return "errorRequestNotCancelable"
			case .vehicleMake:
					return "vehicleMake"
			case .popupAdvisorDropoffSelfDrop:
					return "popupAdvisorDropoffSelfDrop"
			case .errorIllegalRequestStateChange:
					return "errorIllegalRequestStateChange"
			case .viewSigninPhoneLabel:
					return "viewSigninPhoneLabel"
			case .viewSettingsSoftwareLicencesHeader:
					return "viewSettingsSoftwareLicencesHeader"
			case .helpMyCurrentLocationIsntWorkingDetail:
					return "helpMyCurrentLocationIsntWorkingDetail"
			case .viewScheduleServiceStatusFeedback:
					return "viewScheduleServiceStatusFeedback"
			case .helpMyVehicleWasDamagedDetail:
					return "helpMyVehicleWasDamagedDetail"
			case .confirm:
					return "confirm"
			case .cancelDelivery:
					return "cancelDelivery"
			case .helpPrivacyPolicyInformationDetail:
					return "helpPrivacyPolicyInformationDetail"
			case .viewScheduleServiceOptionPickup:
					return "viewScheduleServiceOptionPickup"
			case .viewScheduleServiceTypeOtherDetailExtraLabel:
					return "viewScheduleServiceTypeOtherDetailExtraLabel"
			case .viewEditTextPhoneDescription:
					return "viewEditTextPhoneDescription"
			case .viewRatingRangeValueOne:
					return "viewRatingRangeValueOne"
			case .errorInvalidPasswordConfirm:
					return "errorInvalidPasswordConfirm"
			case .showDetails:
					return "showDetails"
			case .update:
					return "update"
			case .viewScheduleServiceOptionConfirmButtonPositivePickup:
					return "viewScheduleServiceOptionConfirmButtonPositivePickup"
			case .popupSelectTimeSlotTimesLabelDropoff:
					return "popupSelectTimeSlotTimesLabelDropoff"
			case .confirmationCode:
					return "confirmationCode"
			case .errorOops:
					return "errorOops"
			case .helpRequestingDataFromLuxebyVolvo:
					return "helpRequestingDataFromLuxebyVolvo"
			case .viewHelpOptionDetailEmailDealer:
					return "viewHelpOptionDetailEmailDealer"
			case .errorLocationOutOfPickupArea:
					return "errorLocationOutOfPickupArea"
			case .number1:
					return "number1"
			case .errorUnknown:
					return "errorUnknown"
			case .yourVolvos:
					return "yourVolvos"
			case .removeVehicle:
					return "removeVehicle"
			case .viewScheduleServiceTypeMilestoneDetailNameLabel:
					return "viewScheduleServiceTypeMilestoneDetailNameLabel"
			case .popupSelectTimeSlotUnavailableCallDealership:
					return "popupSelectTimeSlotUnavailableCallDealership"
			case .viewIntro:
					return "viewIntro"
			case .errorSoftUpgradeTitle:
					return "errorSoftUpgradeTitle"
			case .iDontKnow:
					return "iDontKnow"
			case .viewScheduleServiceStatusFeedbackCommentHint:
					return "viewScheduleServiceStatusFeedbackCommentHint"
			case .errorInvalidEmail:
					return "errorInvalidEmail"
			case .popupContactTitle:
					return "popupContactTitle"
			case .errorUserDisabled:
					return "errorUserDisabled"
			case .helpMyVehicleWasDamaged:
					return "helpMyVehicleWasDamaged"
			case .openSettings:
					return "openSettings"
			case .errorPasswordNotMatch:
					return "errorPasswordNotMatch"
			case .popupSelectTimeSlotTimesLabelPickup:
					return "popupSelectTimeSlotTimesLabelPickup"
			case .confirmPhoneNumber:
					return "confirmPhoneNumber"
			case .viewScheduleServiceStatusCompleteInfo:
					return "viewScheduleServiceStatusCompleteInfo"
			case .underTheHood:
					return "underTheHood"
			case .notAvailable:
					return "notAvailable"
			case .viewVehicleAddLabel:
					return "viewVehicleAddLabel"
			case .emailAddress:
					return "emailAddress"
			case .helpTooFewLoanersAvailable:
					return "helpTooFewLoanersAvailable"
			case .viewScheduleServiceTypeOtherDetailExtraHint:
					return "viewScheduleServiceTypeOtherDetailExtraHint"
			case .popupAdvisorDropoffSelfPickup:
					return "popupAdvisorDropoffSelfPickup"
			case .helpThereWasAnIssueWithMyLoanerVehicle:
					return "helpThereWasAnIssueWithMyLoanerVehicle"
			case .helpMyDriverDidntMatchThePicture:
					return "helpMyDriverDidntMatchThePicture"
			case .errorOffline:
					return "errorOffline"
			case .yourAccount:
					return "yourAccount"
			case .helpTermsOfServiceDetail:
					return "helpTermsOfServiceDetail"
			case .settings:
					return "settings"
			case .viewTosContentPrivacyPolicyUrl:
					return "viewTosContentPrivacyPolicyUrl"
			case .viewScheduleServiceTypeOtherDetailExtraTitle:
					return "viewScheduleServiceTypeOtherDetailExtraTitle"
			case .helpTooFewLoanersAvailableDetail:
					return "helpTooFewLoanersAvailableDetail"
			case .viewSignupNameLabel:
					return "viewSignupNameLabel"
			case .helpNoneOfTheAvailableTimesWorkForMeDetail:
					return "helpNoneOfTheAvailableTimesWorkForMeDetail"
			case .helpAppOtherDetail:
					return "helpAppOtherDetail"
			case .popupUpdatingLocation:
					return "popupUpdatingLocation"
			case .viewTosContentTermsOfServiceTitle:
					return "viewTosContentTermsOfServiceTitle"
			case .viewEditTextTitlePhoneNumber:
					return "viewEditTextTitlePhoneNumber"
			case .popupContactCall:
					return "popupContactCall"
			case .viewLogoTitle:
					return "viewLogoTitle"
			case .viewScheduleServiceOptionNoteDropoff:
					return "viewScheduleServiceOptionNoteDropoff"
			case .viewScheduleServiceStatusTimePickupWindow:
					return "viewScheduleServiceStatusTimePickupWindow"
			case .appName:
					return "appName"
			case .viewEmailSubject:
					return "viewEmailSubject"
			case .helpICantArrangeService:
					return "helpICantArrangeService"
			case .add:
					return "add"
			case .helpTroubleWithTheLuxebyVolvoApp:
					return "helpTroubleWithTheLuxebyVolvoApp"
			case .viewSigninEmailLabel:
					return "viewSigninEmailLabel"
			case .helpICantCancelMyPickupOrDeliveryDetail:
					return "helpICantCancelMyPickupOrDeliveryDetail"
			case .currentService:
					return "currentService"
			case .popupPhoneVerificationResendCodeMessage:
					return "popupPhoneVerificationResendCodeMessage"
			case .viewEditTextTitleLastName:
					return "viewEditTextTitleLastName"
			case .popupSelectTimeSlotTimesLabelDelivery:
					return "popupSelectTimeSlotTimesLabelDelivery"
			case .newService:
					return "newService"
			case .viewSigninPhoneContactChangeLabel:
					return "viewSigninPhoneContactChangeLabel"
			case .viewSigninPasswordDescription:
					return "viewSigninPasswordDescription"
			case .errorNoMatchingCustomer:
					return "errorNoMatchingCustomer"
			case .popupAdvisorPickupMessage:
					return "popupAdvisorPickupMessage"
			case .errorOnline:
					return "errorOnline"
			case .viewSettingsDistanceUnitTitle:
					return "viewSettingsDistanceUnitTitle"
			case .color:
					return "color"
			case .contact:
					return "contact"
			case .errorInvalidApplicationVersion:
					return "errorInvalidApplicationVersion"
			case .viewScheduleServiceOptionConfirmButtonPositiveDropoff:
					return "viewScheduleServiceOptionConfirmButtonPositiveDropoff"
			case .errorEmailAlreadyExist:
					return "errorEmailAlreadyExist"
			case .errorDuplicateLoanerVehicleBookingAssignment:
					return "errorDuplicateLoanerVehicleBookingAssignment"
			case .errorIllegalRequestTaskChange:
					return "errorIllegalRequestTaskChange"
			case .helpThereWasAnIssueWithMyPaperwork:
					return "helpThereWasAnIssueWithMyPaperwork"
			case .helpMyDriverWasUnprofessional:
					return "helpMyDriverWasUnprofessional"
			case .permissionLocationTitle:
					return "permissionLocationTitle"
			case .cancelDropoff:
					return "cancelDropoff"
			case .viewVehicleAddYearHint:
					return "viewVehicleAddYearHint"
			case .viewHelpOptionPp:
					return "viewHelpOptionPp"
			case .permissionNotificationMessage:
					return "permissionNotificationMessage"
			case .scheduledDelivery:
					return "scheduledDelivery"
			case .viewScheduleServiceVehicleServiceScheduled:
					return "viewScheduleServiceVehicleServiceScheduled"
			case .signout:
					return "signout"
			case .viewScheduleServiceOptionDropoff:
					return "viewScheduleServiceOptionDropoff"
			case .helpNoParticipatingDealershipsInArea:
					return "helpNoParticipatingDealershipsInArea"
			case .viewHelpOptionDetailCallDealer:
					return "viewHelpOptionDetailCallDealer"
			case .permissionAllowNotificationTitle:
					return "permissionAllowNotificationTitle"
			case .close:
					return "close"
			case .errorPhoneNumberNotInFile:
					return "errorPhoneNumberNotInFile"
			case .scheduleService:
					return "scheduleService"
			case .permissionAllowNotificationMessage:
					return "permissionAllowNotificationMessage"
			case .viewHelpOptionTitle:
					return "viewHelpOptionTitle"
			case .helpSomethingUnsafeHappenedDetail:
					return "helpSomethingUnsafeHappenedDetail"
			case .viewScheduleServiceStatusSelfAdvisorPickup:
					return "viewScheduleServiceStatusSelfAdvisorPickup"
			case .popupSelectLocationPermissionDenied:
					return "popupSelectLocationPermissionDenied"
			case .createPassword:
					return "createPassword"
			case .permissionsLocationDeniedMessage:
					return "permissionsLocationDeniedMessage"
			case .help:
					return "help"
			case .yourLastDelivery:
					return "yourLastDelivery"
			case .viewProfileContactHeader:
					return "viewProfileContactHeader"
			case .errorAmbiguousVehicleUpsert:
					return "errorAmbiguousVehicleUpsert"
			case .number11:
					return "number11"
			case .vehicleInterior:
					return "vehicleInterior"
			case .viewDatesLoanersOnly:
					return "viewDatesLoanersOnly"
			case .viewDealershipCloseToLocation:
					return "viewDealershipCloseToLocation"
			case .helpThereWasAnIssueWithMyLoanerVehicleDetail:
					return "helpThereWasAnIssueWithMyLoanerVehicleDetail"
			case .viewSignupPasswordRequireNumber:
					return "viewSignupPasswordRequireNumber"
			case .helpMyDriverWasLate:
					return "helpMyDriverWasLate"
			case .viewSoftwareLicences:
					return "viewSoftwareLicences"
			case .popupRemoveAddressMessage:
					return "popupRemoveAddressMessage"
			case .cancel:
					return "cancel"
			case .helpICouldntContactMyDriverDetail:
					return "helpICouldntContactMyDriverDetail"
			case .popupDefaultCancelDropoffMessage:
					return "popupDefaultCancelDropoffMessage"
			case .viewEditTextTitleEmail:
					return "viewEditTextTitleEmail"
			case .viewScheduleServiceStatusInfoScheduledDropoff:
					return "viewScheduleServiceStatusInfoScheduledDropoff"
			case .readMore:
					return "readMore"
			case .yes:
					return "yes"
			case .viewEditTextInfoHintPhoneNumber:
					return "viewEditTextInfoHintPhoneNumber"
			case .helpTermsOfService:
					return "helpTermsOfService"
			case .completedService:
					return "completedService"
			case .viewSignupPasswordLabel:
					return "viewSignupPasswordLabel"
			case .viewScheduleServiceStatusSelfDealershipNavigate:
					return "viewScheduleServiceStatusSelfDealershipNavigate"
			case .deliveryLocation:
					return "deliveryLocation"
			case .popupAdvisorDropoffSelfPickupDescription:
					return "popupAdvisorDropoffSelfPickupDescription"
			case .helpNoneOfTheAvailableTimesWorkForMe:
					return "helpNoneOfTheAvailableTimesWorkForMe"
			case .errorForcedUpgradeMessage:
					return "errorForcedUpgradeMessage"
			case .viewEmailIntentChooserTitle:
					return "viewEmailIntentChooserTitle"
			case .viewScheduleService:
					return "viewScheduleService"
			case .helpILostAnItem:
					return "helpILostAnItem"
			case .ok:
					return "ok"
			case .helpICantArrangeServiceDetail:
					return "helpICantArrangeServiceDetail"
			case .viewScheduleServiceOptionInfoPickup:
					return "viewScheduleServiceOptionInfoPickup"
			case .viewHelpOptionTos:
					return "viewHelpOptionTos"
			case .number8:
					return "number8"
			case .popupSelectTimeSlotLabelDropoff:
					return "popupSelectTimeSlotLabelDropoff"
			case .phoneNumberAlreadyTaken:
					return "phoneNumberAlreadyTaken"
			case .refresh:
					return "refresh"
			case .viewPhoneVerificationLabel:
					return "viewPhoneVerificationLabel"
			case .popupSelectTimeSlotLabelDelivery:
					return "popupSelectTimeSlotLabelDelivery"
			case .viewScheduleServiceStatusAtDealershipInfo:
					return "viewScheduleServiceStatusAtDealershipInfo"
			case .map:
					return "map"
			case .scheduleDelivery:
					return "scheduleDelivery"
			case .viewEditTextTitlePassword:
					return "viewEditTextTitlePassword"
			case .viewEditTextTitlePasswordConfirm:
					return "viewEditTextTitlePasswordConfirm"
			case .viewScheduleServiceStatusFeedbackCommentTitle:
					return "viewScheduleServiceStatusFeedbackCommentTitle"
			case .min:
					return "min"
			case .viewScheduleServiceDetailConfirmService:
					return "viewScheduleServiceDetailConfirmService"
			case .errorAccountAlreadyExists:
					return "errorAccountAlreadyExists"
			case .popupSoftUpgradeNegative:
					return "popupSoftUpgradeNegative"
			case .viewScheduleServiceTypeOtherLabel:
					return "viewScheduleServiceTypeOtherLabel"
			case .updateYourPassword:
					return "updateYourPassword"
			case .number9:
					return "number9"
			case .helpSomethingUnsafeHappened:
					return "helpSomethingUnsafeHappened"
			case .viewHelpCategoryHowLuxeByVolvoWorks:
					return "viewHelpCategoryHowLuxeByVolvoWorks"
			case .viewScheduleServiceStatusComplete:
					return "viewScheduleServiceStatusComplete"
			case .popupSelectDealershipLabel:
					return "popupSelectDealershipLabel"
			case .errorInvalidCredentials:
					return "errorInvalidCredentials"
			case .helpICantCancelMyPickupOrDelivery:
					return "helpICantCancelMyPickupOrDelivery"
			case .errorInvalidPhoneNumber:
					return "errorInvalidPhoneNumber"
			case .errorInvalidPhoneNumberFormatted:
					return "errorInvalidPhoneNumberFormatted"
			case .helpIForgotMyPasswordDetail:
					return "helpIForgotMyPasswordDetail"
			case .viewSignupContactLabel:
					return "viewSignupContactLabel"
			case .helpPushNotificationsArentWorking:
					return "helpPushNotificationsArentWorking"
			case .viewTosContentPrivacyPolicyTitle:
					return "viewTosContentPrivacyPolicyTitle"
			case .viewScheduleServiceTypeDescription:
					return "viewScheduleServiceTypeDescription"
			case .viewScheduleServiceOptionInfoSelfPickup:
					return "viewScheduleServiceOptionInfoSelfPickup"
			case .helpMyPickupDeliveryLocationWasWrongDetail:
					return "helpMyPickupDeliveryLocationWasWrongDetail"
			case .viewRatingRangeValueTen:
					return "viewRatingRangeValueTen"
			case .popupSelectTimeSlotUnavailableLabel:
					return "popupSelectTimeSlotUnavailableLabel"
			case .popupAdvisorDropoffReschedule:
					return "popupAdvisorDropoffReschedule"
			case .viewScheduleServiceStatusInServiceInfo:
					return "viewScheduleServiceStatusInServiceInfo"
			case .errorInvalidFirstName:
					return "errorInvalidFirstName"
			case .pickup:
					return "pickup"
			case .popupAdvisorDropoffMessage:
					return "popupAdvisorDropoffMessage"
			case .number7:
					return "number7"
			case .popupSelectTimeSlotUnavailableCallDealershipNotAvailable:
					return "popupSelectTimeSlotUnavailableCallDealershipNotAvailable"
			case .next:
					return "next"
			case .viewScheduleServiceTypeDetailNameLabelMilestone:
					return "viewScheduleServiceTypeDetailNameLabelMilestone"
			case .helpIMissedMyPickupDeliveryDetail:
					return "helpIMissedMyPickupDeliveryDetail"
			case .viewEditTextTitleFirstName:
					return "viewEditTextTitleFirstName"
			case .popupRemoveVehicleMessage:
					return "popupRemoveVehicleMessage"
			case .remove:
					return "remove"
			case .change:
					return "change"
			case .errorInvalidLastName:
					return "errorInvalidLastName"
			case .permissionsLocationDeniedTitle:
					return "permissionsLocationDeniedTitle"
			case .viewScheduleServiceScheduledLabel:
					return "viewScheduleServiceScheduledLabel"
			case .helpDeleteMyLuxebyVolvoAccount:
					return "helpDeleteMyLuxebyVolvoAccount"
			case .edit:
					return "edit"
			case .popupSelectLocationPermissionNote:
					return "popupSelectLocationPermissionNote"
			case .viewScheduleServiceStatusReminderPickup:
					return "viewScheduleServiceStatusReminderPickup"
			case .errorAmbiguousCustomerUpsert:
					return "errorAmbiguousCustomerUpsert"
			case .viewScheduleServiceStatusFeedbackCommentLabel:
					return "viewScheduleServiceStatusFeedbackCommentLabel"
			case .errorLocationServiceNotOfferedInYourArea:
					return "errorLocationServiceNotOfferedInYourArea"
			case .helpPushNotificationsArentWorkingDetail:
					return "helpPushNotificationsArentWorkingDetail"
			case .errorInvalidVerificationCode:
					return "errorInvalidVerificationCode"
			case .errorSoftUpgradeMessage:
					return "errorSoftUpgradeMessage"
			case .viewScheduleServiceStatusCompleteTitle:
					return "viewScheduleServiceStatusCompleteTitle"
			case .viewScheduledSelfDrop:
					return "viewScheduledSelfDrop"
			case .viewSignupPasswordDescription:
					return "viewSignupPasswordDescription"
			case .viewScheduleServiceStatusInfoNearBy:
					return "viewScheduleServiceStatusInfoNearBy"
			case .vehicleExterior:
					return "vehicleExterior"
			case .number3:
					return "number3"
			case .notNow:
					return "notNow"
			case .helpMyPickupDeliveryLocationWasWrong:
					return "helpMyPickupDeliveryLocationWasWrong"
			case .errorPhoneNumberAlreadyExist:
					return "errorPhoneNumberAlreadyExist"
			case .dealership:
					return "dealership"
			case .helpICantUpdateMyPhone:
					return "helpICantUpdateMyPhone"
			case .viewScheduleServiceStatusTimeWindowEstimatedDelivery:
					return "viewScheduleServiceStatusTimeWindowEstimatedDelivery"
			case .mins:
					return "mins"
			case .number2:
					return "number2"
			case .errorDuplicateRequest:
					return "errorDuplicateRequest"
			case .viewScheduleServiceTypeOtherSubLabel:
					return "viewScheduleServiceTypeOtherSubLabel"
			case .viewHelpOptionDetailCallVolvo:
					return "viewHelpOptionDetailCallVolvo"
			case .errorInvalidUserDisabled:
					return "errorInvalidUserDisabled"
			case .popupSelectLocationCurrentLocation:
					return "popupSelectLocationCurrentLocation"
			case .done:
					return "done"
			case .later:
					return "later"
			case .viewSettingsSoftwareLicencesTitle:
					return "viewSettingsSoftwareLicencesTitle"
			case .unknown:
					return "unknown"
			case .helpMyDriverWasUnprofessionalDetail:
					return "helpMyDriverWasUnprofessionalDetail"
			case .popupContactText:
					return "popupContactText"
			case .popupSelectLocationLabel:
					return "popupSelectLocationLabel"
			case .errorUpdatePhoneNumberAlreadyExist:
					return "errorUpdatePhoneNumberAlreadyExist"
			case .helpMyDriverWasLateDetail:
					return "helpMyDriverWasLateDetail"
			case .viewIntroFooterSignup:
					return "viewIntroFooterSignup"
			case .helpTheAppIsntWorkingCorrectlyDetail:
					return "helpTheAppIsntWorkingCorrectlyDetail"
			case .popupAdvisorDropoffLabel:
					return "popupAdvisorDropoffLabel"
			case .viewScheduleServiceOptionNotePickup:
					return "viewScheduleServiceOptionNotePickup"
			case .helpMyDriverDidntMatchThePictureDetail:
					return "helpMyDriverDidntMatchThePictureDetail"
			case .skip:
					return "skip"
			case .viewSigninNameLabel:
					return "viewSigninNameLabel"
			case .popupDefaultCancelPickupMessage:
					return "popupDefaultCancelPickupMessage"
			case .helpMyCurrentLocationIsntWorking:
					return "helpMyCurrentLocationIsntWorking"
			case .errorForcedUpgradeTitle:
					return "errorForcedUpgradeTitle"
			case .errorLocationOutOfDropoffArea:
					return "errorLocationOutOfDropoffArea"
			case .viewEditTextInfoHintLastName:
					return "viewEditTextInfoHintLastName"
			case .selectedService:
					return "selectedService"
			case .viewSigninForgotPassword:
					return "viewSigninForgotPassword"
			case .errorRemoveVehicleError:
					return "errorRemoveVehicleError"
			case .helpOther:
					return "helpOther"
			case .volvoYearModel:
					return "volvoYearModel"
			case .viewScheduleServiceStatusSelfAdvisorDropoff:
					return "viewScheduleServiceStatusSelfAdvisorDropoff"
			case .number5:
					return "number5"
			case .popupAdvisorDropoffRescheduleDescription:
					return "popupAdvisorDropoffRescheduleDescription"
			case .errorInvalidPassword:
					return "errorInvalidPassword"
			case .helpThereWasAnIssueWithMyPaperworkDetail:
					return "helpThereWasAnIssueWithMyPaperworkDetail"
			case .errorVerifyPhoneNumber:
					return "errorVerifyPhoneNumber"
			case .viewProfileLocationHeader:
					return "viewProfileLocationHeader"
			case .viewScheduleServiceOptionPickupSelfDeliveryDropoff:
					return "viewScheduleServiceOptionPickupSelfDeliveryDropoff"
			case .toastSettingsLocationDisabled:
					return "toastSettingsLocationDisabled"
			case .helpTheAppIsntWorkingCorrectly:
					return "helpTheAppIsntWorkingCorrectly"
			case .viewScheduleServiceStatusTimeDeliveryWindow:
					return "viewScheduleServiceStatusTimeDeliveryWindow"
			case .viewScheduleServiceStatusInfoEnRoute:
					return "viewScheduleServiceStatusInfoEnRoute"
			case .helpOtherDetail:
					return "helpOtherDetail"
			case .changePhoneNumber:
					return "changePhoneNumber"
			case .permissionAllowButtonTitle:
					return "permissionAllowButtonTitle"
			case .viewSettingsVolvoAddNewLabel:
					return "viewSettingsVolvoAddNewLabel"
			case .viewTosContentPrivacyPolicy:
					return "viewTosContentPrivacyPolicy"
			case .yourVolvo:
					return "yourVolvo"
			case .phoneNumberCannotBeEmpty:
					return "phoneNumberCannotBeEmpty"
			case .number6:
					return "number6"
			case .viewVehicleAddModelHint:
					return "viewVehicleAddModelHint"
			case .model:
					return "model"
			case .popupSelectTimeSlotLabelPickup:
					return "popupSelectTimeSlotLabelPickup"
			case .viewScheduleServiceTypeOtherUnknown:
					return "viewScheduleServiceTypeOtherUnknown"
			case .helpICantUpdateMyPhoneDetail:
					return "helpICantUpdateMyPhoneDetail"
			case .number10:
					return "number10"
			case .helpDeleteMyLuxebyVolvoAccountDetail:
					return "helpDeleteMyLuxebyVolvoAccountDetail"
			case .viewProfileAccountPasswordHeader:
					return "viewProfileAccountPasswordHeader"
			case .needALoaner:
					return "needALoaner"
			case .helpPrivacyPolicyInformation:
					return "helpPrivacyPolicyInformation"
			case .addNewLocation:
					return "addNewLocation"
			case .imNotSure:
					return "imNotSure"
			case .viewScheduleServiceTypeOtherDetail:
					return "viewScheduleServiceTypeOtherDetail"
			case .errorLocationServiceUnavailable:
					return "errorLocationServiceUnavailable"
			case .viewTosContentTermsOfServiceUrl:
					return "viewTosContentTermsOfServiceUrl"
			case .errorInvalidCharacter:
					return "errorInvalidCharacter"
			case .errorDatabase:
					return "errorDatabase"
			case .delivery:
					return "delivery"
			case .helpICouldntContactMyDriver:
					return "helpICouldntContactMyDriver"
			case .helpIForgotMyPassword:
					return "helpIForgotMyPassword"
			case .viewHelpCategoryTroubleWithLuxeByVolvoApp:
					return "viewHelpCategoryTroubleWithLuxeByVolvoApp"
			case .viewIntroFooterSignin:
					return "viewIntroFooterSignin"
			case .viewEmailBody:
					return "viewEmailBody"
			case .viewTosContentTermsOfService:
					return "viewTosContentTermsOfService"
			case .helpRequestingDataFromLuxebyVolvoDetail:
					return "helpRequestingDataFromLuxebyVolvoDetail"
			case .number4:
					return "number4"
			case .passwordRequirements:
					return "passwordRequirements"
			case .errorInvalidPasswordUnauthorizedCharacters:
					return "errorInvalidPasswordUnauthorizedCharacters"
			case .errorPhoneNumberTaken:
					return "errorPhoneNumberTaken"
			case .viewScheduleServiceStatusTimeWindowEstimatedPickup:
					return "viewScheduleServiceStatusTimeWindowEstimatedPickup"
        }
    }
    
    var description: String {
        return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
    }
    
    func with(_ args: CVarArg...) -> String {
        let format = description
        return String(format: format, arguments: args)
    }
    
}

extension String {
    static func localized(_ localized: Localized) -> String {
        return localized.description
    }
}
